'use strict';

const APP_VERSION='7.1-web';
const DB_KEY='asArcadeMobileDB';
const AVATARS=AVATAR_PRESETS.map(p=>p.id);
const THEMES=['neon','sunset','forest','royal','sky','candy'];
const WALLPAPERS=['none','grid','stars','candy'];
const BANNERS=['Arcade Explorer','High Score Hero','Puzzle Master','Racing Champion','Creative Star','Family Game Night','Adventure Ace','Strategy Captain'];
const CATEGORY_ICONS={Arcade:'🕹️',Adventure:'🗺️',Puzzle:'🧩',Strategy:'♟️',Sports:'🏆',Shooter:'🚀',Word:'🔤',Learning:'📚',Creative:'🎨',Casual:'🎯',Racing:'🏁',Multiplayer:'👥',Simulation:'⚙️',Cards:'🃏'};
const STORE={
  themes:THEMES.map((name,i)=>({name,cost:i<2?0:80+i*15})),
  wallpapers:WALLPAPERS.map((name,i)=>({name,cost:i===0?0:70+i*20})),
  banners:BANNERS.map((name,i)=>({name,cost:i===0?0:60+i*15})),
  avatars:AVATAR_PRESETS.map((preset,i)=>({name:preset.id,label:preset.name,cost:i<4?0:70+i*15}))
};
const ACHIEVEMENTS=[
  ['First Steps','Play your first game',a=>a.stats.plays>=1],
  ['Level Learner','Complete 10 levels',a=>a.stats.levels>=10],
  ['Arcade Regular','Play 25 different games',a=>Object.keys(a.progress).length>=25],
  ['Coin Collector','Own 100 AG Coins',a=>a.coins>=100],
  ['Game Finisher','Complete a game',a=>a.stats.completed>=1],
  ['Century Club','Complete 100 levels',a=>a.stats.levels>=100],
  ['Family Champion','Win 10 games',a=>a.stats.wins>=10],
  ['Arcade Legend','Reach level 20',a=>levelFromXp(a.xp)>=20]
];
const qs=s=>document.querySelector(s);const qsa=s=>[...document.querySelectorAll(s)];
const views={auth:qs('#authView'),launcher:qs('#launcherView'),game:qs('#gameView')};
const detailsDialog=qs('#detailsDialog'),panelDialog=qs('#panelDialog'),accountDialog=qs('#accountDialog');
let deferredInstall=null;let currentGame=null;let session=null;let activeAccountId=null;

function defaultDB(){return{version:1,adminHash:'',active:null,accounts:[]}}
function loadDB(){try{const d=JSON.parse(localStorage.getItem(DB_KEY));return d&&Array.isArray(d.accounts)?d:defaultDB()}catch{return defaultDB()}}
function migrateDB(d){
  let changed=false;d.version=2;
  for(const a of d.accounts){
    const normalized=normalizeAvatar(a.avatar);if(JSON.stringify(normalized)!==JSON.stringify(a.avatar)){a.avatar=normalized;changed=true}
    a.unlocks=a.unlocks||{};a.unlocks.avatars=Array.isArray(a.unlocks.avatars)?a.unlocks.avatars.filter(x=>AVATARS.includes(x)):AVATARS.slice(0,4);
    if(!a.unlocks.avatars.length)a.unlocks.avatars=AVATARS.slice(0,4);
    a.settings=a.settings||{};
  }
  if(changed)saveDB(d);return d;
}
function saveDB(db){localStorage.setItem(DB_KEY,JSON.stringify(db))}
let db=migrateDB(loadDB());
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function randomAvatarConfig(){const c=defaultAvatarConfig();for(const key of Object.keys(c))c[key]=Math.floor(Math.random()*(AVATAR_OPTIONS[key]?.length||1));return c}
async function hashText(text){if(crypto.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return String(h>>>0)}
function account(){return db.accounts.find(a=>a.id===activeAccountId)||null}
function updateAccount(fn){const a=account();if(!a)return;fn(a);a.updatedAt=Date.now();saveDB(db);refreshHeader();refreshAchievements(a)}
function newAccount(username,displayName,pinHash,type,avatar){return{id:uid(),username,displayName:displayName||username,pinHash,type,enabled:true,avatar:normalizeAvatar(avatar),coins:20,xp:0,banner:BANNERS[0],settings:{theme:'neon',wallpaper:'stars',reducedMotion:false,highContrast:false,sound:true},unlocks:{themes:['neon','sunset'],wallpapers:['none','stars'],banners:[BANNERS[0]],avatars:AVATARS.slice(0,4)},favorites:[],progress:{},achievements:[],stats:{plays:0,levels:0,completed:0,wins:0,seconds:0},daily:{date:'',plays:0,levels:0,claimed:false},parental:{minutes:0,multiplayer:true,spending:true,categories:[],external:false},createdAt:Date.now()}}
function levelFromXp(xp){return Math.max(1,Math.floor(Math.sqrt(Math.max(0,xp)/80))+1)}
function xpForNext(level){return level*level*80}
function toast(text){const el=qs('#toast');el.textContent=text;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2500)}
function showView(name){Object.values(views).forEach(v=>v.classList.remove('active'));views[name].classList.add('active');window.scrollTo(0,0)}
function openDialog(dialog){dialog.showModal()}
function closeDialogs(){qsa('dialog[open]').forEach(d=>d.close())}
qsa('.close-dialog').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));

function applyTheme(){const a=account();document.body.className='';if(!a)return;document.body.classList.add(`theme-${a.settings.theme}`,`wallpaper-${a.settings.wallpaper}`);if(a.settings.highContrast)document.body.classList.add('high-contrast');if(a.settings.reducedMotion)document.body.classList.add('reduced-motion')}
function refreshAuth(){const sel=qs('#accountSelect');sel.innerHTML='';db.accounts.filter(a=>a.enabled).forEach(a=>sel.add(new Option(`${a.displayName} — ${avatarLabel(a.avatar)}`,a.id)));if(!sel.options.length)sel.add(new Option('Create an account first',''));qs('#loginPin').value='';refreshLoginAvatarPreview()}
function refreshLoginAvatarPreview(){const selected=db.accounts.find(a=>a.id===qs('#accountSelect').value&&a.enabled);qs('#loginAvatarPreview').innerHTML=avatarSVG(selected?selected.avatar:defaultAvatarConfig(),108)}
function refreshHeader(){const a=account();if(!a)return;qs('#avatarButton').innerHTML=avatarSVG(a.avatar,58);qs('#welcomeText').textContent=`Welcome, ${a.displayName}`;qs('#bannerText').textContent=a.banner;qs('#levelText').textContent=levelFromXp(a.xp);qs('#xpText').textContent=a.xp;qs('#coinText').textContent=a.coins;applyTheme();const d=todayDaily(a);qs('#dailySummary').textContent=`Daily: ${d.plays}/3 games • ${d.levels}/2 levels`}
function refreshAchievements(a){let changed=false;for(const [name,,test] of ACHIEVEMENTS){if(test(a)&&!a.achievements.includes(name)){a.achievements.push(name);a.xp+=50;changed=true;toast(`🏆 Achievement unlocked: ${name}`)}}if(changed)saveDB(db)}
function todayKey(){return new Date().toISOString().slice(0,10)}
function todayDaily(a){if(a.daily.date!==todayKey())a.daily={date:todayKey(),plays:0,levels:0,claimed:false};return a.daily}
function claimDaily(a){const d=todayDaily(a);if(d.claimed)return toast('Daily reward already claimed');if(d.plays>=3&&d.levels>=2){d.claimed=true;a.coins+=8;a.xp+=60;saveDB(db);refreshHeader();toast('Daily challenge complete: +8 AG Coins and +60 XP')}else toast('Play 3 games and complete 2 levels first')}

qs('#createBtn').addEventListener('click',()=>openCreateAccount());
qs('#parentBtn').addEventListener('click',()=>openParentalControls(true));
qs('#loginBtn').addEventListener('click',login);
qs('#loginPin').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
qs('#accountSelect').addEventListener('change',refreshLoginAvatarPreview);
qs('#logoutBtn').addEventListener('click',()=>{if(session)session.stop();activeAccountId=null;db.active=null;saveDB(db);applyTheme();refreshAuth();showView('auth')});
qs('#backToLauncher').addEventListener('click',exitGame);
qs('#pauseBtn').addEventListener('click',()=>session&&session.togglePause());
qs('#avatarButton').addEventListener('click',()=>openPanel('settingsPanel'));
qs('#favoritesOnly').addEventListener('change',renderGames);qs('#categorySelect').addEventListener('change',renderGames);qs('#searchInput').addEventListener('input',renderGames);
qsa('[data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));
qsa('[data-key]').forEach(button=>{
  const key=button.dataset.key;
  const down=e=>{e.preventDefault();session&&session.setKey(key,true)};const up=e=>{e.preventDefault();session&&session.setKey(key,false)};
  button.addEventListener('pointerdown',down);button.addEventListener('pointerup',up);button.addEventListener('pointercancel',up);button.addEventListener('pointerleave',up);
});
window.addEventListener('keydown',e=>{if(session){if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){session.togglePause();return}session.setKey(e.code,true)}});
window.addEventListener('keyup',e=>session&&session.setKey(e.code,false));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;qs('#installBtn').classList.remove('hidden')});
qs('#installBtn').addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;qs('#installBtn').classList.add('hidden')});

async function login(){const id=qs('#accountSelect').value;const a=db.accounts.find(x=>x.id===id);if(!a)return toast('Create an account first');if(!a.enabled)return toast('This account is disabled');const hash=await hashText(qs('#loginPin').value);if(hash!==a.pinHash)return toast('Incorrect PIN');activeAccountId=id;db.active=id;saveDB(db);todayDaily(a);refreshHeader();renderLauncher();showView('launcher')}
function openCreateAccount(){
  qs('#newUsername').value='';qs('#newDisplayName').value='';qs('#newPin').value='';
  const controls=qs('#newAvatarControls'),preview=qs('#newAvatarPreview');
  controls.innerHTML=avatarControlMarkup('new-avatar',defaultAvatarConfig());
  const redraw=()=>preview.innerHTML=avatarSVG(readAvatarControls(controls),164);
  controls.querySelectorAll('select').forEach(el=>el.addEventListener('change',redraw));
  qs('#randomizeNewAvatar').onclick=()=>{controls.innerHTML=avatarControlMarkup('new-avatar',randomAvatarConfig());controls.querySelectorAll('select').forEach(el=>el.addEventListener('change',redraw));redraw()};
  redraw();openDialog(accountDialog)
}
qs('#saveAccountBtn').addEventListener('click',async()=>{const username=qs('#newUsername').value.trim();const pin=qs('#newPin').value.trim();if(username.length<2)return toast('Username needs at least 2 characters');if(pin.length<4)return toast('PIN needs at least 4 characters');if(db.accounts.some(a=>a.username.toLowerCase()===username.toLowerCase()))return toast('Username already exists');const avatar=readAvatarControls(qs('#newAvatarControls'));const a=newAccount(username,qs('#newDisplayName').value.trim(),await hashText(pin),qs('#newAccountType').value,avatar);db.accounts.push(a);saveDB(db);accountDialog.close();refreshAuth();toast('Account created')});

function renderLauncher(){const cats=['All',...new Set(ARCADE_GAMES.map(g=>g.category))];const sel=qs('#categorySelect');if(!sel.options.length)cats.forEach(c=>sel.add(new Option(c,c)));renderGames()}
function renderGames(){const a=account();if(!a)return;const q=qs('#searchInput').value.trim().toLowerCase(),cat=qs('#categorySelect').value||'All',fav=qs('#favoritesOnly').checked;let games=ARCADE_GAMES.filter(g=>(!q||(g.name+' '+g.description).toLowerCase().includes(q))&&(cat==='All'||g.category===cat)&&(!fav||a.favorites.includes(g.id)));qs('#gameCount').textContent=`${games.length} of ${ARCADE_GAMES.length} games`;const grid=qs('#gameGrid');grid.innerHTML='';for(const g of games){const card=document.createElement('article');card.className='game-card';card.dataset.gameId=g.id;const p=a.progress[g.id]||{};card.innerHTML=`<button class="favorite" aria-label="Favorite">${a.favorites.includes(g.id)?'★':'☆'}</button><div class="category-icon">${CATEGORY_ICONS[g.category]||'🎲'}</div><h3>${escapeHtml(g.name)} ${g.new?'<span class="new-badge">NEW</span>':''}</h3><p>${escapeHtml(g.description)}</p><div class="meta"><span>${escapeHtml(g.category)}</span><span>${p.level?`Level ${p.level}`:'New'}</span></div>`;card.querySelector('.favorite').onclick=e=>{e.stopPropagation();toggleFavorite(g.id)};card.onclick=()=>showDetails(g);grid.append(card)}}
function toggleFavorite(id){updateAccount(a=>{const i=a.favorites.indexOf(id);i>=0?a.favorites.splice(i,1):a.favorites.push(id)});renderGames()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function objective(g){return g.description.endsWith('.')?g.description:g.description+'.'}
function howTo(g){const map={Arcade:'React quickly, avoid hazards, collect useful items, and reach the level target.',Adventure:'Explore the stage, collect required objects, avoid danger, and reach the exit.',Puzzle:'Study the board and use touch controls to solve the target with as few moves as possible.',Strategy:'Follow the displayed board rules, plan ahead, and defeat the opponent or puzzle.',Sports:'Control your player, time actions carefully, and outscore the opponent.',Shooter:'Move to avoid attacks, aim, fire, and clear the enemy wave.',Word:'Read the prompt, select or enter the correct letters and words.',Learning:'Answer each activity carefully and build accuracy as difficulty rises.',Creative:'Use touch gestures and tools to create, draw, or design freely.',Casual:'Follow the simple target and replay to improve your score.',Racing:'Steer safely, avoid obstacles, and reach the finish target.',Multiplayer:'Use both on-screen control clusters for two players, or play against the built-in opponent.',Simulation:'Manage resources, purchase upgrades, and reach the stage target.',Cards:'Follow the turn order and use valid combinations to win.'};return map[g.category]||'Follow the on-screen objective and controls.'}
function showDetails(g){currentGame=g;const a=account(),p=a.progress[g.id]||{level:1,highScore:0};qs('#detailsContent').innerHTML=`<div style="font-size:3rem">${CATEGORY_ICONS[g.category]||'🎲'}</div><h2>${escapeHtml(g.name)}</h2><p><b>${escapeHtml(g.category)}</b> • ${g.levels} levels • ${g.engine==='arena'?'Multiplayer':'One player'}</p><div class="panel-card"><h3>Objective</h3><p>${escapeHtml(objective(g))}</p><h3>How to play</h3><p>${escapeHtml(howTo(g))}</p><h3>Controls</h3><p>${escapeHtml(g.controls)}. The mobile controls remain at the bottom of the game page.</p><h3>Progress</h3><p>Resume level ${p.level||1} • High score ${p.highScore||0}</p><p><b>Rewards:</b> 1 AG Coin for each new level and 5 bonus coins for completing the game.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><button id="startNew" class="primary">Start New Game</button><button id="resumeGame">Resume Level ${p.level||1}</button><button id="detailFavorite">${a.favorites.includes(g.id)?'Remove Favorite':'Add Favorite'}</button></div>`;openDialog(detailsDialog);qs('#startNew').onclick=()=>{detailsDialog.close();startGame(g,1)};qs('#resumeGame').onclick=()=>{detailsDialog.close();startGame(g,p.level||1)};qs('#detailFavorite').onclick=()=>{toggleFavorite(g.id);detailsDialog.close()}}

function openPanel(type){const a=account();if(!a&&type!=='parentPanel')return;const out=qs('#panelContent');if(type==='dailyPanel'){const d=todayDaily(a);out.innerHTML=`<h2>Daily Challenges</h2><div class="panel-grid"><div class="panel-card"><h3>Play 3 games</h3><p>${d.plays}/3</p></div><div class="panel-card"><h3>Complete 2 levels</h3><p>${d.levels}/2</p></div><div class="panel-card"><h3>Reward</h3><p>8 AG Coins + 60 XP</p></div></div><button id="claimDaily" class="primary">Claim Reward</button>`;openDialog(panelDialog);qs('#claimDaily').onclick=()=>claimDaily(a);return}
  if(type==='storePanel'){renderStore(out,a);openDialog(panelDialog);return}
  if(type==='achievementPanel'){renderAchievements(out,a);openDialog(panelDialog);return}
  if(type==='leaderboardPanel'){renderLeaderboards(out);openDialog(panelDialog);return}
  if(type==='settingsPanel'){renderSettings(out,a);openDialog(panelDialog);return}
  if(type==='parentPanel'){openParentalControls(false);return}}
function renderStore(out,a){
  if(!a.parental.spending){out.innerHTML='<h2>AG Store</h2><p>Coin spending is disabled by Parental Controls.</p>';return}
  const section=(title,key,items)=>`<h3>${title}</h3><div class="panel-grid">${items.map(it=>{const owned=a.unlocks[key].includes(it.name);const visual=key==='avatars'?`<div class="avatar-mini">${avatarSVG(avatarPreset(it.name).config,46)}</div>`:'';return`<div class="panel-card store-item ${owned?'':'locked'}">${visual}<b>${escapeHtml(it.label||it.name)}</b><p>${owned?'Owned':`${it.cost} AG Coins`}</p><button data-store="${key}" data-item="${escapeHtml(it.name)}" data-cost="${it.cost}">${owned?'Apply':'Unlock'}</button></div>`}).join('')}</div>`;
  out.innerHTML=`<h2>AG Store</h2><p>Balance: 🪙 ${a.coins}. Avatar presets now apply a complete, polished character design.</p>${section('Themes','themes',STORE.themes)}${section('Wallpapers','wallpapers',STORE.wallpapers)}${section('Banners','banners',STORE.banners)}${section('Avatar Presets','avatars',STORE.avatars)}`;
  out.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>buyStore(b.dataset.store,b.dataset.item,+b.dataset.cost))
}
function buyStore(key,item,cost){updateAccount(a=>{const owned=a.unlocks[key].includes(item);if(!owned){if(a.coins<cost){toast('Not enough AG Coins');return}a.coins-=cost;a.unlocks[key].push(item)}if(key==='themes')a.settings.theme=item;if(key==='wallpapers')a.settings.wallpaper=item;if(key==='banners')a.banner=item;if(key==='avatars')a.avatar=cloneAvatar(avatarPreset(item).config);toast(`${key==='avatars'?avatarPreset(item).name:item} applied`) });renderStore(qs('#panelContent'),account());renderGames()}
function renderAchievements(out,a){refreshAchievements(a);out.innerHTML=`<h2>Trophy Room</h2><div class="panel-grid">${ACHIEVEMENTS.map(([n,d])=>`<div class="panel-card"><h3>${a.achievements.includes(n)?'🏆':'🔒'} ${n}</h3><p>${d}</p></div>`).join('')}</div>`}
function renderLeaderboards(out){const rows=[...db.accounts].sort((a,b)=>b.xp-a.xp);out.innerHTML=`<h2>Local Family Leaderboards</h2><div class="panel-grid">${rows.map((a,i)=>`<div class="panel-card"><div class="profile-card-heading"><span class="avatar-mini">${avatarSVG(a.avatar,46)}</span><h3>#${i+1} ${escapeHtml(a.displayName)}</h3></div><p>Level ${levelFromXp(a.xp)} • ${a.xp} XP • ${a.coins} coins</p><p>${a.stats.levels} levels • ${a.stats.completed} games completed</p></div>`).join('')}</div>`}
function renderSettings(out,a){
  out.innerHTML=`<h2>Customize & Accessibility</h2><p class="update-notice">Your avatar is now a layered, original 3D-style character instead of a single emoji.</p><div class="avatar-studio-layout"><div><div id="settingsAvatarPreview" class="avatar-preview-large">${avatarSVG(a.avatar,164)}</div><div class="avatar-actions"><button id="randomizeAvatar">Surprise Me</button></div></div><div id="settingsAvatarControls" class="avatar-control-grid">${avatarControlMarkup('settings-avatar',a.avatar)}</div></div><h3>Quick Avatar Presets</h3><div class="avatar-preset-grid">${a.unlocks.avatars.map(id=>{const p=avatarPreset(id);return`<button class="avatar-preset" data-avatar-preset="${id}">${avatarSVG(p.config,76)}<span>${escapeHtml(p.name)}</span></button>`}).join('')}</div><label>Theme<select id="themeSetting">${a.unlocks.themes.map(x=>`<option ${x===a.settings.theme?'selected':''}>${x}</option>`).join('')}</select></label><label>Wallpaper<select id="wallpaperSetting">${a.unlocks.wallpapers.map(x=>`<option ${x===a.settings.wallpaper?'selected':''}>${x}</option>`).join('')}</select></label><label>Banner<select id="bannerSetting">${a.unlocks.banners.map(x=>`<option ${x===a.banner?'selected':''}>${x}</option>`).join('')}</select></label><label class="check"><input id="contrastSetting" type="checkbox" ${a.settings.highContrast?'checked':''}> High contrast</label><label class="check"><input id="motionSetting" type="checkbox" ${a.settings.reducedMotion?'checked':''}> Reduced motion</label><button id="saveSettings" class="primary">Save Changes</button>`;
  const controls=qs('#settingsAvatarControls'),preview=qs('#settingsAvatarPreview');
  const redraw=()=>preview.innerHTML=avatarSVG(readAvatarControls(controls),164);
  controls.querySelectorAll('select').forEach(el=>el.addEventListener('change',redraw));
  qs('#randomizeAvatar').onclick=()=>{controls.innerHTML=avatarControlMarkup('settings-avatar',randomAvatarConfig());controls.querySelectorAll('select').forEach(el=>el.addEventListener('change',redraw));redraw()};
  out.querySelectorAll('[data-avatar-preset]').forEach(btn=>btn.onclick=()=>{controls.innerHTML=avatarControlMarkup('settings-avatar',avatarPreset(btn.dataset.avatarPreset).config);controls.querySelectorAll('select').forEach(el=>el.addEventListener('change',redraw));redraw()});
  qs('#saveSettings').onclick=()=>{updateAccount(x=>{x.settings.theme=qs('#themeSetting').value;x.settings.wallpaper=qs('#wallpaperSetting').value;x.banner=qs('#bannerSetting').value;x.avatar=readAvatarControls(controls);x.settings.highContrast=qs('#contrastSetting').checked;x.settings.reducedMotion=qs('#motionSetting').checked});panelDialog.close();renderGames();toast('Customization saved')}
}

async function openParentalControls(fromAuth){const pin=prompt(db.adminHash?'Enter the Parental Controls administrator PIN':'Create a Parental Controls administrator PIN (4+ characters)');if(pin===null)return;if(pin.length<4)return toast('Administrator PIN needs at least 4 characters');const h=await hashText(pin);if(!db.adminHash){db.adminHash=h;saveDB(db);toast('Administrator PIN created')}else if(h!==db.adminHash)return toast('Incorrect administrator PIN');renderParentPanel(qs('#panelContent'));openDialog(panelDialog)}
function renderParentPanel(out){out.innerHTML=`<h2>Parental Controls</h2><p>Manage accounts without knowing the player's PIN. Existing PINs cannot be displayed, but they can be reset.</p><div class="panel-grid">${db.accounts.map(a=>`<div class="panel-card" data-account="${a.id}"><div class="profile-card-heading"><span class="avatar-mini">${avatarSVG(a.avatar,46)}</span><h3>${escapeHtml(a.displayName)}</h3></div><p>${a.type} • ${a.enabled?'Enabled':'Disabled'}</p><label>Daily minutes<input class="limit" type="number" min="0" value="${a.parental.minutes}"></label><label class="check"><input class="multi" type="checkbox" ${a.parental.multiplayer?'checked':''}> Multiplayer allowed</label><label class="check"><input class="spend" type="checkbox" ${a.parental.spending?'checked':''}> AG Coin spending</label><button class="save-parent">Save</button><button class="reset-pin">Reset Player PIN</button><button class="toggle-account">${a.enabled?'Disable':'Enable'} Account</button></div>`).join('')}</div>`;out.querySelectorAll('[data-account]').forEach(card=>{const a=db.accounts.find(x=>x.id===card.dataset.account);card.querySelector('.save-parent').onclick=()=>{a.parental.minutes=Math.max(0,+card.querySelector('.limit').value||0);a.parental.multiplayer=card.querySelector('.multi').checked;a.parental.spending=card.querySelector('.spend').checked;saveDB(db);toast('Parental controls saved')};card.querySelector('.toggle-account').onclick=()=>{a.enabled=!a.enabled;saveDB(db);renderParentPanel(out);refreshAuth()};card.querySelector('.reset-pin').onclick=async()=>{const p=prompt(`Enter a new PIN for ${a.displayName}`);if(p&&p.length>=4){a.pinHash=await hashText(p);saveDB(db);toast('Player PIN reset')}}})}

function startGame(g,level){const a=account();if(!a)return;if(g.engine==='arena'&&!a.parental.multiplayer)return toast('Multiplayer is blocked by Parental Controls');const d=todayDaily(a);d.plays++;a.stats.plays++;const prog=a.progress[g.id]||(a.progress[g.id]={level:1,completedLevels:[],highScore:0,finished:false,plays:0});prog.plays++;saveDB(db);currentGame=g;showView('game');qs('#gameTitle').textContent=g.name;qs('#gameLevelText').textContent=`Level ${level} of ${g.levels}`;qs('#touchControls').classList.toggle('multiplayer',g.engine==='arena');qs('#gameInstructions').innerHTML=`<h3>${escapeHtml(g.name)} — How to Play</h3><b>Objective:</b> ${escapeHtml(objective(g))}<br><b>How to play:</b> ${escapeHtml(howTo(g))}<br><b>Controls:</b> ${escapeHtml(g.controls)}. Use the touchscreen controls above; they remain at the bottom of the page.<br><b>Rewards:</b> 1 coin for a new level and 5 bonus coins for completing all ${g.levels} levels.`;session=new GameSession(g,level);session.start()}
function exitGame(){if(session){session.stop();session=null}showView('launcher');refreshHeader();renderGames()}
function completeLevel(score=0){if(!session||session.completed)return;session.completed=true;const g=session.game,level=session.level;updateAccount(a=>{const p=a.progress[g.id]||(a.progress[g.id]={level:1,completedLevels:[],highScore:0,finished:false,plays:0});p.highScore=Math.max(p.highScore||0,Math.round(score));let reward=0;if(!p.completedLevels.includes(level)){p.completedLevels.push(level);a.coins+=1;a.xp+=25+level;a.stats.levels++;todayDaily(a).levels++;reward++}if(level>=g.levels&&!p.finished){p.finished=true;a.coins+=5;a.xp+=100;a.stats.completed++;a.stats.wins++;reward+=5}p.level=level>=g.levels?g.level:level+1;session.reward=reward});session.showResult(true,score)}
function failLevel(score=0){if(!session||session.completed)return;session.completed=true;session.showResult(false,score)}

class GameSession{
  constructor(game,level){this.game=game;this.level=level;this.canvas=qs('#gameCanvas');this.ctx=this.canvas.getContext('2d');this.keys=new Set();this.running=false;this.paused=false;this.completed=false;this.reward=0;this.last=0;this.elapsed=0;this.pointer={x:0,y:0,down:false};this.state={};this.boundPointer=e=>this.handlePointer(e);this.boundPointerUp=e=>{this.pointer.down=false;this.engine.pointerUp?.(this.pointer)};this.engine=this.createEngine()}
  start(){this.running=true;this.canvas.addEventListener('pointerdown',this.boundPointer);this.canvas.addEventListener('pointermove',this.boundPointer);window.addEventListener('pointerup',this.boundPointerUp);this.engine.init?.();this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}
  stop(){this.running=false;this.canvas.removeEventListener('pointerdown',this.boundPointer);this.canvas.removeEventListener('pointermove',this.boundPointer);window.removeEventListener('pointerup',this.boundPointerUp);this.engine.cleanup?.();qs('#gameOverlay').classList.add('hidden')}
  setKey(key,on){on?this.keys.add(key):this.keys.delete(key);if(on)this.engine.keyDown?.(key)}
  pressed(...keys){return keys.some(k=>this.keys.has(k))}
  handlePointer(e){const r=this.canvas.getBoundingClientRect();this.pointer.x=(e.clientX-r.left)*this.canvas.width/r.width;this.pointer.y=(e.clientY-r.top)*this.canvas.height/r.height;this.pointer.down=e.type==='pointerdown'||this.pointer.down;this.engine.pointer?.(this.pointer,e.type)}
  loop(t){if(!this.running)return;const dt=Math.min(.04,(t-this.last)/1000||0);this.last=t;if(!this.paused&&!this.completed){this.elapsed+=dt;try{this.engine.update(dt)}catch(err){console.error(err);this.showError(err);return}}try{this.engine.draw(this.ctx)}catch(err){console.error(err);this.showError(err);return}requestAnimationFrame(x=>this.loop(x))}
  togglePause(){if(this.completed)return;this.paused=!this.paused;const o=qs('#gameOverlay');if(this.paused){o.innerHTML=`<div class="overlay-card"><h2>Game Paused</h2><p>${escapeHtml(this.game.name)}</p><button id="resumeBtn" class="primary">Resume</button><button id="restartBtn">Restart Level</button><button id="quitBtn">Return to Launcher</button></div>`;o.classList.remove('hidden');qs('#resumeBtn').onclick=()=>this.togglePause();qs('#restartBtn').onclick=()=>{const g=this.game,l=this.level;this.stop();session=new GameSession(g,l);session.start()};qs('#quitBtn').onclick=exitGame}else o.classList.add('hidden')}
  showResult(win,score){const o=qs('#gameOverlay');const next=this.level<this.game.levels;const title=win?'Level Complete!':'Try Again';o.innerHTML=`<div class="overlay-card"><h2>${title}</h2><p>Score: ${Math.round(score)}</p>${win?`<p>AG Coins earned: ${this.reward}</p>`:''}<button id="resultMain" class="primary">${win&&next?'Next Level':'Play Again'}</button><button id="resultLauncher">Return to Launcher</button></div>`;o.classList.remove('hidden');qs('#resultMain').onclick=()=>{const g=this.game,l=win&&next?this.level+1:this.level;this.stop();session=new GameSession(g,l);qs('#gameLevelText').textContent=`Level ${l} of ${g.levels}`;session.start()};qs('#resultLauncher').onclick=exitGame}
  showError(err){this.running=false;const o=qs('#gameOverlay');o.innerHTML=`<div class="overlay-card"><h2>Game Error</h2><p>${escapeHtml(err.message||String(err))}</p><button id="errorBack">Return to Launcher</button></div>`;o.classList.remove('hidden');qs('#errorBack').onclick=exitGame}
  createEngine(){switch(this.game.engine){case'drawing':return drawingEngine(this);case'merge':return mergeEngine(this);case'memory':return memoryEngine(this);case'quiz':return quizEngine(this);case'clicker':return clickerEngine(this);case'runner':return runnerEngine(this);case'shooter':return shooterEngine(this);case'sports':return sportsEngine(this);case'board':return boardEngine(this);case'puzzle':return puzzleEngine(this);case'arena':return arenaEngine(this);case'collect':return collectEngine(this);case'tap':return tapEngine(this);default:return dodgeEngine(this)}}
}

function clearCanvas(ctx,color='#071020'){ctx.fillStyle=color;ctx.fillRect(0,0,900,540)}
function text(ctx,s,x,y,size=28,align='center',color='#fff'){ctx.fillStyle=color;ctx.font=`800 ${size}px Segoe UI, sans-serif`;ctx.textAlign=align;ctx.fillText(s,x,y)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function rand(a,b){return a+Math.random()*(b-a)}

function dodgeEngine(s){const st={p:{x:420,y:470,w:55,h:42},haz:[],spawn:0,score:0,target:12+s.level*.7};return{update(dt){const sp=330;if(s.pressed('ArrowLeft','KeyA'))st.p.x-=sp*dt;if(s.pressed('ArrowRight','KeyD'))st.p.x+=sp*dt;st.p.x=clamp(st.p.x,0,845);st.spawn-=dt;if(st.spawn<=0){st.spawn=Math.max(.22,.65-s.level*.015);st.haz.push({x:rand(0,850),y:-40,w:rand(28,75),h:35,v:rand(170,280)+s.level*8})}for(const h of st.haz)h.y+=h.v*dt;st.haz=st.haz.filter(h=>h.y<590);if(st.haz.some(h=>hit(st.p,h)))failLevel(st.score);st.score+=dt*10;if(s.elapsed>=st.target)completeLevel(st.score)},draw(c){clearCanvas(c,'#07142b');for(let i=0;i<40;i++){c.fillStyle='#ffffff44';c.fillRect((i*97+s.elapsed*12)%900,(i*53)%520,2,2)}c.fillStyle='#39d8ff';c.fillRect(st.p.x,st.p.y,st.p.w,st.p.h);c.fillStyle='#ff5f76';st.haz.forEach(h=>c.fillRect(h.x,h.y,h.w,h.h));text(c,`SURVIVE ${Math.max(0,st.target-s.elapsed).toFixed(1)}s`,450,38,24);text(c,`Score ${Math.round(st.score)}`,20,38,18,'left','#ffd166')}}}
function tapEngine(s){const st={x:450,y:270,r:45,hits:0,target:10+Math.floor(s.level/2),time:20};function move(){st.x=rand(70,830);st.y=rand(85,455);st.r=rand(28,50)}return{pointer(p,type){if(type==='pointerdown'&&Math.hypot(p.x-st.x,p.y-st.y)<=st.r){st.hits++;move();if(st.hits>=st.target)completeLevel(st.hits*100+st.time*10)}},update(dt){st.time-=dt;if(st.time<=0)failLevel(st.hits*100)},draw(c){clearCanvas(c,'#16113b');c.beginPath();c.arc(st.x,st.y,st.r,0,Math.PI*2);c.fillStyle='#ffcf55';c.fill();c.strokeStyle='#fff';c.lineWidth=5;c.stroke();text(c,`${st.hits}/${st.target}`,450,45,26);text(c,`${Math.max(0,st.time).toFixed(1)}s`,450,510,20)}}}
function collectEngine(s){const st={p:{x:430,y:260,w:38,h:38},orbs:[],enemies:[],score:0,target:5+Math.floor(s.level/2)};for(let i=0;i<st.target;i++)st.orbs.push({x:rand(30,850),y:rand(70,490),r:12});for(let i=0;i<2+s.level/5;i++)st.enemies.push({x:rand(50,850),y:rand(80,480),w:35,h:35,vx:rand(-100,100),vy:rand(-100,100)});return{update(dt){const v=240;if(s.pressed('ArrowLeft','KeyA'))st.p.x-=v*dt;if(s.pressed('ArrowRight','KeyD'))st.p.x+=v*dt;if(s.pressed('ArrowUp','KeyW'))st.p.y-=v*dt;if(s.pressed('ArrowDown','KeyS'))st.p.y+=v*dt;st.p.x=clamp(st.p.x,0,862);st.p.y=clamp(st.p.y,55,502);for(const e of st.enemies){e.x+=e.vx*dt;e.y+=e.vy*dt;if(e.x<0||e.x>865)e.vx*=-1;if(e.y<55||e.y>505)e.vy*=-1;if(hit(st.p,e))failLevel(st.score*100)}st.orbs=st.orbs.filter(o=>{if(Math.hypot(st.p.x+19-o.x,st.p.y+19-o.y)<31){st.score++;return false}return true});if(!st.orbs.length)completeLevel(st.score*200+Math.max(0,60-s.elapsed)*10)},draw(c){clearCanvas(c,'#072b29');c.fillStyle='#ffdd61';st.orbs.forEach(o=>{c.beginPath();c.arc(o.x,o.y,o.r,0,7);c.fill()});c.fillStyle='#ff5f76';st.enemies.forEach(e=>c.fillRect(e.x,e.y,e.w,e.h));c.fillStyle='#53e6ff';c.fillRect(st.p.x,st.p.y,st.p.w,st.p.h);text(c,`COLLECT ${st.score}/${st.target}`,450,38,24)}}}
function runnerEngine(s){const st={p:{x:120,y:430,w:42,h:55,vy:0},obs:[],spawn:1,dist:0,target:650+s.level*65};return{keyDown(k){if(['Space','ArrowUp','KeyW'].includes(k)&&st.p.y>=429)st.p.vy=-520},update(dt){st.p.vy+=1100*dt;st.p.y+=st.p.vy*dt;if(st.p.y>430){st.p.y=430;st.p.vy=0}st.spawn-=dt;if(st.spawn<=0){st.spawn=rand(.8,1.45)-Math.min(.35,s.level*.01);st.obs.push({x:930,y:445,w:rand(25,55),h:rand(35,70),v:270+s.level*8})}for(const o of st.obs)o.x-=o.v*dt;st.obs=st.obs.filter(o=>o.x>-70);if(st.obs.some(o=>hit(st.p,o)))failLevel(st.dist);st.dist+=220*dt;if(st.dist>=st.target)completeLevel(st.dist)},draw(c){clearCanvas(c,'#171c4a');c.fillStyle='#24305f';c.fillRect(0,485,900,55);for(let i=0;i<12;i++){c.fillStyle='#fff3';c.fillRect(((i*110)-st.dist*.3)%1000,120+(i%4)*55,3,3)}c.fillStyle='#4ce2ff';c.fillRect(st.p.x,st.p.y,st.p.w,st.p.h);c.fillStyle='#ff784f';st.obs.forEach(o=>c.fillRect(o.x,o.y,o.w,o.h));text(c,`${Math.round(st.dist)} / ${Math.round(st.target)} m`,450,38,24)}}}
function shooterEngine(s){const st={p:{x:425,y:480,w:50,h:35},shots:[],enemies:[],spawn:0,score:0,target:8+Math.floor(s.level*.7),cool:0};function fire(){if(st.cool>0)return;st.cool=.22;st.shots.push({x:st.p.x+23,y:st.p.y,v:-520})}return{keyDown(k){if(['Space','Enter'].includes(k))fire()},pointer(p,type){if(type==='pointerdown'){st.p.x=clamp(p.x-25,0,850);fire()}},update(dt){if(s.pressed('ArrowLeft','KeyA'))st.p.x-=300*dt;if(s.pressed('ArrowRight','KeyD'))st.p.x+=300*dt;if(s.pressed('Space'))fire();st.p.x=clamp(st.p.x,0,850);st.cool-=dt;st.spawn-=dt;if(st.spawn<=0){st.spawn=Math.max(.35,1-s.level*.025);st.enemies.push({x:rand(20,830),y:60,w:48,h:34,v:rand(45,95)+s.level*3})}st.shots.forEach(b=>b.y+=b.v*dt);st.enemies.forEach(e=>e.y+=e.v*dt);for(const b of st.shots)for(const e of st.enemies)if(hit({x:b.x,y:b.y,w:5,h:14},e)){b.dead=e.dead=true;st.score++}st.shots=st.shots.filter(b=>!b.dead&&b.y>-20);st.enemies=st.enemies.filter(e=>!e.dead&&e.y<560);if(st.enemies.some(e=>e.y>470))failLevel(st.score*100);if(st.score>=st.target)completeLevel(st.score*150)},draw(c){clearCanvas(c,'#020819');for(let i=0;i<70;i++){c.fillStyle=i%8?'#fff5':'#6ef';c.fillRect((i*73)%900,(i*41)%500,2,2)}c.fillStyle='#55dcff';c.fillRect(st.p.x,st.p.y,st.p.w,st.p.h);c.fillStyle='#ffe26a';st.shots.forEach(b=>c.fillRect(b.x,b.y,5,14));c.fillStyle='#ff5274';st.enemies.forEach(e=>c.fillRect(e.x,e.y,e.w,e.h));text(c,`ENEMIES ${st.score}/${st.target}`,450,38,24)}}}
function sportsEngine(s){const st={p:{x:20,y:215,w:22,h:110},ai:{x:858,y:215,w:22,h:110},ball:{x:450,y:270,r:14,vx:280,vy:150},score:0,opp:0,target:3};function reset(dir=1){Object.assign(st.ball,{x:450,y:270,vx:(260+s.level*6)*dir,vy:rand(-180,180)})}return{update(dt){const v=300;if(s.pressed('ArrowUp','KeyW'))st.p.y-=v*dt;if(s.pressed('ArrowDown','KeyS'))st.p.y+=v*dt;st.p.y=clamp(st.p.y,50,380);st.ai.y+=clamp(st.ball.y-(st.ai.y+55),-210*dt,210*dt);st.ai.y=clamp(st.ai.y,50,380);st.ball.x+=st.ball.vx*dt;st.ball.y+=st.ball.vy*dt;if(st.ball.y<55||st.ball.y>525)st.ball.vy*=-1;if(hit({x:st.ball.x-14,y:st.ball.y-14,w:28,h:28},st.p)&&st.ball.vx<0)st.ball.vx=Math.abs(st.ball.vx)*1.04;if(hit({x:st.ball.x-14,y:st.ball.y-14,w:28,h:28},st.ai)&&st.ball.vx>0)st.ball.vx=-Math.abs(st.ball.vx)*1.04;if(st.ball.x<0){st.opp++;reset(1)}if(st.ball.x>900){st.score++;reset(-1)}if(st.score>=st.target)completeLevel(st.score*500-st.opp*100);if(st.opp>=st.target)failLevel(st.score*300)},draw(c){clearCanvas(c,'#083b42');c.strokeStyle='#ffffff55';c.lineWidth=4;c.setLineDash([14,14]);c.beginPath();c.moveTo(450,50);c.lineTo(450,540);c.stroke();c.setLineDash([]);c.fillStyle='#4be4ff';c.fillRect(st.p.x,st.p.y,st.p.w,st.p.h);c.fillStyle='#ff6a7d';c.fillRect(st.ai.x,st.ai.y,st.ai.w,st.ai.h);c.fillStyle='#fff';c.beginPath();c.arc(st.ball.x,st.ball.y,st.ball.r,0,7);c.fill();text(c,`${st.score}  :  ${st.opp}`,450,40,30)}}}
function boardEngine(s){const title=s.game.name.toLowerCase();const size=title.includes('gomoku')||title.includes('five')||title.includes('pente')?10:8;const st={board:Array.from({length:size},()=>Array(size).fill(0)),turn:1,moves:0,target:title.includes('five')||title.includes('gomoku')||title.includes('pente')?5:4};function winner(r,c,p){for(const[dr,dc]of[[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(const z of[-1,1]){let rr=r+dr*z,cc=c+dc*z;while(rr>=0&&rr<size&&cc>=0&&cc<size&&st.board[rr][cc]===p){n++;rr+=dr*z;cc+=dc*z}}if(n>=st.target)return true}return false}function ai(){const empty=[];for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!st.board[r][c])empty.push([r,c]);if(!empty.length)return;let pick=empty[Math.floor(Math.random()*empty.length)];for(const pos of empty){st.board[pos[0]][pos[1]]=2;if(winner(...pos,2)){pick=pos;st.board[pos[0]][pos[1]]=0;break}st.board[pos[0]][pos[1]]=0}st.board[pick[0]][pick[1]]=2;st.moves++;if(winner(...pick,2))failLevel(st.moves*20)}function play(r,c){if(st.board[r][c]||s.completed)return;st.board[r][c]=1;st.moves++;if(winner(r,c,1))return completeLevel(1200-st.moves*20);setTimeout(()=>{if(!s.completed)ai()},180)}return{pointer(p,type){if(type!=='pointerdown')return;const cell=Math.min(54,430/size),ox=(900-cell*size)/2,oy=70;const c=Math.floor((p.x-ox)/cell),r=Math.floor((p.y-oy)/cell);if(r>=0&&r<size&&c>=0&&c<size)play(r,c)},update(){},draw(c){clearCanvas(c,'#17122f');const cell=Math.min(54,430/size),ox=(900-cell*size)/2,oy=70;c.strokeStyle='#91b8ff';for(let i=0;i<=size;i++){c.beginPath();c.moveTo(ox,oy+i*cell);c.lineTo(ox+size*cell,oy+i*cell);c.stroke();c.beginPath();c.moveTo(ox+i*cell,oy);c.lineTo(ox+i*cell,oy+size*cell);c.stroke()}for(let r=0;r<size;r++)for(let col=0;col<size;col++)if(st.board[r][col]){c.beginPath();c.arc(ox+(col+.5)*cell,oy+(r+.5)*cell,cell*.34,0,7);c.fillStyle=st.board[r][col]===1?'#42dcff':'#ff5d7a';c.fill()}text(c,`${s.game.name} • place ${st.target} in a row`,450,36,21)}}}
function puzzleEngine(s){const n=5,st={g:Array.from({length:n},()=>Array(n).fill(false)),moves:0};for(let k=0;k<8+s.level;k++){const r=Math.floor(Math.random()*n),c=Math.floor(Math.random()*n);toggle(r,c)}function toggle(r,c){for(const[dr,dc]of[[0,0],[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dr,cc=c+dc;if(rr>=0&&rr<n&&cc>=0&&cc<n)st.g[rr][cc]=!st.g[rr][cc]}}return{pointer(p,type){if(type!=='pointerdown')return;const cell=78,ox=255,oy=70,c=Math.floor((p.x-ox)/cell),r=Math.floor((p.y-oy)/cell);if(r>=0&&r<n&&c>=0&&c<n){toggle(r,c);st.moves++;if(st.g.every(row=>row.every(v=>!v)))completeLevel(1500-st.moves*25)}},update(){},draw(c){clearCanvas(c,'#0b2a40');const cell=78,ox=255,oy=70;for(let r=0;r<n;r++)for(let col=0;col<n;col++){c.fillStyle=st.g[r][col]?'#ffe062':'#173c59';c.fillRect(ox+col*cell+4,oy+r*cell+4,cell-8,cell-8)}text(c,`Turn every light off • Moves ${st.moves}`,450,38,23)}}}
function arenaEngine(s){const st={p1:{x:140,y:240,w:42,h:42,score:0},p2:{x:720,y:240,w:42,h:42,score:0},orb:{x:450,y:270,r:18},time:35};function resetOrb(){st.orb.x=rand(180,720);st.orb.y=rand(100,440)}return{update(dt){const v=250;if(s.pressed('ArrowLeft'))st.p1.x-=v*dt;if(s.pressed('ArrowRight'))st.p1.x+=v*dt;if(s.pressed('ArrowUp'))st.p1.y-=v*dt;if(s.pressed('ArrowDown'))st.p1.y+=v*dt;if(s.pressed('KeyA'))st.p2.x-=v*dt;if(s.pressed('KeyD'))st.p2.x+=v*dt;if(s.pressed('KeyW'))st.p2.y-=v*dt;if(s.pressed('KeyS'))st.p2.y+=v*dt;for(const p of[st.p1,st.p2]){p.x=clamp(p.x,0,858);p.y=clamp(p.y,55,498);if(Math.hypot(p.x+21-st.orb.x,p.y+21-st.orb.y)<40){p.score++;resetOrb()}}st.time-=dt;if(st.time<=0){if(st.p1.score>=st.p2.score)completeLevel(st.p1.score*300);else failLevel(st.p1.score*200)}},draw(c){clearCanvas(c,'#29204c');c.fillStyle='#42ddff';c.fillRect(st.p1.x,st.p1.y,st.p1.w,st.p1.h);c.fillStyle='#ff5f86';c.fillRect(st.p2.x,st.p2.y,st.p2.w,st.p2.h);c.fillStyle='#ffd85d';c.beginPath();c.arc(st.orb.x,st.orb.y,st.orb.r,0,7);c.fill();text(c,`P1 ${st.p1.score}  •  P2 ${st.p2.score}  •  ${Math.ceil(st.time)}s`,450,38,24)}}}
function mergeEngine(s){const st={g:Array.from({length:4},()=>Array(4).fill(0)),score:0};add();add();function add(){const e=[];for(let r=0;r<4;r++)for(let c=0;c<4;c++)if(!st.g[r][c])e.push([r,c]);if(e.length){const[r,c]=e[Math.floor(Math.random()*e.length)];st.g[r][c]=Math.random()<.9?2:4}}function slide(line){const a=line.filter(Boolean);for(let i=0;i<a.length-1;i++)if(a[i]===a[i+1]){a[i]*=2;st.score+=a[i];a.splice(i+1,1)}while(a.length<4)a.push(0);return a}function move(dir){const old=JSON.stringify(st.g);if(dir==='Left')for(let r=0;r<4;r++)st.g[r]=slide(st.g[r]);if(dir==='Right')for(let r=0;r<4;r++)st.g[r]=slide([...st.g[r]].reverse()).reverse();if(dir==='Up'||dir==='Down')for(let c=0;c<4;c++){let col=st.g.map(r=>r[c]);if(dir==='Down')col.reverse();col=slide(col);if(dir==='Down')col.reverse();for(let r=0;r<4;r++)st.g[r][c]=col[r]}if(JSON.stringify(st.g)!==old)add();const max=Math.max(...st.g.flat());if(max>=Math.min(2048,64*2**Math.floor((s.level-1)/3)))completeLevel(st.score)}return{keyDown(k){const m={ArrowLeft:'Left',ArrowRight:'Right',ArrowUp:'Up',ArrowDown:'Down',KeyA:'Left',KeyD:'Right',KeyW:'Up',KeyS:'Down'}[k];if(m)move(m)},pointer(p,type){if(type==='pointerdown')this.start={x:p.x,y:p.y};else if(this.start&&type==='pointermove'&&Math.hypot(p.x-this.start.x,p.y-this.start.y)>70){const dx=p.x-this.start.x,dy=p.y-this.start.y;move(Math.abs(dx)>Math.abs(dy)?(dx>0?'Right':'Left'):(dy>0?'Down':'Up'));this.start=null}},update(){},draw(c){clearCanvas(c,'#32233f');const cell=102,ox=246,oy=65;for(let r=0;r<4;r++)for(let col=0;col<4;col++){const v=st.g[r][col];c.fillStyle=v?`hsl(${45+Math.log2(v)*24} 75% 55%)`:'#514064';c.fillRect(ox+col*cell+5,oy+r*cell+5,cell-10,cell-10);if(v)text(c,String(v),ox+(col+.5)*cell,oy+(r+.62)*cell,26)}text(c,`Score ${st.score}`,450,38,23)}}}
function memoryEngine(s){const pairs=8,vals=[...Array(pairs).keys(),...Array(pairs).keys()].sort(()=>Math.random()-.5),st={vals,open:[],matched:new Set(),moves:0};return{pointer(p,type){if(type!=='pointerdown'||st.open.length>=2)return;const cell=90,ox=270,oy=70,c=Math.floor((p.x-ox)/cell),r=Math.floor((p.y-oy)/cell),i=r*4+c;if(i<0||i>=16||st.matched.has(i)||st.open.includes(i))return;st.open.push(i);if(st.open.length===2){st.moves++;if(vals[st.open[0]]===vals[st.open[1]]){st.open.forEach(x=>st.matched.add(x));st.open=[];if(st.matched.size===16)completeLevel(1600-st.moves*30)}else setTimeout(()=>{st.open=[]},650)}},update(){},draw(c){clearCanvas(c,'#19274c');const cell=90,ox=270,oy=70;for(let i=0;i<16;i++){const r=Math.floor(i/4),col=i%4,show=st.open.includes(i)||st.matched.has(i);c.fillStyle=show?'#4bdcff':'#354773';c.fillRect(ox+col*cell+5,oy+r*cell+5,cell-10,cell-10);if(show)text(c,['★','◆','●','▲','♥','☀','☂','♫'][vals[i]],ox+(col+.5)*cell,oy+(r+.65)*cell,34)}text(c,`Pairs ${st.matched.size/2}/${pairs} • Moves ${st.moves}`,450,38,23)}}}
function quizEngine(s){const questions=[['What is 7 × 8?',['54','56','64','48'],1],['Which planet is known as the Red Planet?',['Venus','Mars','Jupiter','Mercury'],1],['Which word is a noun?',['quickly','blue','river','jump'],2],['What is 100 ÷ 4?',['20','25','30','40'],1],['Which shape has three sides?',['Square','Circle','Triangle','Hexagon'],2]],st={i:0,score:0,buttons:[]};function next(){st.q=questions[(st.i+s.level-1)%questions.length];st.buttons=st.q[1].map((_,i)=>({x:170+(i%2)*290,y:280+Math.floor(i/2)*85,w:260,h:62,i}))}next();return{pointer(p,type){if(type!=='pointerdown')return;const b=st.buttons.find(x=>p.x>=x.x&&p.x<=x.x+x.w&&p.y>=x.y&&p.y<=x.y+x.h);if(!b)return;if(b.i===st.q[2])st.score++;st.i++;if(st.i>=5){if(st.score>=3)completeLevel(st.score*300);else failLevel(st.score*200)}else next()},update(){},draw(c){clearCanvas(c,'#11254b');text(c,`Question ${st.i+1}/5`,450,45,22);text(c,st.q[0],450,170,30);st.buttons.forEach(b=>{c.fillStyle='#294c83';c.fillRect(b.x,b.y,b.w,b.h);text(c,st.q[1][b.i],b.x+b.w/2,b.y+40,20)})}}}
function clickerEngine(s){const st={cash:0,rate:1,auto:0,target:80+s.level*35};function click(){st.cash+=st.rate}return{pointer(p,type){if(type!=='pointerdown')return;if(p.y>130&&p.y<360){click()}else if(p.y>400&&p.x<430&&st.cash>=20){st.cash-=20;st.rate++}else if(p.y>400&&p.x>470&&st.cash>=60){st.cash-=60;st.auto++}},keyDown(k){if(['Space','Enter'].includes(k))click()},update(dt){st.cash+=st.auto*dt;if(st.cash>=st.target)completeLevel(st.cash*10)},draw(c){clearCanvas(c,'#2b1939');c.fillStyle='#ffca55';c.beginPath();c.arc(450,245,105,0,7);c.fill();text(c,'TAP',450,260,38,'center','#5c3310');c.fillStyle='#284a77';c.fillRect(80,400,350,80);c.fillRect(470,400,350,80);text(c,`Upgrade Tap (20) • ${st.rate}`,255,450,18);text(c,`Auto (60) • ${st.auto}`,645,450,18);text(c,`${Math.floor(st.cash)} / ${st.target}`,450,50,28)}}}
function drawingEngine(s){const st={lines:[],last:null,color:'#42dcff'};return{pointer(p,type){if(type==='pointerdown'){st.last={x:p.x,y:p.y}}else if(type==='pointermove'&&p.down&&st.last){st.lines.push({a:st.last,b:{x:p.x,y:p.y},color:st.color});st.last={x:p.x,y:p.y};if(st.lines.length>=120)completeLevel(st.lines.length)}},pointerUp(){st.last=null},keyDown(k){if(k==='Enter'){st.lines=[]}if(k==='Space')st.color=['#42dcff','#ff5e7d','#ffd45d','#5ce58c','#bd75ff'][Math.floor(Math.random()*5)]},update(){},draw(c){clearCanvas(c,'#f5f8ff');c.lineCap='round';c.lineWidth=8;for(const l of st.lines){c.strokeStyle=l.color;c.beginPath();c.moveTo(l.a.x,l.a.y);c.lineTo(l.b.x,l.b.y);c.stroke()}text(c,'Draw with touch • A changes color • B clears',450,35,19,'center','#1a2c4b')}}}

async function syncGameCatalog(){
  try{
    const response=await fetch('./games.json?v=7.1',{cache:'no-store'});if(!response.ok)return;
    const fresh=await response.json();if(!Array.isArray(fresh)||!fresh.length)return;
    const current=JSON.stringify(ARCADE_GAMES.map(g=>[g.id,g.name,g.engine,g.controls]));
    const next=JSON.stringify(fresh.map(g=>[g.id,g.name,g.engine,g.controls]));
    if(current!==next){ARCADE_GAMES.splice(0,ARCADE_GAMES.length,...fresh);if(activeAccountId){const selected=qs('#categorySelect').value;qs('#categorySelect').innerHTML='';renderLauncher();if([...qs('#categorySelect').options].some(o=>o.value===selected))qs('#categorySelect').value=selected;renderGames()}toast('Game names and catalog were refreshed')}
  }catch(error){console.warn('Catalog refresh skipped',error)}
}
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{
  try{const registration=await navigator.serviceWorker.register('./service-worker.js?v=7.1');await registration.update();let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()})}catch(error){console.warn(error)}
  syncGameCatalog();
});
window.addEventListener('error',e=>{console.error(e.error||e.message);try{localStorage.setItem('asArcadeLastError',JSON.stringify({time:new Date().toISOString(),message:e.message,stack:e.error?.stack||''}))}catch{}});
refreshAuth();if(db.active&&db.accounts.some(a=>a.id===db.active&&a.enabled)){activeAccountId=db.active;refreshHeader();renderLauncher();showView('launcher')}else showView('auth');
