'use strict';

/* 39 additional game engines. Each factory implements mechanics that match its title. */
window.EXTRA_GAME_FACTORIES={
  chesstactics:chessTacticsGame,wordsearch:wordSearchGame,crossword:crosswordGame,scramble:scrambleGame,
  mathsprint:mathSprintGame,typingrace:typingRaceGame,rhythm:rhythmGame,sequencer:sequencerGame,
  paintnumbers:paintNumbersGame,jigsaw:jigsawGame,sliding:slidingGame,pipes:pipesGame,laser:laserGame,
  tangram:tangramGame,nonogram:nonogramGame,mastermind:mastermindGame,codebreaker:codeBreakerGame,
  yahtzee:yahtzeeGame,solitaire:solitaireGame,war:warGame,gofish:goFishGame,dicerace:diceRaceGame,
  dotsboxes:dotsBoxesGame,mancala:mancalaGame,morris:morrisGame,gomoku:gomokuGame,hex:hexGame,
  dominoes:dominoesGame,volleyball:volleyballGame,airhockey:airHockeyGame,bowling:bowlingGame,
  fishing:fishingGame,cooking:cookingGame,farm:farmGame,petcare:petCareGame,citybuilder:cityBuilderGame,
  pinball:pinballGame,match3:match3Game,robotcode:robotCodeGame
};

function chessTacticsGame(s){
  const pieces=['R','B','Q','N'],piece=pieces[(s.level-1)%pieces.length],cell=58,ox=218,oy=58;
  const starts={R:[7,0],B:[7,1],Q:[7,3],N:[7,1]},start=starts[piece].slice();
  const targets={R:[1,0],B:[2,6],Q:[1,3],N:[5,2]},target=targets[piece].slice();let selected=false,done=false;
  function legal(r,c){const dr=r-start[0],dc=c-start[1];if(piece==='R')return (dr===0||dc===0)&&!(dr===0&&dc===0);if(piece==='B')return Math.abs(dr)===Math.abs(dc)&&dr!==0;if(piece==='Q')return (dr===0||dc===0||Math.abs(dr)===Math.abs(dc))&&!(dr===0&&dc===0);return (Math.abs(dr)===2&&Math.abs(dc)===1)||(Math.abs(dr)===1&&Math.abs(dc)===2)}
  function play(r,c){if(done)return;if(r===start[0]&&c===start[1]){selected=true;return}if(!selected||!legal(r,c))return failLevel(0);done=true;(r===target[0]&&c===target[1]?completeLevel:failLevel)(1800)}
  return{pointer(p,t){if(t==='pointerdown')play(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell))},draw(c){bg(c,'#172033');for(let r=0;r<8;r++)for(let col=0;col<8;col++)rect(c,ox+col*cell,oy+r*cell,cell,cell,(r+col)%2?'#6b7f9c':'#d8e0ea');txt(c,'♚',ox+(target[1]+.5)*cell,oy+(target[0]+.72)*cell,44,'#141414');txt(c,({R:'♖',B:'♗',Q:'♕',N:'♘'})[piece],ox+(start[1]+.5)*cell,oy+(start[0]+.72)*cell,44,selected?'#27dfff':'#fff');txt(c,`Capture the king with the ${piece==='R'?'rook':piece==='B'?'bishop':piece==='Q'?'queen':'knight'} in one move`,450,36,20)}}
}

function wordSearchGame(s){
  const words=['STAR','GAME','CODE','PLAY'],N=10,grid=Array.from({length:N},()=>Array.from({length:N},()=>String.fromCharCode(65+Math.floor(Math.random()*26))));
  const placements=[[1,1,0,1],[3,1,1,0],[7,1,0,1],[1,8,1,0]];words.forEach((w,i)=>{const[r,c,dr,dc]=placements[i];[...w].forEach((ch,k)=>grid[r+dr*k][c+dc*k]=ch)});let start=null,found=new Set();const cell=42,ox=240,oy=65;
  function finish(p){if(!start)return;const a=[Math.floor((start.y-oy)/cell),Math.floor((start.x-ox)/cell)],b=[Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell)],dr=Math.sign(b[0]-a[0]),dc=Math.sign(b[1]-a[1]);if(!(dr===0||dc===0||Math.abs(b[0]-a[0])===Math.abs(b[1]-a[1]))){start=null;return}let str='',r=a[0],c=a[1];while(r>=0&&r<N&&c>=0&&c<N){str+=grid[r][c];if(r===b[0]&&c===b[1])break;r+=dr;c+=dc}const idx=words.findIndex(w=>w===str||w===[...str].reverse().join(''));if(idx>=0)found.add(idx);start=null;if(found.size===words.length)completeLevel(2200)}
  return{pointer(p,t){if(t==='pointerdown')start={...p};if(t==='pointerup')finish(p)},draw(c){bg(c,'#102c40');for(let r=0;r<N;r++)for(let col=0;col<N;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,'#edf7ff','#47728a');txt(c,grid[r][col],ox+(col+.5)*cell,oy+(r+.68)*cell,20,'#153245')}txt(c,words.map((w,i)=>found.has(i)?`✓ ${w}`:w).join('   '),450,36,20)}}
}

function crosswordGame(s){
  const solution=['CAT','ARE','TEN'],grid=Array.from({length:3},()=>Array(3).fill('')),cell=110,ox=285,oy=90;let selected=[0,0];
  const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  function put(ch){grid[selected[0]][selected[1]]=ch;let i=selected[0]*3+selected[1]+1;selected=[Math.floor((i%9)/3),i%3];if(grid.every((r,i)=>r.join('')===solution[i]))completeLevel(2500)}
  return{keyDown(k){if(/^Key[A-Z]$/.test(k))put(k.slice(3));if(k==='Backspace'){grid[selected[0]][selected[1]]=''}},pointer(p,t){if(t!=='pointerdown')return;if(p.y<420){const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(grid[r]?.[c]!==undefined)selected=[r,c]}else{const i=Math.floor((p.x-90)/28);if(i>=0&&i<26)put(letters[i])}},draw(c){bg(c,'#f2ead8');for(let r=0;r<3;r++)for(let col=0;col<3;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,selected[0]===r&&selected[1]===col?'#d9efff':'#fff','#1d3557');txt(c,grid[r][col],ox+(col+.5)*cell,oy+(r+.68)*cell,42,'#13243c')}txt(c,'Across: 1 Feline • 2 Exist • 3 Number after nine',450,45,18,'#332c26');txt(c,'Down: 1 Feline • 2 Exist • 3 Number after nine',450,70,18,'#332c26');for(let i=0;i<26;i++){const x=90+i*28;rect(c,x,455,25,36,'#fff','#536');txt(c,letters[i],x+12,480,15,'#213')}}}
}

function scrambleGame(s){
  const bank=[['PLANET','World in space'],['PUZZLE','Something to solve'],['ROCKET','Space vehicle'],['JUNGLE','Dense tropical forest'],['ARCADE','Place full of games']],q=bank[(s.level-1)%bank.length],letters=[...q[0]].sort(()=>Math.random()-.5),used=Array(letters.length).fill(false);let answer='';
  function choose(i){if(used[i])return;used[i]=true;answer+=letters[i];if(answer.length===q[0].length)(answer===q[0]?completeLevel:failLevel)(1800)}function undo(){for(let i=used.length-1;i>=0;i--)if(used[i]){used[i]=false;answer=answer.slice(0,-1);break}}
  return{keyDown(k){if(k==='Backspace'||k==='Enter')undo()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>330&&p.y<420){const i=Math.floor((p.x-180)/90);if(i>=0&&i<letters.length)choose(i)}else if(p.y>440)undo()},draw(c){bg(c,'#2b1846');txt(c,q[1],450,120,28);txt(c,answer.padEnd(q[0].length,'_').split('').join(' '),450,230,40,'#ffe066');letters.forEach((ch,i)=>{rect(c,180+i*90,340,70,70,used[i]?'#4b3d5f':'#4ad7e8');txt(c,ch,215+i*90,387,30,used[i]?'#8d829b':'#10243a')});rect(c,340,455,220,48,'#9a4cc0');txt(c,'UNDO',450,488,20)}}
}

function mathSprintGame(s){
  let score=0,time=40,q=null,buttons=[];const target=7+Math.min(7,Math.floor(s.level/6));
  function next(){const a=1+Math.floor(Math.random()*12),b=1+Math.floor(Math.random()*12),ops=['+','−','×'],op=ops[Math.floor(Math.random()*ops.length)],ans=op==='+'?a+b:op==='−'?a-b:a*b;let vals=[ans,ans+1,ans-1,ans+(Math.random()<.5?2:-2)].sort(()=>Math.random()-.5);q={text:`${a} ${op} ${b} = ?`,ans};buttons=vals.map((v,i)=>({x:150+(i%2)*310,y:270+Math.floor(i/2)*90,w:280,h:65,v}))}next();
  function pick(v){if(v===q.ans){score++;time+=1.5;if(score>=target)return completeLevel(score*250)}else time-=2;next()}
  return{pointer(p,t){if(t==='pointerdown'){const b=buttons.find(x=>buttonHit(p,x));if(b)pick(b.v)}},keyDown(k){const i={Digit1:0,Digit2:1,Digit3:2,Digit4:3}[k];if(i!==undefined)pick(buttons[i].v)},update(dt){time-=dt;if(time<=0)failLevel(score*100)},draw(c){bg(c,'#102b55');txt(c,q.text,450,180,46);buttons.forEach((b,i)=>{rect(c,b.x,b.y,b.w,b.h,'#28528b','#6bdcff');txt(c,`${i+1}. ${b.v}`,b.x+b.w/2,b.y+44,24)});txt(c,`Correct ${score}/${target} • ${Math.ceil(time)}s`,450,42,22)}}
}

function typingRaceGame(s){
  const phrases=['FAST TYPING','ARCADE HERO','CODE THE GAME','TOUCH AND PLAY','LEVEL COMPLETE'],target=phrases[(s.level-1)%phrases.length],keys='ABCDEFGHIJKLMNOPQRSTUVWXYZ ',buttons=[];let typed='',rival=0;
  for(let i=0;i<keys.length;i++)buttons.push({x:55+(i%9)*88,y:335+Math.floor(i/9)*55,w:78,h:45,ch:keys[i]});
  function input(ch){if(ch==='BACK'){typed=typed.slice(0,-1);return}const expect=target[typed.length];if(ch===expect)typed+=ch;else rival+=.3;if(typed===target)completeLevel(2400-rival*30)}
  return{keyDown(k){if(/^Key[A-Z]$/.test(k))input(k.slice(3));else if(k==='Space')input(' ');else if(k==='Backspace')input('BACK')},pointer(p,t){if(t!=='pointerdown')return;const b=buttons.find(x=>buttonHit(p,x));if(b)input(b.ch)},update(dt){rival+=dt*gentleScale(s,.62,.9);if(rival>=target.length)failLevel(typed.length*100)},draw(c){bg(c,'#1a2447');txt(c,target,450,115,38,'#dbe8ff');txt(c,typed+'▌',450,190,34,'#56e3a6');rect(c,100,245,700,22,'#26385d');rect(c,100,245,700*typed.length/target.length,22,'#56e3a6');rect(c,100,280,700,16,'#26385d');rect(c,100,280,700*Math.min(1,rival/target.length),16,'#ff6b7d');buttons.forEach(b=>{rect(c,b.x,b.y,b.w,b.h,'#334d7d');txt(c,b.ch===' '?'SPACE':b.ch,b.x+b.w/2,b.y+31,b.ch===' '?13:18)})}}
}

function rhythmGame(s){
  const lanes=[270,390,510,630],keys={KeyD:0,KeyF:1,KeyJ:2,KeyK:3,ArrowLeft:0,ArrowDown:1,ArrowUp:2,ArrowRight:3};let notes=[],spawn=.8,created=0,hits=0,miss=0,total=12+Math.min(14,Math.floor(s.level*.4)),flash=-1;
  function tap(i){flash=i;setTimeout(()=>flash=-1,80);let best=null,d=78;for(const n of notes){const dd=Math.abs(n.y-440);if(n.lane===i&&dd<d){best=n;d=dd}}if(best){notes.splice(notes.indexOf(best),1);hits++}else miss++}
  return{keyDown(k){if(keys[k]!==undefined)tap(keys[k])},pointer(p,t){if(t==='pointerdown')tap(clamp(Math.floor((p.x-210)/120),0,3))},update(dt){spawn-=dt;if(spawn<=0&&created<total){notes.push({lane:(created*3+s.level)%4,y:60});created++;spawn=gentleScale(s,.72,.58)}for(const n of notes)n.y+=gentleScale(s,225,275)*dt;for(const n of [...notes])if(n.y>500){notes.splice(notes.indexOf(n),1);miss++}if(created===total&&!notes.length)(hits>=Math.ceil(total*.62)?completeLevel:failLevel)(hits*180)},draw(c){bg(c,'#170f31');for(let i=0;i<4;i++){rect(c,lanes[i]-45,55,90,420,flash===i?'#503ea0':'#2a2450');rect(c,lanes[i]-45,430,90,18,'#65e8ff');txt(c,['D','F','J','K'][i],lanes[i],510,22)}for(const n of notes)circle(c,lanes[n.lane],n.y,24,['#ff5c7f','#5ce6ff','#ffe36a','#7cf08d'][n.lane]);txt(c,`Hits ${hits} • Misses ${miss}`,450,35,21)}}
}

function sequencerGame(s){
  const R=4,C=8,target=Array.from({length:R},(_,r)=>Array.from({length:C},(_,c)=>(c+r*2+s.level)%5===0)),g=Array.from({length:R},()=>Array(C).fill(false));let play=false,step=0,timer=0;
  function check(){if(g.every((r,i)=>r.every((v,j)=>v===target[i][j])))completeLevel(2300)}
  return{keyDown(k){if(k==='Space')play=!play;if(k==='Enter')check()},pointer(p,t){if(t!=='pointerdown')return;const cell=68,ox=178,oy=130,r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(g[r]?.[c]!==undefined){g[r][c]=!g[r][c];check()}},update(dt){if(play){timer+=dt;if(timer>.25){timer=0;step=(step+1)%C}}},draw(c){bg(c,'#11273b');const cell=68,ox=178,oy=130;for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,ox+col*cell+3,oy+r*cell+3,cell-6,cell-6,g[r][col]?'#4fd9b8':'#263f55',step===col?'#ffe06d':'');if(target[r][col])circle(c,ox+(col+.5)*cell,oy+(r+.5)*cell,7,'#ff8dd5')}txt(c,'Match the pink target dots • Space plays the loop',450,75,20)}}
}

function paintNumbersGame(s){
  const N=8,pattern=Array.from({length:N},(_,r)=>Array.from({length:N},(_,c)=>1+((r<4?0:2)+(c<4?0:1))%4)),filled=Array.from({length:N},()=>Array(N).fill(0)),colors=['','#ff6b7b','#52c8ff','#ffe067','#65dc8b'];let color=1;const cell=48,ox=258,oy=70;
  function done(){return filled.every((r,i)=>r.every((v,j)=>v===pattern[i][j]))}
  return{keyDown(k){if(k==='Space'||k==='Enter')color=color%4+1},pointer(p,t){if(t!=='pointerdown')return;if(p.y>470){color=clamp(Math.floor((p.x-270)/90)+1,1,4);return}const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(pattern[r]?.[c]===color){filled[r][c]=color;if(done())completeLevel(2500)}},draw(c){bg(c,'#f5f0e6');for(let r=0;r<N;r++)for(let col=0;col<N;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,filled[r][col]?colors[filled[r][col]]:'#fff','#9b9288');if(!filled[r][col])txt(c,pattern[r][col],ox+(col+.5)*cell,oy+(r+.68)*cell,18,'#6a625b')}for(let i=1;i<=4;i++){circle(c,270+(i-1)*90,495,25,colors[i],color===i?'#111':'');txt(c,i,270+(i-1)*90,502,16,'#111')}}}
}

function jigsawGame(s){
  const pieces=Array.from({length:9},(_,i)=>({id:i,x:60+(i%5)*125,y:420+Math.floor(i/5)*55,drag:false,dx:0,dy:0,placed:false}));let drag=null;const cell=120,ox=270,oy=70;
  return{pointer(p,t){if(t==='pointerdown'){for(const q of [...pieces].reverse())if(!q.placed&&p.x>=q.x&&p.x<=q.x+90&&p.y>=q.y&&p.y<=q.y+90){drag=q;q.dx=p.x-q.x;q.dy=p.y-q.y;break}}else if(t==='pointermove'&&drag){drag.x=p.x-drag.dx;drag.y=p.y-drag.dy}else if(t==='pointerup'&&drag){const tr=Math.floor(drag.id/3),tc=drag.id%3,tx=ox+tc*cell,ty=oy+tr*cell;if(Math.hypot(drag.x-tx,drag.y-ty)<75){drag.x=tx;drag.y=ty;drag.placed=true}drag=null;if(pieces.every(q=>q.placed))completeLevel(2500)}},draw(c){bg(c,'#203455');for(let r=0;r<3;r++)for(let col=0;col<3;col++)rect(c,ox+col*cell,oy+r*cell,90,90,'#15263f','#7ebee4');for(const q of pieces){rect(c,q.x,q.y,90,90,`hsl(${q.id*40} 72% 60%)`,'#fff');txt(c,q.id+1,q.x+45,q.y+57,26)}}}
}

function slidingGame(s){
  const N=4,g=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0];let blank=15,moves=0;for(let i=0;i<70+s.level;i++){const r=Math.floor(blank/N),c=blank%N,opts=[];for(const[dR,dC]of[[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dR,cc=c+dC;if(rr>=0&&rr<N&&cc>=0&&cc<N)opts.push(rr*N+cc)}const q=opts[Math.floor(Math.random()*opts.length)];[g[blank],g[q]]=[g[q],g[blank]];blank=q}const cell=105,ox=240,oy=70;
  function move(i){const r=Math.floor(i/N),c=i%N,br=Math.floor(blank/N),bc=blank%N;if(Math.abs(r-br)+Math.abs(c-bc)!==1)return;[g[i],g[blank]]=[g[blank],g[i]];blank=i;moves++;if(g.every((v,i)=>v===(i+1)%16))completeLevel(2400-moves*10)}
  return{pointer(p,t){if(t==='pointerdown')move(Math.floor((p.y-oy)/cell)*N+Math.floor((p.x-ox)/cell))},keyDown(k){const d=keyDirection(k);if(!d)return;const br=Math.floor(blank/N),bc=blank%N;move((br-d[1])*N+(bc-d[0]))},draw(c){bg(c,'#322544');for(let i=0;i<16;i++){const r=Math.floor(i/N),col=i%N;if(g[i]){rect(c,ox+col*cell+4,oy+r*cell+4,cell-8,cell-8,'#6e55a3');txt(c,g[i],ox+(col+.5)*cell,oy+(r+.65)*cell,30)}}txt(c,`Moves ${moves}`,450,38,21)}}
}

function pipesGame(s){
  const R=6,C=8,cell=58,ox=218,oy=90,tiles=Array.from({length:R},()=>Array(C).fill(null));
  for(let c=0;c<C-1;c++)tiles[2][c]={kind:'straight',target:0,rot:Math.floor(Math.random()*4)};
  tiles[2][C-1]={kind:'elbow',target:1,rot:Math.floor(Math.random()*4)}; // left to down
  for(let r=3;r<R;r++)tiles[r][C-1]={kind:'straight',target:1,rot:Math.floor(Math.random()*4)};
  function normalized(t){return t.kind==='straight'?t.rot%2:t.rot%4}function check(){return tiles.every(row=>row.every(t=>!t||normalized(t)===t.target))}
  function drawPipe(c,x,y,t){const r=normalized(t),cx=x+cell/2,cy=y+cell/2;c.strokeStyle='#5ce5ff';c.lineWidth=12;c.lineCap='round';c.beginPath();if(t.kind==='straight'){if(r===0){c.moveTo(x+4,cy);c.lineTo(x+cell-4,cy)}else{c.moveTo(cx,y+4);c.lineTo(cx,y+cell-4)}}else{const ends=[[[0,-1],[1,0]],[[-1,0],[0,1]],[[0,1],[-1,0]],[[1,0],[0,-1]]][r];c.moveTo(cx+ends[0][0]*(cell/2-4),cy+ends[0][1]*(cell/2-4));c.lineTo(cx,cy);c.lineTo(cx+ends[1][0]*(cell/2-4),cy+ends[1][1]*(cell/2-4))}c.stroke();c.lineCap='butt'}
  return{pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),col=Math.floor((p.x-ox)/cell),tile=tiles[r]?.[col];if(tile){tile.rot=(tile.rot+1)%4;if(check())completeLevel(2200)}},draw(c){bg(c,'#15313b');for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,'#244852','#102c34');if(tiles[r][col])drawPipe(c,ox+col*cell,oy+r*cell,tiles[r][col])}circle(c,ox-10,oy+2.5*cell,12,'#4bdcff');circle(c,ox+(C-.5)*cell,oy+R*cell+8,12,'#4ee58b');txt(c,'Rotate the route from the left source to the bottom drain',450,50,19)}}
}

function laserGame(s){
  const mirrors=[{r:1,c:2,slash:Math.random()<.5},{r:4,c:2,slash:Math.random()<.5},{r:0,c:4,slash:Math.random()<.5}],cell=70,ox=240,oy=70;let path=[],hitTarget=false;
  function trace(){path=[];let r=1,c=-1,dr=0,dc=1;for(let k=0;k<50;k++){c+=dc;r+=dr;path.push([r,c]);if(r===4&&c===6){hitTarget=true;return}if(r<0||r>=6||c<0||c>=7)break;const m=mirrors.find(x=>x.r===r&&x.c===c);if(m){if(m.slash){[dr,dc]=[-dc,-dr]}else [dr,dc]=[dc,dr]}}hitTarget=false}
  trace();return{pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell),m=mirrors.find(x=>x.r===r&&x.c===c);if(m){m.slash=!m.slash;trace();if(hitTarget)completeLevel(2500)}},draw(c){bg(c,'#0b1025');for(let r=0;r<6;r++)for(let col=0;col<7;col++)rect(c,ox+col*cell,oy+r*cell,cell,cell,'#151d38','#2c3f68');for(const m of mirrors)txt(c,m.slash?'/':'\\',ox+(m.c+.5)*cell,oy+(m.r+.72)*cell,48,'#dce8ff');c.strokeStyle='#ff4868';c.lineWidth=5;c.beginPath();path.forEach((q,i)=>{const x=ox+(q[1]+.5)*cell,y=oy+(q[0]+.5)*cell;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();circle(c,ox+6.5*cell,oy+4.5*cell,18,hitTarget?'#58e58a':'#ffcf4a');txt(c,'Rotate mirrors to hit the receiver',450,45,20)}}
}

function tangramGame(s){
  const targets=[{x:320,y:110,w:120,h:80},{x:470,y:110,w:80,h:120},{x:590,y:110,w:100,h:100},{x:340,y:260,w:100,h:100},{x:490,y:270,w:120,h:70},{x:640,y:260,w:70,h:120},{x:500,y:380,w:100,h:80}],pieces=targets.map((t,i)=>({x:35+(i%4)*125,y:400+Math.floor(i/4)*65,w:t.w*.65,h:t.h*.65,id:i,placed:false}));let drag=null;
  return{pointer(p,t){if(t==='pointerdown'){drag=[...pieces].reverse().find(q=>!q.placed&&buttonHit(p,q));if(drag){drag.dx=p.x-drag.x;drag.dy=p.y-drag.y}}else if(t==='pointermove'&&drag){drag.x=p.x-drag.dx;drag.y=p.y-drag.dy}else if(t==='pointerup'&&drag){const z=targets[drag.id];if(Math.hypot(drag.x-z.x,drag.y-z.y)<70){Object.assign(drag,{x:z.x,y:z.y,w:z.w,h:z.h,placed:true})}drag=null;if(pieces.every(q=>q.placed))completeLevel(2400)}},draw(c){bg(c,'#25203a');targets.forEach(t=>rect(c,t.x,t.y,t.w,t.h,'#ffffff12','#fff6'));pieces.forEach((q,i)=>rect(c,q.x,q.y,q.w,q.h,`hsl(${i*51} 75% 60%)`));txt(c,'Fit every colored shape into its matching outline',450,45,20)}}
}

function nonogramGame(s){
  const sol=[[0,1,1,1,0],[1,0,1,0,1],[1,1,1,1,1],[0,1,1,1,0],[0,0,1,0,0]],g=Array.from({length:5},()=>Array(5).fill(0));let mode=1;const cell=70,ox=310,oy=120;const clue=a=>{let o=[],n=0;for(const v of a){if(v)n++;else if(n){o.push(n);n=0}}if(n)o.push(n);return o.join(' ')||'0'};
  function check(){if(g.every((r,i)=>r.every((v,j)=>(v===1)===(sol[i][j]===1))))completeLevel(2400)}
  return{keyDown(k){if(k==='Space'||k==='Enter')mode=mode===1?2:1},pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(g[r]?.[c]!==undefined){g[r][c]=g[r][c]===mode?0:mode;check()}},draw(c){bg(c,'#e8edf2');for(let r=0;r<5;r++){txt(c,clue(sol[r]),ox-18,oy+(r+.65)*cell,18,'#24364b','right');for(let col=0;col<5;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,g[r][col]===1?'#293c55':'#fff','#6b7a8c');if(g[r][col]===2)txt(c,'×',ox+(col+.5)*cell,oy+(r+.68)*cell,30,'#bd5969')}}for(let col=0;col<5;col++)txt(c,clue(sol.map(r=>r[col])),ox+(col+.5)*cell,oy-18,18,'#24364b');txt(c,mode===1?'FILL mode':'X mode',450,55,20,'#24364b')}}
}

function mastermindGame(s){
  const colors=['#f05267','#48c8ff','#ffe061','#5ce18b','#b578ff','#ff9d4c'],code=Array.from({length:4},()=>Math.floor(Math.random()*6));let current=[0,0,0,0],slot=0,rows=[];
  function submit(){let exact=0,partial=0,usedC=[],usedG=[];for(let i=0;i<4;i++)if(current[i]===code[i]){exact++;usedC.push(i);usedG.push(i)}for(let i=0;i<4;i++)if(!usedG.includes(i)){const j=code.findIndex((v,k)=>v===current[i]&&!usedC.includes(k));if(j>=0){partial++;usedC.push(j)}}rows.push({guess:current.slice(),exact,partial});if(exact===4)return completeLevel(2600-rows.length*100);if(rows.length>=8)return failLevel(0);current=[0,0,0,0];slot=0}
  return{keyDown(k){if(k==='ArrowLeft')slot=(slot+3)%4;if(k==='ArrowRight')slot=(slot+1)%4;if(k==='ArrowUp')current[slot]=(current[slot]+1)%6;if(k==='Enter'||k==='Space')submit()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>450){const i=Math.floor((p.x-225)/75);if(i>=0&&i<6){current[slot]=i;slot=(slot+1)%4}}else if(p.y>370)submit()},draw(c){bg(c,'#17273b');rows.slice(-5).forEach((r,ri)=>{r.guess.forEach((v,i)=>circle(c,300+i*70,90+ri*55,20,colors[v]));txt(c,`● ${r.exact}  ○ ${r.partial}`,650,98+ri*55,18)});current.forEach((v,i)=>circle(c,300+i*70,380,24,colors[v],i===slot?'#fff':''));rect(c,620,350,150,55,'#4d76a2');txt(c,'SUBMIT',695,386,18);colors.forEach((v,i)=>circle(c,250+i*75,485,24,v));txt(c,'Black = exact • White = wrong position',450,45,18)}}
}

function codeBreakerGame(s){
  const code=[1+Math.floor(Math.random()*8),1+Math.floor(Math.random()*8),1+Math.floor(Math.random()*8)],guess=[1,1,1];let selected=0,attempts=[];
  function submit(){const exact=guess.filter((v,i)=>v===code[i]).length,sum=guess.reduce((a,b)=>a+b,0),even=guess.filter(v=>v%2===0).length;attempts.push({g:guess.slice(),exact,sum,even});if(exact===3)return completeLevel(2500-attempts.length*120);if(attempts.length>=7)failLevel(0)}
  return{keyDown(k){if(k==='ArrowLeft')selected=(selected+2)%3;if(k==='ArrowRight')selected=(selected+1)%3;if(k==='ArrowUp')guess[selected]=guess[selected]%9+1;if(k==='ArrowDown')guess[selected]=(guess[selected]+7)%9+1;if(k==='Space'||k==='Enter')submit()},pointer(p,t){if(t!=='pointerdown')return;if(p.y<300){selected=clamp(Math.floor((p.x-300)/100),0,2);guess[selected]=guess[selected]%9+1}else submit()},draw(c){bg(c,'#281d34');guess.forEach((v,i)=>{rect(c,300+i*100,120,80,100,i===selected?'#8a5cb5':'#49375d');txt(c,v,340+i*100,185,48)});rect(c,330,260,240,55,'#b45a7c');txt(c,'TEST CODE',450,297,20);attempts.slice(-4).forEach((a,i)=>txt(c,`${a.g.join('')} • exact ${a.exact} • sum ${a.sum} • evens ${a.even}`,450,365+i*36,18));txt(c,'Use the clues to deduce all three digits',450,50,20)}}
}

function yahtzeeGame(s){
  let dice=[1,1,1,1,1],held=[false,false,false,false,false],rolls=0,round=1,total=0;const target=55+Math.floor(s.level*2);
  function roll(){if(rolls>=3)return;for(let i=0;i<5;i++)if(!held[i])dice[i]=1+Math.floor(Math.random()*6);rolls++}function score(){const counts=Array(7).fill(0);dice.forEach(v=>counts[v]++);const sum=dice.reduce((a,b)=>a+b,0),best=Math.max(sum,Math.max(...counts)*10,counts.some(x=>x>=4)?40:0,counts.some(x=>x===5)?50:0);total+=best;round++;rolls=0;held.fill(false);if(round>5)(total>=target?completeLevel:failLevel)(total*30);else roll()}roll();
  return{keyDown(k){if(k==='Space')roll();if(k==='Enter')score()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>160&&p.y<270){const i=Math.floor((p.x-230)/90);if(i>=0&&i<5)held[i]=!held[i]}else if(p.x<450)roll();else score()},draw(c){bg(c,'#0d543d');dice.forEach((v,i)=>{rect(c,230+i*90,170,70,70,held[i]?'#ffe06b':'#fff','#111');txt(c,v,265+i*90,220,32,'#111')});rect(c,210,330,210,60,'#2579b8');rect(c,480,330,210,60,'#a54875');txt(c,'ROLL',315,370,22);txt(c,'SCORE',585,370,22);txt(c,`Round ${round}/5 • Rolls ${rolls}/3 • Total ${total}/${target}`,450,55,22)}}
}

function solitaireGame(s){
  const suits=['♥','♠','♦','♣'],red=x=>x==='♥'||x==='♦';let deck=[];for(const suit of suits)for(let rank=1;rank<=4;rank++)deck.push({suit,rank});deck.sort(()=>Math.random()-.5);const piles=[[],[],[],[]];deck.forEach((c,i)=>piles[i%4].push(c));const foundations={'♥':0,'♠':0,'♦':0,'♣':0};let selected=null;
  function tapPile(i){const p=piles[i];if(!p.length)return;const card=p[p.length-1];if(foundations[card.suit]===card.rank-1){foundations[card.suit]++;p.pop()}else if(selected===null)selected=i;else{const from=piles[selected],m=from[from.length-1],dest=piles[i],top=dest[dest.length-1];if(selected!==i&&(!top||(top.rank===m.rank+1&&red(top.suit)!==red(m.suit))))dest.push(from.pop());selected=null}if(Object.values(foundations).every(v=>v===4))completeLevel(2600)}
  return{pointer(p,t){if(t==='pointerdown'){const i=Math.floor((p.x-170)/145);if(i>=0&&i<4)tapPile(i)}},draw(c){bg(c,'#07523b');suits.forEach((suit,i)=>{rect(c,160+i*145,70,90,110,'#ffffff18','#fff');txt(c,`${suit}${foundations[suit]||''}`,205+i*145,135,30,red(suit)?'#ff7082':'#fff')});piles.forEach((pile,i)=>pile.forEach((card,j)=>{rect(c,170+i*145,220+j*28,90,110,'#fff',selected===i&&j===pile.length-1?'#ffe06b':'#111');txt(c,`${card.suit}${card.rank}`,215+i*145,270+j*28,24,red(card.suit)?'#d33':'#111')}));txt(c,'Move A→4 of each suit to the foundations',450,45,19)}}
}

function warGame(s){
  let player=Array.from({length:12},()=>2+Math.floor(Math.random()*13)),cpu=Array.from({length:12},()=>2+Math.floor(Math.random()*13)),round=0,ps=0,cs=0,last=null;
  function reveal(){if(round>=12)return;const a=player[round],b=cpu[round];if(a>b)ps++;else if(b>a)cs++;else{ps+=.5;cs+=.5}last=[a,b];round++;if(round===12)setTimeout(()=>((ps>cs)?completeLevel:failLevel)(ps*200),300)}
  return{keyDown(k){if(k==='Space'||k==='Enter')reveal()},pointer(p,t){if(t==='pointerdown')reveal()},draw(c){bg(c,'#4b1730');txt(c,'YOU',280,100,24);txt(c,'CPU',620,100,24);if(last){drawCard(c,245,150,last[0],true);drawCard(c,585,150,last[1],true)}rect(c,330,390,240,65,'#8f3d69');txt(c,'REVEAL',450,433,22);txt(c,`Round ${round}/12 • ${ps}–${cs}`,450,55,22)}}
}

function goFishGame(s){
  const ranks=['A','2','3','4','5','6'],deck=[];for(let r=0;r<6;r++)for(let k=0;k<4;k++)deck.push(r);deck.sort(()=>Math.random()-.5);let hand=deck.splice(0,5),cpu=deck.splice(0,5),books=0,cpuBooks=0;
  function collect(h){for(let r=0;r<6;r++)if(h.filter(x=>x===r).length===4){for(let k=0;k<4;k++)h.splice(h.indexOf(r),1);return 1}return 0}function ask(r){if(!hand.includes(r))return;const got=cpu.filter(x=>x===r);if(got.length){cpu=cpu.filter(x=>x!==r);hand.push(...got)}else if(deck.length)hand.push(deck.pop());books+=collect(hand);setTimeout(ai,250);finish()}function ai(){if(!cpu.length&&deck.length)cpu.push(deck.pop());if(!cpu.length)return;const r=cpu[Math.floor(Math.random()*cpu.length)],got=hand.filter(x=>x===r);if(got.length){hand=hand.filter(x=>x!==r);cpu.push(...got)}else if(deck.length)cpu.push(deck.pop());cpuBooks+=collect(cpu);finish()}function finish(){if((!deck.length&&!hand.length)||books+cpuBooks===6)(books>cpuBooks?completeLevel:failLevel)(books*500)}
  return{pointer(p,t){if(t!=='pointerdown')return;const groups=[...new Set(hand)].sort();const i=Math.floor((p.x-170)/100);if(groups[i]!==undefined)ask(groups[i])},draw(c){bg(c,'#125b70');txt(c,`Your books ${books} • Computer books ${cpuBooks} • Pond ${deck.length}`,450,55,22);const groups=[...new Set(hand)].sort();groups.forEach((r,i)=>{rect(c,170+i*100,350,80,110,'#fff','#111');txt(c,ranks[r],210+i*100,410,32,'#153');txt(c,`×${hand.filter(x=>x===r).length}`,210+i*100,445,16,'#153')});txt(c,'Tap a rank to ask the computer',450,300,20)}}
}

function diceRaceGame(s){
  const pos=[0,0],cpu=[0],finish=30;let roll=0,choose=0,waiting=true;
  function rollDie(){if(!waiting)return;roll=1+Math.floor(Math.random()*6);waiting=false}function move(){if(waiting||!roll)return;pos[choose]=Math.min(finish,pos[choose]+roll+(pos[choose]===9||pos[choose]===19?3:0));cpu[0]=Math.min(finish,cpu[0]+1+Math.floor(Math.random()*6));roll=0;waiting=true;if(pos.every(x=>x>=finish))completeLevel(2500);else if(cpu[0]>=finish)failLevel(0)}
  return{keyDown(k){if(k==='Space')waiting?rollDie():move();if(k==='ArrowLeft'||k==='ArrowRight')choose=1-choose},pointer(p,t){if(t!=='pointerdown')return;if(p.y>420){if(waiting)rollDie();else move()}else choose=p.y<250?0:1},draw(c){bg(c,'#e8d8ae');for(let i=0;i<=finish;i++){const x=70+(i%10)*76,y=90+Math.floor(i/10)*95;rect(c,x,y,68,68,i===9||i===19?'#ffe06b':'#fff','#886');txt(c,i,x+34,y+43,16,'#443')}for(let i=0;i<2;i++)circle(c,104+(pos[i]%10)*76,110+Math.floor(pos[i]/10)*95+i*16,12,i===choose?'#31cfff':'#206da0');circle(c,104+(cpu[0]%10)*76,145+Math.floor(cpu[0]/10)*95,12,'#ff5c74');rect(c,330,445,240,55,'#7c5a31');txt(c,waiting?'ROLL DIE':`MOVE TOKEN ${choose+1} (${roll})`,450,482,20)}}
}

function dotsBoxesGame(s){
  const R=4,C=5,ox=250,oy=100,cell=90,h=new Set(),v=new Set(),boxes=Array.from({length:R-1},()=>Array(C-1).fill(0));let turn=1,selected=null,score=[0,0,0];
  function edgeKey(a,b){return `${Math.min(a[0],b[0])},${Math.min(a[1],b[1])}-${Math.max(a[0],b[0])},${Math.max(a[1],b[1])}`}function boxDone(r,c){return h.has(edgeKey([r,c],[r,c+1]))&&h.has(edgeKey([r+1,c],[r+1,c+1]))&&v.has(edgeKey([r,c],[r+1,c]))&&v.has(edgeKey([r,c+1],[r+1,c+1]))}
  function point(r,c){if(selected===null){selected=[r,c];return}if(Math.abs(r-selected[0])+Math.abs(c-selected[1])!==1){selected=[r,c];return}const key=edgeKey(selected,[r,c]),set=r===selected[0]?h:v;if(set.has(key)){selected=null;return}set.add(key);let gained=false;for(let br=0;br<R-1;br++)for(let bc=0;bc<C-1;bc++)if(!boxes[br][bc]&&boxDone(br,bc)){boxes[br][bc]=turn;score[turn]++;gained=true}selected=null;if(!gained)turn=3-turn;if(h.size+v.size===R*(C-1)+(R-1)*C)(score[1]>score[2]?completeLevel:failLevel)(score[1]*400)}
  return{pointer(p,t){if(t!=='pointerdown')return;const c=Math.round((p.x-ox)/cell),r=Math.round((p.y-oy)/cell);if(r>=0&&r<R&&c>=0&&c<C)point(r,c)},draw(c){bg(c,'#f0e4ca');for(let r=0;r<R-1;r++)for(let col=0;col<C-1;col++)if(boxes[r][col])rect(c,ox+col*cell+8,oy+r*cell+8,cell-16,cell-16,boxes[r][col]===1?'#72d9ff':'#ff8ca2');c.strokeStyle='#533';c.lineWidth=6;for(const key of[...h,...v]){const[a,b]=key.split('-').map(x=>x.split(',').map(Number));c.beginPath();c.moveTo(ox+a[1]*cell,oy+a[0]*cell);c.lineTo(ox+b[1]*cell,oy+b[0]*cell);c.stroke()}for(let r=0;r<R;r++)for(let col=0;col<C;col++)circle(c,ox+col*cell,oy+r*cell,7,'#332');txt(c,`Player ${turn} • ${score[1]}–${score[2]}`,450,55,22,'#332')}}
}

function mancalaGame(s){
  let pits=[4,4,4,4,4,4,0,4,4,4,4,4,4,0],turn=0;
  function sow(i){if(turn!==0||i<0||i>5||!pits[i])return;let stones=pits[i];pits[i]=0;while(stones){i=(i+1)%14;if(i===13)continue;pits[i]++;stones--}if(i===6){}else turn=1;if(i>=0&&i<6&&pits[i]===1&&pits[12-i]>0){pits[6]+=pits[12-i]+1;pits[12-i]=pits[i]=0}end();if(turn===1)setTimeout(ai,250)}function ai(){const choices=[7,8,9,10,11,12].filter(i=>pits[i]);if(!choices.length)return end(true);let i=choices[Math.floor(Math.random()*choices.length)],stones=pits[i];pits[i]=0;while(stones){i=(i+1)%14;if(i===6)continue;pits[i]++;stones--}turn=0;end()}function end(force=false){if(force||pits.slice(0,6).every(x=>x===0)||pits.slice(7,13).every(x=>x===0)){pits[6]+=pits.slice(0,6).reduce((a,b)=>a+b,0);pits[13]+=pits.slice(7,13).reduce((a,b)=>a+b,0);(pits[6]>pits[13]?completeLevel:failLevel)(pits[6]*100)}}
  return{pointer(p,t){if(t!=='pointerdown')return;const i=Math.floor((p.x-190)/85);if(p.y>320)sow(i)},draw(c){bg(c,'#9a653b');rect(c,120,120,660,300,'#c58b54','#6e4327');for(let i=0;i<6;i++){circle(c,215+i*85,350,32,'#7c4b2d');txt(c,pits[i],215+i*85,359,20);circle(c,215+(5-i)*85,190,32,'#7c4b2d');txt(c,pits[7+i],215+(5-i)*85,199,20)}rect(c,135,160,55,220,'#71432b');rect(c,710,160,55,220,'#71432b');txt(c,pits[13],162,280,24);txt(c,pits[6],737,280,24);txt(c,turn===0?'Your turn':'Computer turn',450,55,22)}}
}

function morrisGame(s){
  const pts=[[1,1],[4,1],[7,1],[2,2],[4,2],[6,2],[3,3],[4,3],[5,3],[1,4],[2,4],[3,4],[5,4],[6,4],[7,4],[3,5],[4,5],[5,5],[2,6],[4,6],[6,6],[1,7],[4,7],[7,7]],adj=[[1,9],[0,2,4],[1,14],[4,10],[1,3,5,7],[4,13],[7,11],[4,6,8],[7,12],[0,10,21],[3,9,11,18],[6,10,15],[8,13,17],[5,12,14,20],[2,13,23],[11,16],[15,17,19],[12,16],[10,19],[16,18,20,22],[13,19],[9,22],[19,21,23],[14,22]],mills=[[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14],[15,16,17],[18,19,20],[21,22,23],[0,9,21],[3,10,18],[6,11,15],[1,4,7],[16,19,22],[8,12,17],[5,13,20],[2,14,23]];let board=Array(24).fill(0),placed=[0,0,0],turn=1,sel=null,remove=false;
  const forms=(i,w)=>mills.some(m=>m.includes(i)&&m.every(x=>board[x]===w));function click(i){if(turn!==1)return;if(remove){if(board[i]===2){board[i]=0;remove=false;turn=2;setTimeout(ai,250)}return}if(placed[1]<9){if(board[i])return;board[i]=1;placed[1]++;if(forms(i,1))remove=true;else{turn=2;setTimeout(ai,250)}}else if(sel===null){if(board[i]===1)sel=i}else if(board[i]===0&&adj[sel].includes(i)){board[i]=1;board[sel]=0;sel=null;if(forms(i,1))remove=true;else{turn=2;setTimeout(ai,250)}}check()}function ai(){let empt=board.map((v,i)=>v?null:i).filter(i=>i!==null),i;if(placed[2]<9){i=empt[Math.floor(Math.random()*empt.length)];board[i]=2;placed[2]++}else{const moves=[];board.forEach((v,a)=>{if(v===2)adj[a].forEach(b=>{if(!board[b])moves.push([a,b])})});if(!moves.length)return completeLevel(2500);const m=moves[Math.floor(Math.random()*moves.length)];board[m[1]]=2;board[m[0]]=0;i=m[1]}if(forms(i,2)){const choices=board.map((v,j)=>v===1?j:null).filter(j=>j!==null);if(choices.length)board[choices[Math.floor(Math.random()*choices.length)]]=0}turn=1;check()}function check(){const a=board.filter(x=>x===1).length,b=board.filter(x=>x===2).length;if(placed[1]>=9&&a<3)failLevel(0);if(placed[2]>=9&&b<3)completeLevel(2500)}
  return{pointer(p,t){if(t!=='pointerdown')return;let best=-1,d=28;pts.forEach((q,i)=>{const dd=Math.hypot(p.x-(140+q[0]*75),p.y-(20+q[1]*62));if(dd<d){d=dd;best=i}});if(best>=0)click(best)},draw(c){bg(c,'#34251c');c.strokeStyle='#d9b98c';c.lineWidth=4;for(const m of mills){c.beginPath();m.forEach((i,k)=>{const q=pts[i],x=140+q[0]*75,y=20+q[1]*62;k?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}pts.forEach((q,i)=>circle(c,140+q[0]*75,20+q[1]*62,16,board[i]===1?'#eee':board[i]===2?'#222':'#9b7657',sel===i?'#5ee7ff':''));txt(c,remove?'Remove an enemy piece':placed[1]<9?'Place a piece':'Move along a line',450,38,20)}}
}

function gomokuGame(s){
  const N=15,g=Array.from({length:N},()=>Array(N).fill(0)),cell=29,ox=247,oy=70;function win(w){for(let r=0;r<N;r++)for(let c=0;c<N;c++)for(const[dR,dC]of[[1,0],[0,1],[1,1],[1,-1]])if([0,1,2,3,4].every(k=>g[r+dR*k]?.[c+dC*k]===w))return true;return false}function play(r,c){if(g[r]?.[c])return;g[r][c]=1;if(win(1))return completeLevel(2500);const choices=[];for(let rr=0;rr<N;rr++)for(let cc=0;cc<N;cc++)if(!g[rr][cc]&&g.slice(Math.max(0,rr-1),rr+2).some(row=>row.slice(Math.max(0,cc-1),cc+2).some(Boolean)))choices.push([rr,cc]);const q=choices[Math.floor(Math.random()*choices.length)]||[7,7];g[q[0]][q[1]]=2;if(win(2))failLevel(0)}return{pointer(p,t){if(t==='pointerdown')play(Math.round((p.y-oy)/cell),Math.round((p.x-ox)/cell))},draw(c){bg(c,'#d8aa63');for(let i=0;i<N;i++){c.strokeStyle='#6c4b28';c.beginPath();c.moveTo(ox,oy+i*cell);c.lineTo(ox+(N-1)*cell,oy+i*cell);c.stroke();c.beginPath();c.moveTo(ox+i*cell,oy);c.lineTo(ox+i*cell,oy+(N-1)*cell);c.stroke()}for(let r=0;r<N;r++)for(let col=0;col<N;col++)if(g[r][col])circle(c,ox+col*cell,oy+r*cell,11,g[r][col]===1?'#fff':'#111')}}
}

function hexGame(s){
  const N=9,g=Array.from({length:N},()=>Array(N).fill(0)),rad=23,ox=270,oy=95;const neigh=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];function connected(w){const q=[],seen=new Set();if(w===1)for(let r=0;r<N;r++)if(g[r][0]===1){q.push([r,0]);seen.add(`${r},0`)}else{}else for(let c=0;c<N;c++)if(g[0][c]===2){q.push([0,c]);seen.add(`0,${c}`)}while(q.length){const[r,c]=q.shift();if((w===1&&c===N-1)||(w===2&&r===N-1))return true;for(const[dR,dC]of neigh){const rr=r+dR,cc=c+dC,k=`${rr},${cc}`;if(g[rr]?.[cc]===w&&!seen.has(k)){seen.add(k);q.push([rr,cc])}}}return false}function play(r,c){if(g[r]?.[c])return;g[r][c]=1;if(connected(1))return completeLevel(2600);const empty=[];for(let rr=0;rr<N;rr++)for(let cc=0;cc<N;cc++)if(!g[rr][cc])empty.push([rr,cc]);const q=empty.sort((a,b)=>Math.abs(a[0]-4)-Math.abs(b[0]-4))[Math.floor(Math.random()*Math.min(8,empty.length))]||empty[0];if(q)g[q[0]][q[1]]=2;if(connected(2))failLevel(0)}function center(r,c){return[ox+c*rad*1.75+r*rad*.88,oy+r*rad*1.52]}
  return{pointer(p,t){if(t!=='pointerdown')return;let best=null,d=rad;for(let r=0;r<N;r++)for(let c=0;c<N;c++){const q=center(r,c),dd=Math.hypot(p.x-q[0],p.y-q[1]);if(dd<d){d=dd;best=[r,c]}}if(best)play(...best)},draw(c){bg(c,'#18314a');for(let r=0;r<N;r++)for(let col=0;col<N;col++){const[x,y]=center(r,col);circle(c,x,y,rad-3,g[r][col]===1?'#5bdcff':g[r][col]===2?'#ff627b':'#d7e1eb','#506981')}txt(c,'Blue connects left–right • Red connects top–bottom',450,45,19)}}
}

function dominoesGame(s){
  let tiles=[];for(let a=0;a<=6;a++)for(let b=a;b<=6;b++)tiles.push([a,b]);tiles.sort(()=>Math.random()-.5);let hand=tiles.splice(0,7),cpu=tiles.splice(0,7),chain=[tiles.pop()],selected=null;
  const ends=()=>[chain[0][0],chain[chain.length-1][1]];function orient(tile,end,left){if(tile[1]===end)return left?tile:[tile[1],tile[0]];if(tile[0]===end)return left?[tile[1],tile[0]]:tile;return null}function play(i,left){const e=ends()[left?0:1],o=orient(hand[i],e,left);if(!o)return;if(left)chain.unshift(o);else chain.push(o);hand.splice(i,1);if(!hand.length)return completeLevel(2500);setTimeout(ai,200)}function ai(){const e=ends();let move=null;for(let i=0;i<cpu.length;i++)for(const left of[true,false]){const o=orient(cpu[i],e[left?0:1],left);if(o){move=[i,left,o];break}}if(move){const[i,left,o]=move;if(left)chain.unshift(o);else chain.push(o);cpu.splice(i,1)}else if(tiles.length)cpu.push(tiles.pop());if(!cpu.length)failLevel(0)}function drawTile(c,t,x,y,sel){rect(c,x,y,70,40,'#f7f1df',sel?'#5ee7ff':'#332');c.strokeStyle='#332';c.beginPath();c.moveTo(x+35,y);c.lineTo(x+35,y+40);c.stroke();txt(c,t[0],x+17,y+28,18,'#222');txt(c,t[1],x+53,y+28,18,'#222')}
  return{pointer(p,t){if(t!=='pointerdown')return;if(p.y>420){const i=Math.floor((p.x-85)/85);if(hand[i])selected=i}else if(selected!==null){play(selected,p.x<450);selected=null}},draw(c){bg(c,'#315b43');let x=100;chain.slice(-9).forEach(t=>{drawTile(c,t,x,220,false);x+=78});hand.forEach((t,i)=>drawTile(c,t,85+i*85,440,i===selected));txt(c,`Open ends ${ends()[0]} and ${ends()[1]} • Computer has ${cpu.length}`,450,55,21);txt(c,'Select a tile, then tap left or right half of table',450,390,18)}}
}

function volleyballGame(s){
  const p1={x:180,y:430,vx:0,vy:0,score:0},p2={x:720,y:430,vx:0,vy:0,score:0},ball={x:450,y:160,vx:180,vy:0};let ground=470;
  function jump(p){if(p.y>=430)p.vy=-440}function reset(dir){Object.assign(ball,{x:450,y:150,vx:180*dir,vy:0});p1.y=p2.y=430}
  return{keyDown(k){if(k==='Space')jump(p1);if(k==='KeyF')jump(p2)},update(dt){const v=240;if(s.pressed('ArrowLeft'))p1.x-=v*dt;if(s.pressed('ArrowRight'))p1.x+=v*dt;if(s.pressed('KeyA'))p2.x-=v*dt;if(s.pressed('KeyD'))p2.x+=v*dt;p1.x=clamp(p1.x,35,415);p2.x=clamp(p2.x,485,865);for(const p of[p1,p2]){p.vy+=900*dt;p.y+=p.vy*dt;if(p.y>430){p.y=430;p.vy=0}const d=Math.hypot(ball.x-p.x,ball.y-p.y);if(d<42){ball.vx=(ball.x-p.x)*7;ball.vy=-Math.abs(ball.vy)-240}}ball.vy+=650*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<15||ball.x>885)ball.vx*=-1;if(ball.x>438&&ball.x<462&&ball.y>250){ball.vx*=-.85;ball.x=ball.x<450?437:463}if(ball.y>ground){if(ball.x<450)p2.score++;else p1.score++;reset(ball.x<450?-1:1)}if(p1.score>=7||p2.score>=7)(p1.score>p2.score?completeLevel:failLevel)(p1.score*400)},draw(c){bg(c,'#7bd1ff');rect(c,0,470,W,70,'#e9c47f');rect(c,443,250,14,220,'#fff');rect(c,p1.x-22,p1.y-45,44,45,'#4bdcff');rect(c,p2.x-22,p2.y-45,44,45,'#ff5f7d');circle(c,ball.x,ball.y,14,'#fff','#235');txt(c,`${p1.score} — ${p2.score}`,450,45,26,'#16334e')}}
}

function airHockeyGame(s){
  const p1={x:200,y:270,r:28},p2={x:700,y:270,r:28},puck={x:450,y:270,r:16,vx:0,vy:0},score=[0,0,0];function reset(){Object.assign(puck,{x:450,y:270,vx:0,vy:0})}
  return{update(dt){const v=320;if(s.pressed('ArrowLeft'))p1.x-=v*dt;if(s.pressed('ArrowRight'))p1.x+=v*dt;if(s.pressed('ArrowUp'))p1.y-=v*dt;if(s.pressed('ArrowDown'))p1.y+=v*dt;if(s.pressed('KeyA'))p2.x-=v*dt;if(s.pressed('KeyD'))p2.x+=v*dt;if(s.pressed('KeyW'))p2.y-=v*dt;if(s.pressed('KeyS'))p2.y+=v*dt;p1.x=clamp(p1.x,40,425);p2.x=clamp(p2.x,475,860);for(const p of[p1,p2]){p.y=clamp(p.y,85,500);const d=Math.hypot(puck.x-p.x,puck.y-p.y);if(d<p.r+puck.r){const nx=(puck.x-p.x)/(d||1),ny=(puck.y-p.y)/(d||1);puck.vx=nx*430;puck.vy=ny*430}}puck.x+=puck.vx*dt;puck.y+=puck.vy*dt;puck.vx*=Math.pow(.35,dt);puck.vy*=Math.pow(.35,dt);if(puck.y<75+puck.r||puck.y>H-puck.r)puck.vy*=-.85;if(puck.x<0&&puck.y>210&&puck.y<330){score[2]++;reset()}else if(puck.x>W&&puck.y>210&&puck.y<330){score[1]++;reset()}else if(puck.x<puck.r||puck.x>W-puck.r)puck.vx*=-.85;if(score[1]>=5||score[2]>=5)(score[1]>score[2]?completeLevel:failLevel)(score[1]*500)},draw(c){bg(c,'#d9f5ff');c.strokeStyle='#2c7ba4';c.lineWidth=6;c.strokeRect(15,65,W-30,H-80);c.beginPath();c.arc(450,300,75,0,7);c.stroke();c.strokeRect(0,210,55,120);c.strokeRect(845,210,55,120);circle(c,p1.x,p1.y,p1.r,'#34bce8');circle(c,p2.x,p2.y,p2.r,'#ef5571');circle(c,puck.x,puck.y,puck.r,'#222');txt(c,`${score[1]} — ${score[2]}`,450,42,26,'#17445d')}}
}

function bowlingGame(s){
  let aim=0,power=0,setting=false,balls=2,score=0,frame=1,pins=[];function resetPins(){pins=[];for(let r=0;r<4;r++)for(let i=0;i<=r;i++)pins.push({x:450+(i-r/2)*34,y:120+r*32,up:true})}resetPins();function action(){if(!setting){setting=true;power=0}else{const accuracy=Math.max(0,1-Math.abs(aim)/4),force=power;let knocked=0;for(const pin of pins)if(pin.up&&Math.random()<accuracy*force*.95){pin.up=false;knocked++}score+=knocked;balls--;setting=false;if(!pins.some(p=>p.up)||balls===0){frame++;if(frame>5)return(score>=25?completeLevel:failLevel)(score*100);balls=2;resetPins()}}}
  return{keyDown(k){if(k==='ArrowLeft')aim=Math.max(-3,aim-1);if(k==='ArrowRight')aim=Math.min(3,aim+1);if(k==='Space'||k==='Enter')action()},pointer(p,t){if(t==='pointerdown'){aim=clamp(Math.round((p.x-450)/80),-3,3);action()}},update(dt){if(setting)power=(Math.sin(performance.now()/230)+1)/2},draw(c){bg(c,'#2c5070');rect(c,260,60,380,480,'#d7aa65');for(const pin of pins)if(pin.up){circle(c,pin.x,pin.y,12,'#fff');rect(c,pin.x-7,pin.y,pin.x?14:14,25,'#fff')}c.strokeStyle='#ff5b6f';c.lineWidth=5;c.beginPath();c.moveTo(450,500);c.lineTo(450+aim*40,360);c.stroke();rect(c,300,465,300,20,'#233');rect(c,300,465,300*power,20,'#54de89');txt(c,`Frame ${frame}/5 • Balls ${balls} • Score ${score}`,450,40,21)}}
}

function fishingGame(s){
  let state='ready',wait=0,tension=50,fish=0,total=0,target=8+Math.floor(s.level/2),safe=50;
  function action(){if(state==='ready'){state='waiting';wait=1+Math.random()*2.5}else if(state==='bite'){state='hooked';fish=2+Math.random()*4}else if(state==='hooked')tension+=8}
  return{keyDown(k){if(k==='Space'||k==='Enter')action();if(k==='ArrowLeft')tension-=5;if(k==='ArrowRight')tension+=5},pointer(p,t){if(t==='pointerdown')action()},update(dt){if(state==='waiting'){wait-=dt;if(wait<=0){state='bite';wait=1}}else if(state==='bite'){wait-=dt;if(wait<=0)state='ready'}else if(state==='hooked'){safe=50+Math.sin(performance.now()/500)*22;tension+=(safe-tension)*dt*.7;tension-=dt*2;if(tension<10||tension>90){state='ready';tension=50}else{fish-=dt*(1-Math.abs(tension-safe)/60);if(fish<=0){const w=1+Math.floor(Math.random()*4);total+=w;state='ready';tension=50;if(total>=target)completeLevel(total*250)}}}},draw(c){bg(c,'#78c8e9');rect(c,0,360,W,180,'#1679a5');txt(c,state==='ready'?'CAST':state==='waiting'?'Waiting…':state==='bite'?'BITE! TAP NOW':'REEL! Keep tension in green',450,80,28,'#16324a');rect(c,200,430,500,30,'#26394d');rect(c,200+safe*5-60,430,120,30,'#51db83');rect(c,200+tension*5-5,420,10,50,'#ffe05c');txt(c,`Catch weight ${total}/${target}`,450,330,22,'#fff')}}
}

function cookingGame(s){
  const ingredients=['🍞','🥬','🍅','🧀','🥩','🍳'],orders=[[0,1,2],[0,4,3],[5,2,3],[0,1,4,2]],buttons=ingredients.map((v,i)=>({x:130+i*110,y:360,w:90,h:75,i}));let order=orders[(s.level-1)%orders.length],made=[],served=0,time=55,target=4+Math.min(3,Math.floor((s.level-1)/10));
  function tap(i){made.push(i);if(made.some((v,k)=>v!==order[k])){made=[];time-=2}}function serve(){if(made.length===order.length&&made.every((v,i)=>v===order[i])){served++;made=[];order=orders[Math.floor(Math.random()*orders.length)];if(served>=target)completeLevel(served*450)}else{made=[];time-=3}}
  return{keyDown(k){if(k==='Enter'||k==='Space')serve()},pointer(p,t){if(t!=='pointerdown')return;const b=buttons.find(x=>buttonHit(p,x));if(b)tap(b.i);else if(p.y>460)serve()},update(dt){time-=dt;if(time<=0)failLevel(served*200)},draw(c){bg(c,'#5a2f2a');txt(c,'ORDER',450,75,24);txt(c,order.map(i=>ingredients[i]).join('  '),450,145,44);txt(c,'PLATE',450,230,22);txt(c,made.map(i=>ingredients[i]).join('  ')||'—',450,290,42);buttons.forEach(b=>{rect(c,b.x,b.y,b.w,b.h,'#f0c685');txt(c,ingredients[b.i],b.x+b.w/2,b.y+52,32)});rect(c,340,465,220,50,'#4ca366');txt(c,'SERVE',450,498,20);txt(c,`${served}/${target} orders • ${Math.ceil(time)}s`,450,35,20)}}
}

function farmGame(s){
  const plots=Array.from({length:12},()=>({state:0,age:0,water:false}));let tool=0,coins=12,day=1,value=0,target=20+Math.min(50,Math.floor(s.level*1.25));const tools=['SEED','WATER','HARVEST'];
  function act(i){const p=plots[i];if(tool===0&&p.state===0&&coins>=2){coins-=2;p.state=1;p.age=0;p.water=false}else if(tool===1&&p.state===1)p.water=true;else if(tool===2&&p.state===2){coins+=7;value+=7;p.state=0;if(value>=target)completeLevel(value*80)}}function nextDay(){day++;for(const p of plots)if(p.state===1&&p.water){p.age++;p.water=false;if(p.age>=2)p.state=2}if(day>14&&value<target)failLevel(value*50)}
  return{keyDown(k){if(k==='Space')tool=(tool+1)%3;if(k==='Enter')nextDay()},pointer(p,t){if(t!=='pointerdown')return;if(p.y<420){const c=Math.floor((p.x-210)/120),r=Math.floor((p.y-100)/100),i=r*4+c;if(plots[i])act(i)}else nextDay()},draw(c){bg(c,'#76b95b');plots.forEach((p,i)=>{const x=210+(i%4)*120,y=100+Math.floor(i/4)*100;rect(c,x,y,100,80,'#6d4528','#d3b16e');txt(c,p.state===0?'':p.state===1?(p.water?'🌱💧':'🌱'):'🌽',x+50,y+53,30)});rect(c,300,435,300,50,'#395f31');txt(c,`NEXT DAY • ${tools[tool]}`,450,468,19);txt(c,`Day ${day}/14 • Coins ${coins} • Harvest ${value}/${target}`,450,45,21)}}
}

function petCareGame(s){
  const needs={hunger:78,happy:78,clean:78,energy:78};let time=0;const actions=[['FEED','hunger'],['PLAY','happy'],['WASH','clean'],['SLEEP','energy']];function act(k){needs[k]=Math.min(100,needs[k]+32);for(const q of Object.keys(needs))if(q!==k)needs[q]-=2}
  return{pointer(p,t){if(t!=='pointerdown')return;const i=Math.floor((p.x-170)/145);if(actions[i])act(actions[i][1])},update(dt){time+=dt;for(const k of Object.keys(needs))needs[k]-=dt*gentleScale(s,.66,.98);if(Object.values(needs).some(v=>v<=0))failLevel(time*100);if(time>=40)completeLevel(Object.values(needs).reduce((a,b)=>a+b,0)*8)},draw(c){bg(c,'#f1d7e8');txt(c,'🐶',450,210,100);Object.entries(needs).forEach(([k,v],i)=>{txt(c,k.toUpperCase(),180,285+i*35,16,'#563b52','left');rect(c,300,268+i*35,400,22,'#c39ab8');rect(c,300,268+i*35,400*clamp(v,0,100)/100,22,['#ff8a72','#65d88d','#62bfff','#a58cff'][i])});actions.forEach((a,i)=>{rect(c,170+i*145,430,125,55,'#815a89');txt(c,a[0],232+i*145,466,17)});txt(c,`Care time ${Math.floor(time)}/40`,450,45,20,'#563b52')}}
}

function cityBuilderGame(s){
  const R=5,C=8,g=Array.from({length:R},()=>Array(C).fill(0)),types=['HOME','SHOP','FACTORY','PARK','POWER'];let type=0,budget=140,pop=0,target=30+Math.min(70,Math.floor(s.level*1.75));const costs=[10,15,18,8,25],colors=['#7dc9ff','#ffe06a','#a88b7a','#65d77a','#bd7cff'];
  function place(r,c){if(g[r]?.[c]||budget<costs[type])return;g[r][c]=type+1;budget-=costs[type];recalc()}function recalc(){const counts=Array(6).fill(0);g.flat().forEach(v=>counts[v]++);const power=counts[5]*7,need=counts[1]+counts[2]+counts[3];pop=Math.max(0,counts[1]*6+counts[4]*2-Math.max(0,need-power)*3);budget+=Math.floor(counts[2]*1.5+counts[3]*2-counts[1]*.5);if(pop>=target&&budget>=0)completeLevel(pop*50+budget)}
  return{keyDown(k){if(k==='Space'||k==='Enter')type=(type+1)%types.length},pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-100)/75),c=Math.floor((p.x-150)/75);if(g[r]?.[c]!==undefined)place(r,c)},draw(c){bg(c,'#8fd0ef');for(let r=0;r<R;r++)for(let col=0;col<C;col++){const v=g[r][col];rect(c,150+col*75,100+r*75,68,68,v?colors[v-1]:'#d7e8dc','#496b61');if(v)txt(c,['🏠','🏪','🏭','🌳','⚡'][v-1],184+col*75,145+r*75,24)}txt(c,`${types[type]} • Cost ${costs[type]} • Budget ${budget} • Population ${pop}/${target}`,450,48,19)}}
}

function pinballGame(s){
  const ball={x:700,y:450,r:10,vx:0,vy:0},bumpers=[[330,180],[500,150],[610,260],[390,300]],targets=bumpers.map(()=>true);let balls=3,score=0,launched=false,targetScore=1800+Math.min(2700,Math.floor(s.level*65));
  function launch(){if(!launched){ball.vx=-125;ball.vy=-500;launched=true}}return{keyDown(k){if(k==='Space')launch()},update(dt){if(!launched)return;ball.vy+=500*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<130||ball.x>770)ball.vx*=-.9;if(ball.y<70)ball.vy=Math.abs(ball.vy);for(let i=0;i<bumpers.length;i++){const b=bumpers[i],d=Math.hypot(ball.x-b[0],ball.y-b[1]);if(d<38){const nx=(ball.x-b[0])/(d||1),ny=(ball.y-b[1])/(d||1);ball.vx=nx*315;ball.vy=ny*315-75;if(targets[i]){targets[i]=false;score+=500}}}const left=s.pressed('ArrowLeft','KeyA'),right=s.pressed('ArrowRight','KeyD');if(ball.y>410&&ball.y<485&&((left&&ball.x<450)||(right&&ball.x>450))){ball.vy=-440;ball.vx+=(ball.x<450?115:-115)}if(ball.y>H+20){balls--;if(!balls)return(score>=targetScore?completeLevel:failLevel)(score);Object.assign(ball,{x:700,y:450,vx:0,vy:0});launched=false;targets.fill(true)}if(score>=targetScore)completeLevel(score)},draw(c){bg(c,'#21113e');c.strokeStyle='#7be8ff';c.lineWidth=8;c.strokeRect(120,60,660,470);bumpers.forEach((b,i)=>circle(c,b[0],b[1],30,targets[i]?'#ff5f8a':'#555','#fff'));circle(c,ball.x,ball.y,ball.r,'#fff');c.strokeStyle='#ffe06a';c.lineWidth=10;c.beginPath();c.moveTo(250,470);c.lineTo(420,500);c.moveTo(650,470);c.lineTo(480,500);c.stroke();txt(c,`Score ${score}/${targetScore} • Balls ${balls}`,450,38,21)}}
}

function match3Game(s){
  const R=8,C=8,K=6,g=Array.from({length:R},()=>Array.from({length:C},()=>Math.floor(Math.random()*K))),colors=['#ff5f7b','#53cfff','#ffe05e','#64db86','#a877ff','#ff9e4c'];let selected=null,moves=20,score=0,target=800+s.level*40,cell=52,ox=242,oy=70;
  function matches(){const set=new Set();for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(c<C-2&&g[r][c]===g[r][c+1]&&g[r][c]===g[r][c+2])for(let k=c;k<C&&g[r][k]===g[r][c];k++)set.add(`${r},${k}`);if(r<R-2&&g[r][c]===g[r+1][c]&&g[r][c]===g[r+2][c])for(let k=r;k<R&&g[k][c]===g[r][c];k++)set.add(`${k},${c}`)}return set}function resolve(){let m=matches();if(!m.size)return false;score+=m.size*50;for(const q of m){const[r,c]=q.split(',').map(Number);g[r][c]=-1}for(let c=0;c<C;c++){const vals=[];for(let r=R-1;r>=0;r--)if(g[r][c]>=0)vals.push(g[r][c]);for(let r=R-1,i=0;r>=0;r--,i++)g[r][c]=i<vals.length?vals[i]:Math.floor(Math.random()*K)}setTimeout(()=>{if(matches().size)resolve()},100);return true}function choose(r,c){if(selected===null){selected=[r,c];return}if(Math.abs(r-selected[0])+Math.abs(c-selected[1])!==1){selected=[r,c];return}const[a,b]=selected;[g[a][b],g[r][c]]=[g[r][c],g[a][b]];if(!resolve())[g[a][b],g[r][c]]=[g[r][c],g[a][b]];else moves--;selected=null;if(score>=target)completeLevel(score);else if(moves<=0)failLevel(score)}
  return{pointer(p,t){if(t==='pointerdown')choose(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell))},draw(c){bg(c,'#402052');for(let r=0;r<R;r++)for(let col=0;col<C;col++){circle(c,ox+(col+.5)*cell,oy+(r+.5)*cell,21,colors[g[r][col]],selected&&selected[0]===r&&selected[1]===col?'#fff':'')}txt(c,`Score ${score}/${target} • Moves ${moves}`,450,38,21)}}
}

function robotCodeGame(s){
  const map=['########','#R  #  #','# #   B#','# ## # #','#    #G#','########'].map(r=>r.split('')),program=[];let robot={r:1,c:1,d:1},running=false,pc=0,timer=0,collected=false;const cmds=['MOVE','LEFT','RIGHT'];
  function add(i){if(program.length<12)program.push(i)}function run(){robot={r:1,c:1,d:1};pc=0;collected=false;running=true}function step(){if(pc>=program.length){running=false;return}const cmd=program[pc++];if(cmd===1)robot.d=(robot.d+3)%4;else if(cmd===2)robot.d=(robot.d+1)%4;else{const dirs=[[-1,0],[0,1],[1,0],[0,-1]],d=dirs[robot.d],nr=robot.r+d[0],nc=robot.c+d[1];if(map[nr]?.[nc]!=='#'){robot.r=nr;robot.c=nc;if(map[nr][nc]==='B')collected=true;if(map[nr][nc]==='G'&&collected){running=false;completeLevel(2500-program.length*50)}}}}
  return{keyDown(k){if(k==='Space')run();if(k==='Enter')program.pop()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>430){const i=Math.floor((p.x-170)/150);if(i<3)add(i);else if(i===3)run();else program.pop()}},update(dt){if(running){timer+=dt;if(timer>.35){timer=0;step()}}},draw(c){bg(c,'#18283b');const cell=65,ox=190,oy=65;for(let r=0;r<map.length;r++)for(let col=0;col<map[r].length;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,map[r][col]==='#'?'#34475a':'#d7e4ea','#758695');if(map[r][col]==='B'&&!collected)txt(c,'⚡',ox+(col+.5)*cell,oy+(r+.68)*cell,28);if(map[r][col]==='G')txt(c,'★',ox+(col+.5)*cell,oy+(r+.68)*cell,28,'#5bdc82')}txt(c,['▲','▶','▼','◀'][robot.d],ox+(robot.c+.5)*cell,oy+(robot.r+.68)*cell,30,'#ff5e7b');['MOVE','LEFT','RIGHT','RUN','UNDO'].forEach((v,i)=>{rect(c,170+i*150,440,130,50,'#3b5d7a');txt(c,v,235+i*150,473,16)});txt(c,program.map(i=>cmds[i]).join(' → ')||'Program is empty',450,415,18)}}
}
