'use strict';

/* 39 additional game engines. Each factory implements mechanics that match its title. */
window.EXTRA_GAME_FACTORIES={
  chesstactics:chessTacticsGame,wordsearch:wordSearchGame,crossword:crosswordGame,scramble:scrambleGame,
  mathsprint:mathSprintGame,typingrace:typingRaceGame,rhythm:rhythmGame,sequencer:sequencerGame,
  paintnumbers:paintNumbersGame,jigsaw:jigsawGame,sliding:slidingGame,pipes:pipesGame,laser:laserGame,
  tangram:tangramGame,nonogram:nonogramGame,mastermind:mastermindGame,codebreaker:codeBreakerGame,
  yahtzee:yahtzeeGame,solitaire:solitaireGame,war:warGame,gofish:goFishGame,dicerace:diceRaceGame,
  dotsboxes:dotsBoxesGame,mancala:mancalaGame,morris:morrisGame,gomoku:gomokuGame,hex:hexGame,
  dominoes:dominoesGame,volleyball:volleyballGame,airhockey:airHockeyGame,bowling:bowlingGame,
  fishing:fishingGame,cooking:cookingGame,farm:farmGame,petcare:petCareGame,citybuilder:cityBuilderGame,
  pinball:pinballGame,match3:match3Game,robotcode:robotCodeGame
};

function chessTacticsGame(s){
  const cell=58,ox=218,oy=58,glyph={w:{K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙'},b:{K:'♚',Q:'♛',R:'♜',B:'♝',N:'♞',P:'♟'}},templates=[
    {name:'Knight fork',pieces:[['w','K',7,6],['w','Q',6,3],['w','N',5,5],['b','K',0,6],['b','Q',1,3],['b','R',0,0],['b','P',1,6]],line:[[5,5,3,4],[0,6,1,5],[3,4,1,3]]},
    {name:'Back-rank net',pieces:[['w','K',7,6],['w','Q',4,7],['w','R',7,4],['b','K',0,6],['b','R',0,5],['b','P',1,5],['b','P',1,6],['b','P',1,7]],line:[[4,7,1,7],[0,5,1,5],[7,4,0,4]]},
    {name:'Remove defender',pieces:[['w','K',7,6],['w','Q',5,3],['w','B',4,2],['b','K',0,6],['b','Q',1,3],['b','N',2,5],['b','P',1,6]],line:[[4,2,2,4],[2,5,2,4],[5,3,1,3]]},
    {name:'Skewer',pieces:[['w','K',7,1],['w','R',6,0],['w','B',5,2],['b','K',0,6],['b','Q',1,5],['b','P',1,6]],line:[[5,2,1,6],[0,6,0,7],[1,6,0,5]]},
    {name:'Deflection',pieces:[['w','K',7,6],['w','Q',4,4],['w','R',7,0],['b','K',0,6],['b','R',0,7],['b','Q',2,6],['b','P',1,6]],line:[[4,4,1,7],[0,7,1,7],[7,0,0,0]]},
    {name:'Discovered attack',pieces:[['w','K',7,6],['w','R',7,3],['w','B',5,3],['b','K',0,3],['b','Q',1,3],['b','P',1,2],['b','P',1,4]],line:[[5,3,3,1],[0,3,0,2],[7,3,1,3]]},
    {name:'Clearance',pieces:[['w','K',7,6],['w','Q',6,3],['w','R',7,7],['b','K',0,6],['b','R',0,7],['b','P',1,6],['b','P',1,7]],line:[[7,7,1,7],[0,7,1,7],[6,3,1,7]]},
    {name:'Double attack',pieces:[['w','K',7,6],['w','Q',5,2],['w','N',6,4],['b','K',0,6],['b','Q',1,2],['b','R',0,0],['b','P',1,6]],line:[[6,4,4,5],[0,6,0,7],[5,2,1,2]]},
    {name:'Pin and win',pieces:[['w','K',7,6],['w','Q',6,4],['w','R',7,3],['b','K',0,4],['b','Q',1,4],['b','N',2,4]],line:[[7,3,1,3],[0,4,0,5],[6,4,1,4]]},
    {name:'Mate net',pieces:[['w','K',7,6],['w','Q',4,6],['w','R',7,7],['b','K',0,7],['b','R',0,6],['b','P',1,6],['b','P',1,7]],line:[[4,6,1,7],[0,6,1,6],[7,7,0,7]]}
  ];
  const base=templates[(s.level-1)%templates.length],variant=Math.floor((s.level-1)/templates.length)%4;function tr(r,c){for(let i=0;i<variant;i++)[r,c]=[c,7-r];return[r,c]}const pieces=base.pieces.map(([side,type,r,c])=>{const q=tr(r,c);return{side,type,r:q[0],c:q[1]}}),line=base.line.map(m=>{const a=tr(m[0],m[1]),b=tr(m[2],m[3]);return[a[0],a[1],b[0],b[1]]});let step=0,selected=null,mistakes=0,busy=false;
  function pieceAt(r,c){return pieces.find(q=>q.r===r&&q.c===c)}function movePiece(m){const q=pieceAt(m[0],m[1]);if(!q)return;const captured=pieceAt(m[2],m[3]);if(captured)pieces.splice(pieces.indexOf(captured),1);q.r=m[2];q.c=m[3]}
  function play(r,c){if(busy||s.completed)return;const expected=line[step];if(!selected){const q=pieceAt(r,c);if(q?.side==='w')selected=[r,c];return}if(selected[0]===r&&selected[1]===c){selected=null;return}if(selected[0]===expected[0]&&selected[1]===expected[1]&&r===expected[2]&&c===expected[3]){movePiece(expected);selected=null;step++;if(step>=line.length)return completeLevel(2500+Math.max(0,2-mistakes)*350);busy=true;setTimeout(()=>{const reply=line[step];movePiece(reply);step++;busy=false;if(step>=line.length)completeLevel(2500);},420)}else{mistakes++;selected=null;if(mistakes>=2)failLevel(step*500)}}
  return{pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(r>=0&&r<8&&c>=0&&c<8)play(r,c)},draw(c){bg(c,'#172033');for(let r=0;r<8;r++)for(let col=0;col<8;col++)rect(c,ox+col*cell,oy+r*cell,cell,cell,(r+col)%2?'#6b7f9c':'#d8e0ea');for(const q of pieces){const chosen=selected&&selected[0]===q.r&&selected[1]===q.c;txt(c,glyph[q.side][q.type],ox+(q.c+.5)*cell,oy+(q.r+.73)*cell,44,chosen?'#27dfff':q.side==='w'?'#fff':'#151515')}txt(c,`${base.name} • Find the best ${Math.ceil((line.length-step)/2)}-move line • Mistakes ${mistakes}/2`,450,36,19);if(s.level<=4&&!busy){const e=line[step];txt(c,`Hint: move from ${String.fromCharCode(97+e[1])}${8-e[0]}`,450,525,16,'#b8c8e4')}}}
}

function wordSearchGame(s){
  const banks=[['STAR','GAME','CODE','PLAY'],['MOON','MARS','COMET','ORBIT'],['APPLE','GRAPE','MELON','PEAR'],['TIGER','PANDA','EAGLE','WHALE'],['PIANO','DRUM','FLUTE','SONG'],['TRAIN','PLANE','TRUCK','BOAT'],['EARTH','WATER','FIRE','WIND'],['ROBOT','LASER','CHIP','CLOUD'],['SMILE','LAUGH','HAPPY','KIND'],['GREEN','BLUE','GOLD','PINK']],words=banks[(s.level-1)%banks.length],N=10,rng=seedForLevel(s,2500+s.level),grid=Array.from({length:N},()=>Array.from({length:N},()=>String.fromCharCode(65+Math.floor(rng()*26)))),dirs=[[0,1],[1,0],[1,1],[-1,1]];
  words.forEach((w,i)=>{let placed=false;for(let tries=0;tries<100&&!placed;tries++){const[dr,dc]=dirs[(i+seededInt(rng,0,3))%dirs.length],r=seededInt(rng,dr<0?w.length-1:0,dr>0?N-w.length:N-1),c=seededInt(rng,0,dc>0?N-w.length:N-1);if([...w].every((ch,k)=>{const old=grid[r+dr*k][c+dc*k];return !old||old===ch||/^[A-Z]$/.test(old)})){[...w].forEach((ch,k)=>grid[r+dr*k][c+dc*k]=ch);placed=true}}});let start=null,found=new Set();const cell=42,ox=240,oy=65;
  function finish(p){if(!start)return;const a=[Math.floor((start.y-oy)/cell),Math.floor((start.x-ox)/cell)],b=[Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell)],dr=Math.sign(b[0]-a[0]),dc=Math.sign(b[1]-a[1]);if(!(dr===0||dc===0||Math.abs(b[0]-a[0])===Math.abs(b[1]-a[1]))){start=null;return}let str='',r=a[0],c=a[1];while(r>=0&&r<N&&c>=0&&c<N){str+=grid[r][c];if(r===b[0]&&c===b[1])break;r+=dr;c+=dc}const idx=words.findIndex(w=>w===str||w===[...str].reverse().join(''));if(idx>=0)found.add(idx);start=null;if(found.size===words.length)completeLevel(2200+s.level*15)}
  return{pointer(p,t){if(t==='pointerdown')start={...p};if(t==='pointerup')finish(p)},draw(c){bg(c,'#102c40');for(let r=0;r<N;r++)for(let col=0;col<N;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,'#edf7ff','#47728a');txt(c,grid[r][col],ox+(col+.5)*cell,oy+(r+.68)*cell,20,'#153245')}txt(c,words.map((w,i)=>found.has(i)?`✓ ${w}`:w).join('   '),450,36,20)}}
}

function crosswordGame(s){
  const sets=[
    {w:['CAT','ARE','TEN'],cl:['Feline','Exist','After nine']},
    {w:['APE','PEA','EAR'],cl:['Primate','Green vegetable','Hearing organ']},
    {w:['CAR','APE','RED'],cl:['Road vehicle','Primate','Primary color']},
    {w:['SAD','ARE','DEN'],cl:['Unhappy','Exist','Animal home']},
    {w:['MAN','ARE','NET'],cl:['Adult male','Exist','Catching mesh']},
    {w:['PEN','ERA','NAT'],cl:['Writing tool','Time period','Small insect']},
    {w:['TEA','EAR','ART'],cl:['Hot drink','Hearing organ','Creative work']},
    {w:['RAT','APE','TEN'],cl:['Rodent','Primate','After nine']}
  ],q=sets[(s.level-1)%sets.length],solution=q.w,grid=Array.from({length:3},()=>Array(3).fill('')),cell=110,ox=285,oy=90;let selected=[0,0];const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  function put(ch){grid[selected[0]][selected[1]]=ch;let i=(selected[0]*3+selected[1]+1)%9;selected=[Math.floor(i/3),i%3];if(grid.every((r,i)=>r.join('')===solution[i]))completeLevel(2500)}
  return{keyDown(k){if(/^Key[A-Z]$/.test(k))put(k.slice(3));if(k==='Backspace')grid[selected[0]][selected[1]]=''},pointer(p,t){if(t!=='pointerdown')return;if(p.y<420){const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(grid[r]?.[c]!==undefined)selected=[r,c]}else{const i=Math.floor((p.x-90)/28);if(i>=0&&i<26)put(letters[i])}},draw(c){bg(c,'#f2ead8');for(let r=0;r<3;r++)for(let col=0;col<3;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,selected[0]===r&&selected[1]===col?'#d9efff':'#fff','#1d3557');txt(c,grid[r][col],ox+(col+.5)*cell,oy+(r+.68)*cell,42,'#13243c')}txt(c,`Across and down: ${q.cl.join(' • ')}`,450,55,18,'#332c26');for(let i=0;i<26;i++){const x=90+i*28;rect(c,x,455,25,36,'#fff','#536');txt(c,letters[i],x+12,480,15,'#213')}}}
}

function scrambleGame(s){
  const bank=[['PLANET','World in space'],['PUZZLE','Something to solve'],['ROCKET','Space vehicle'],['JUNGLE','Dense tropical forest'],['ARCADE','Place full of games'],['CASTLE','Fortified home'],['BRIDGE','Crosses a river'],['DRAGON','Mythical creature'],['GARDEN','Place for plants'],['ISLAND','Land surrounded by water'],['MAGNET','Attracts iron'],['ORANGE','Fruit and color'],['PIRATE','Sailing treasure hunter'],['RABBIT','Long-eared animal'],['SILVER','Shiny metal'],['TUNNEL','Underground passage'],['VIOLIN','String instrument'],['WINDOW','Opening with glass'],['YELLOW','Bright color'],['ZEBRAS','Striped animals']],q=bank[(s.level-1)%bank.length],rng=seedForLevel(s,418),letters=[...q[0]];for(let i=letters.length-1;i>0;i--){const j=seededInt(rng,0,i);[letters[i],letters[j]]=[letters[j],letters[i]]}if(letters.join('')===q[0])[letters[0],letters[1]]=[letters[1],letters[0]];const used=Array(letters.length).fill(false);let answer='';
  function choose(i){if(used[i])return;used[i]=true;answer+=letters[i];if(answer.length===q[0].length)(answer===q[0]?completeLevel:failLevel)(1800)}function undo(){for(let i=used.length-1;i>=0;i--)if(used[i]){used[i]=false;answer=answer.slice(0,-1);break}}
  return{keyDown(k){if(k==='Backspace'||k==='Enter')undo()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>330&&p.y<420){const i=Math.floor((p.x-180)/90);if(i>=0&&i<letters.length)choose(i)}else if(p.y>440)undo()},draw(c){bg(c,'#2b1846');txt(c,q[1],450,120,28);txt(c,answer.padEnd(q[0].length,'_').split('').join(' '),450,230,40,'#ffe066');letters.forEach((ch,i)=>{rect(c,180+i*90,340,70,70,used[i]?'#4b3d5f':'#4ad7e8');txt(c,ch,215+i*90,387,30,used[i]?'#8d829b':'#10243a')});rect(c,340,455,220,48,'#9a4cc0');txt(c,'UNDO',450,488,20)}}
}

function mathSprintGame(s){
  let score=0,time=30,q=null,buttons=[];const target=8+Math.floor(s.level/4);
  function next(){const a=1+Math.floor(Math.random()*12),b=1+Math.floor(Math.random()*12),ops=['+','−','×'],op=ops[Math.floor(Math.random()*ops.length)],ans=op==='+'?a+b:op==='−'?a-b:a*b;let vals=[ans,ans+1,ans-1,ans+(Math.random()<.5?2:-2)].sort(()=>Math.random()-.5);q={text:`${a} ${op} ${b} = ?`,ans};buttons=vals.map((v,i)=>({x:150+(i%2)*310,y:270+Math.floor(i/2)*90,w:280,h:65,v}))}next();
  function pick(v){if(v===q.ans){score++;time+=1.5;if(score>=target)return completeLevel(score*250)}else time-=3;next()}
  return{pointer(p,t){if(t==='pointerdown'){const b=buttons.find(x=>buttonHit(p,x));if(b)pick(b.v)}},keyDown(k){const i={Digit1:0,Digit2:1,Digit3:2,Digit4:3}[k];if(i!==undefined)pick(buttons[i].v)},update(dt){time-=dt;if(time<=0)failLevel(score*100)},draw(c){bg(c,'#102b55');txt(c,q.text,450,180,46);buttons.forEach((b,i)=>{rect(c,b.x,b.y,b.w,b.h,'#28528b','#6bdcff');txt(c,`${i+1}. ${b.v}`,b.x+b.w/2,b.y+44,24)});txt(c,`Correct ${score}/${target} • ${Math.ceil(time)}s`,450,42,22)}}
}

function typingRaceGame(s){
  const a=['FAST','BRAVE','SMART','QUICK','SUPER','HAPPY','LASER','PIXEL','ROBOT','MAGIC'],b=['TYPING','ARCADE','PLAYER','PUZZLE','RACER','CODER','HERO','GAMER'],target=`${a[(s.level*3)%a.length]} ${b[(s.level*5+Math.floor(s.level/8))%b.length]}`,keys='ABCDEFGHIJKLMNOPQRSTUVWXYZ ',buttons=[];let typed='',rival=0;
  for(let i=0;i<keys.length;i++)buttons.push({x:55+(i%9)*88,y:335+Math.floor(i/9)*55,w:78,h:45,ch:keys[i]});
  function input(ch){if(ch==='BACK'){typed=typed.slice(0,-1);return}const expect=target[typed.length];if(ch===expect)typed+=ch;else rival+=.7;if(typed===target)completeLevel(2400-rival*30)}
  return{keyDown(k){if(/^Key[A-Z]$/.test(k))input(k.slice(3));else if(k==='Space')input(' ');else if(k==='Backspace')input('BACK')},pointer(p,t){if(t!=='pointerdown')return;const b=buttons.find(x=>buttonHit(p,x));if(b)input(b.ch)},update(dt){rival+=dt*(1.45+s.level*.018);if(rival>=target.length)failLevel(typed.length*100)},draw(c){bg(c,'#1a2447');txt(c,target,450,115,38,'#dbe8ff');txt(c,typed+'▌',450,190,34,'#56e3a6');rect(c,100,245,700,22,'#26385d');rect(c,100,245,700*typed.length/target.length,22,'#56e3a6');rect(c,100,280,700,16,'#26385d');rect(c,100,280,700*Math.min(1,rival/target.length),16,'#ff6b7d');buttons.forEach(b=>{rect(c,b.x,b.y,b.w,b.h,'#334d7d');txt(c,b.ch===' '?'SPACE':b.ch,b.x+b.w/2,b.y+31,b.ch===' '?13:18)})}}
}

function rhythmGame(s){
  const lanes=[270,390,510,630],keys={KeyD:0,KeyF:1,KeyJ:2,KeyK:3,ArrowLeft:0,ArrowDown:1,ArrowUp:2,ArrowRight:3};let notes=[],spawn=0,created=0,hits=0,miss=0,total=14+Math.min(16,s.level),flash=-1;
  function tap(i){flash=i;setTimeout(()=>flash=-1,80);let best=null,d=60;for(const n of notes){const dd=Math.abs(n.y-440);if(n.lane===i&&dd<d){best=n;d=dd}}if(best){notes.splice(notes.indexOf(best),1);hits++}else miss++}
  return{keyDown(k){if(keys[k]!==undefined)tap(keys[k])},pointer(p,t){if(t==='pointerdown')tap(clamp(Math.floor((p.x-210)/120),0,3))},update(dt){spawn-=dt;if(spawn<=0&&created<total){notes.push({lane:(created*3+s.level)%4,y:60});created++;spawn=.48}for(const n of notes)n.y+=310*dt;for(const n of [...notes])if(n.y>485){notes.splice(notes.indexOf(n),1);miss++}if(created===total&&!notes.length)(hits>=Math.ceil(total*.65)?completeLevel:failLevel)(hits*180)},draw(c){bg(c,'#170f31');for(let i=0;i<4;i++){rect(c,lanes[i]-45,55,90,420,flash===i?'#503ea0':'#2a2450');rect(c,lanes[i]-45,430,90,18,'#65e8ff');txt(c,['D','F','J','K'][i],lanes[i],510,22)}for(const n of notes)circle(c,lanes[n.lane],n.y,24,['#ff5c7f','#5ce6ff','#ffe36a','#7cf08d'][n.lane]);txt(c,`Hits ${hits} • Misses ${miss}`,450,35,21)}}
}

function sequencerGame(s){
  const R=4,C=8,target=Array.from({length:R},(_,r)=>Array.from({length:C},(_,c)=>(c+r*2+s.level)%5===0)),g=Array.from({length:R},()=>Array(C).fill(false));let play=false,step=0,timer=0;
  function check(){if(g.every((r,i)=>r.every((v,j)=>v===target[i][j])))completeLevel(2300)}
  return{keyDown(k){if(k==='Space')play=!play;if(k==='Enter')check()},pointer(p,t){if(t!=='pointerdown')return;const cell=68,ox=178,oy=130,r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(g[r]?.[c]!==undefined){g[r][c]=!g[r][c];check()}},update(dt){if(play){timer+=dt;if(timer>.25){timer=0;step=(step+1)%C}}},draw(c){bg(c,'#11273b');const cell=68,ox=178,oy=130;for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,ox+col*cell+3,oy+r*cell+3,cell-6,cell-6,g[r][col]?'#4fd9b8':'#263f55',step===col?'#ffe06d':'');if(target[r][col])circle(c,ox+(col+.5)*cell,oy+(r+.5)*cell,7,'#ff8dd5')}txt(c,'Match the pink target dots • Space plays the loop',450,75,20)}}
}

function paintNumbersGame(s){
  const N=8,rng=seedForLevel(s,610),style=(s.level-1)%8,pattern=Array.from({length:N},(_,r)=>Array.from({length:N},(_,c)=>{const x=c-3.5,y=r-3.5;switch(style){case 0:return 1+((r<4?0:2)+(c<4?0:1))%4;case 1:return 1+(Math.floor((Math.abs(x)+Math.abs(y)))%4);case 2:return 1+((r+c)%4);case 3:return 1+((r*2+c*3+s.level)%4);case 4:return 1+(Math.floor(Math.hypot(x,y)*1.5)%4);case 5:return 1+((r===c||r+c===7)?3:(r<4?0:1));case 6:return 1+((Math.floor(r/2)+Math.floor(c/2))%4);default:return 1+seededInt(rng,0,3)}})),filled=Array.from({length:N},()=>Array(N).fill(0)),colors=['','#ff6b7b','#52c8ff','#ffe067','#65dc8b'];let color=1;const cell=48,ox=258,oy=70;
  function done(){return filled.every((r,i)=>r.every((v,j)=>v===pattern[i][j]))}
  return{keyDown(k){if(k==='Space'||k==='Enter')color=color%4+1},pointer(p,t){if(t!=='pointerdown')return;if(p.y>470){color=clamp(Math.floor((p.x-270)/90)+1,1,4);return}const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(pattern[r]?.[c]===color){filled[r][c]=color;if(done())completeLevel(2500)}},draw(c){bg(c,'#f5f0e6');for(let r=0;r<N;r++)for(let col=0;col<N;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,filled[r][col]?colors[filled[r][col]]:'#fff','#9b9288');if(!filled[r][col])txt(c,pattern[r][col],ox+(col+.5)*cell,oy+(r+.68)*cell,18,'#6a625b')}for(let i=1;i<=4;i++){circle(c,270+(i-1)*90,495,25,colors[i],color===i?'#111':'');txt(c,i,270+(i-1)*90,502,16,'#111')}}}
}

function jigsawGame(s){
  const pieces=Array.from({length:9},(_,i)=>({id:i,x:60+(i%5)*125,y:420+Math.floor(i/5)*55,drag:false,dx:0,dy:0,placed:false}));let drag=null;const cell=120,ox=270,oy=70;
  return{pointer(p,t){if(t==='pointerdown'){for(const q of [...pieces].reverse())if(!q.placed&&p.x>=q.x&&p.x<=q.x+90&&p.y>=q.y&&p.y<=q.y+90){drag=q;q.dx=p.x-q.x;q.dy=p.y-q.y;break}}else if(t==='pointermove'&&drag){drag.x=p.x-drag.dx;drag.y=p.y-drag.dy}else if(t==='pointerup'&&drag){const tr=Math.floor(drag.id/3),tc=drag.id%3,tx=ox+tc*cell,ty=oy+tr*cell;if(Math.hypot(drag.x-tx,drag.y-ty)<75){drag.x=tx;drag.y=ty;drag.placed=true}drag=null;if(pieces.every(q=>q.placed))completeLevel(2500)}},draw(c){bg(c,'#203455');for(let r=0;r<3;r++)for(let col=0;col<3;col++)rect(c,ox+col*cell,oy+r*cell,90,90,'#15263f','#7ebee4');for(const q of pieces){rect(c,q.x,q.y,90,90,`hsl(${q.id*40} 72% 60%)`,'#fff');txt(c,q.id+1,q.x+45,q.y+57,26)}}}
}

function slidingGame(s){
  const N=4,g=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,0];let blank=15,moves=0;for(let i=0;i<70+s.level;i++){const r=Math.floor(blank/N),c=blank%N,opts=[];for(const[dR,dC]of[[1,0],[-1,0],[0,1],[0,-1]]){const rr=r+dR,cc=c+dC;if(rr>=0&&rr<N&&cc>=0&&cc<N)opts.push(rr*N+cc)}const q=opts[Math.floor(Math.random()*opts.length)];[g[blank],g[q]]=[g[q],g[blank]];blank=q}const cell=105,ox=240,oy=70;
  function move(i){const r=Math.floor(i/N),c=i%N,br=Math.floor(blank/N),bc=blank%N;if(Math.abs(r-br)+Math.abs(c-bc)!==1)return;[g[i],g[blank]]=[g[blank],g[i]];blank=i;moves++;if(g.every((v,i)=>v===(i+1)%16))completeLevel(2400-moves*10)}
  return{pointer(p,t){if(t==='pointerdown')move(Math.floor((p.y-oy)/cell)*N+Math.floor((p.x-ox)/cell))},keyDown(k){const d=keyDirection(k);if(!d)return;const br=Math.floor(blank/N),bc=blank%N;move((br-d[1])*N+(bc-d[0]))},draw(c){bg(c,'#322544');for(let i=0;i<16;i++){const r=Math.floor(i/N),col=i%N;if(g[i]){rect(c,ox+col*cell+4,oy+r*cell+4,cell-8,cell-8,'#6e55a3');txt(c,g[i],ox+(col+.5)*cell,oy+(r+.65)*cell,30)}}txt(c,`Moves ${moves}`,450,38,21)}}
}

function pipesGame(s){
  const R=6,C=8,cell=58,ox=218,oy=90,tiles=Array.from({length:R},()=>Array(C).fill(null)),templates=[[[2,0],[2,1],[2,2],[2,3],[3,3],[4,3],[4,4],[4,5],[5,5]],[[1,0],[1,1],[2,1],[3,1],[3,2],[3,3],[2,3],[2,4],[2,5],[3,5],[4,5],[5,5]],[[4,0],[4,1],[3,1],[2,1],[2,2],[2,3],[3,3],[4,3],[4,4],[4,5],[5,5]],[[0,0],[0,1],[1,1],[1,2],[1,3],[2,3],[3,3],[3,4],[3,5],[4,5],[5,5]]],path=templates[(s.level-1)%templates.length],rng=seedForLevel(s,715);
  const dir=(a,b)=>[b[0]-a[0],b[1]-a[1]],code=d=>d[0]===-1?'U':d[0]===1?'D':d[1]===-1?'L':'R';
  for(let i=0;i<path.length;i++){const [r,c]=path[i],prev=i?code(dir(path[i],path[i-1])):'L',next=i<path.length-1?code(dir(path[i],path[i+1])):'D',pair=[prev,next].sort().join('');let kind,target;if(pair==='LR'){kind='straight';target=0}else if(pair==='DU'){kind='straight';target=1}else{kind='elbow';target={'RU':0,'DL':1,'DR':2,'LU':3}[pair]}tiles[r][c]={kind,target,rot:seededInt(rng,0,3)}}
  function normalized(t){return t.kind==='straight'?t.rot%2:t.rot%4}function check(){return tiles.every(row=>row.every(t=>!t||normalized(t)===t.target))}
  function drawPipe(c,x,y,t){const r=normalized(t),cx=x+cell/2,cy=y+cell/2;c.strokeStyle='#5ce5ff';c.lineWidth=12;c.lineCap='round';c.beginPath();if(t.kind==='straight'){if(r===0){c.moveTo(x+4,cy);c.lineTo(x+cell-4,cy)}else{c.moveTo(cx,y+4);c.lineTo(cx,y+cell-4)}}else{const ends=[[[0,-1],[1,0]],[[-1,0],[0,1]],[[0,1],[-1,0]],[[1,0],[0,-1]]][r];c.moveTo(cx+ends[0][0]*(cell/2-4),cy+ends[0][1]*(cell/2-4));c.lineTo(cx,cy);c.lineTo(cx+ends[1][0]*(cell/2-4),cy+ends[1][1]*(cell/2-4))}c.stroke();c.lineCap='butt'}
  return{pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),col=Math.floor((p.x-ox)/cell),tile=tiles[r]?.[col];if(tile){tile.rot=(tile.rot+1)%4;if(check())completeLevel(2200)}},draw(c){bg(c,'#15313b');for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,'#244852','#102c34');if(tiles[r][col])drawPipe(c,ox+col*cell,oy+r*cell,tiles[r][col])}circle(c,ox-10,oy+(path[0][0]+.5)*cell,12,'#4bdcff');const end=path.at(-1);circle(c,ox+(end[1]+.5)*cell,oy+R*cell+8,12,'#4ee58b');txt(c,'Rotate every pipe in the level-specific route',450,50,19)}}
}

function laserGame(s){
  const n=(s.level-1)%40;let code=(n*73)%600;const sr=code%6;code=Math.floor(code/6);const c1=1+(code%2);code=Math.floor(code/2);const r2Choices=[0,1,2,3,4,5].filter(r=>r!==sr),r2=r2Choices[code%5];code=Math.floor(code/5);const c2=3+(code%2);code=Math.floor(code/2);const r3Choices=[0,1,2,3,4,5].filter(r=>r!==r2),r3=r3Choices[code%5],target=[r3,6],required=[];
  const turnRightToVertical=(from,to)=>to>from?false:true,turnVerticalToRight=(from,to)=>to>from?false:true;
  required.push({r:sr,c:c1,slash:turnRightToVertical(sr,r2)});required.push({r:r2,c:c1,slash:turnVerticalToRight(sr,r2)});required.push({r:r2,c:c2,slash:turnRightToVertical(r2,r3)});required.push({r:r3,c:c2,slash:turnVerticalToRight(r2,r3)});
  const occupied=new Set(required.map(m=>`${m.r},${m.c}`));occupied.add(`${target[0]},${target[1]}`);const rng=seedForLevel(s,812),mirrors=required.map(m=>({...m,slash:rng()<.5}));while(mirrors.length<6){const r=seededInt(rng,0,5),c=seededInt(rng,1,5),k=`${r},${c}`;if(!occupied.has(k)){occupied.add(k);mirrors.push({r,c,slash:rng()<.5,decoy:true})}}
  const cell=70,ox=240,oy=70;let path=[],hitTarget=false;
  function trace(){path=[];let r=sr,c=-1,dr=0,dc=1;for(let k=0;k<80;k++){c+=dc;r+=dr;path.push([r,c]);if(r===target[0]&&c===target[1]){hitTarget=true;return}if(r<0||r>=6||c<0||c>=7)break;const m=mirrors.find(x=>x.r===r&&x.c===c);if(m){if(m.slash)[dr,dc]=[-dc,-dr];else [dr,dc]=[dc,dr]}}hitTarget=false}
  trace();return{pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell),m=mirrors.find(x=>x.r===r&&x.c===c);if(m){m.slash=!m.slash;trace();if(hitTarget)completeLevel(2500)}},draw(c){bg(c,'#0b1025');for(let r=0;r<6;r++)for(let col=0;col<7;col++)rect(c,ox+col*cell,oy+r*cell,cell,cell,'#151d38','#2c3f68');for(const m of mirrors)txt(c,m.slash?'/':'\\',ox+(m.c+.5)*cell,oy+(m.r+.72)*cell,48,m.decoy?'#9ca9c0':'#dce8ff');c.strokeStyle='#ff4868';c.lineWidth=5;c.beginPath();path.forEach((z,i)=>{const x=ox+(z[1]+.5)*cell,y=oy+(z[0]+.5)*cell;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();circle(c,ox+(target[1]+.5)*cell,oy+(target[0]+.5)*cell,18,hitTarget?'#58e58a':'#ffcf4a');txt(c,`Level ${s.level}: rotate mirrors to hit the receiver`,450,45,20)}}
}

function tangramGame(s){
  const base=[{x:320,y:110,w:120,h:80},{x:470,y:110,w:80,h:120},{x:590,y:110,w:100,h:100},{x:340,y:260,w:100,h:100},{x:490,y:270,w:120,h:70},{x:640,y:260,w:70,h:120},{x:500,y:380,w:100,h:80}],variant=(s.level-1)%8,rng=seedForLevel(s,907),targets=base.map((t,i)=>{const mirror=variant&1,shift=((variant>>1)*17+i*11)%45,jx=seededInt(rng,-20,20),jy=seededInt(rng,-14,14);return{x:clamp((mirror?780-t.x-t.w:t.x+(i%2?shift:-shift)*.35)+jx,250,730-t.w),y:clamp(t.y+((variant+i)%3-1)*18+jy,80,430-t.h),w:t.w*(1+((variant+i)%3-1)*.08),h:t.h*(1+((variant+i*2)%3-1)*.08)}}),pieces=targets.map((t,i)=>({x:35+(i%4)*125,y:400+Math.floor(i/4)*65,w:t.w*.65,h:t.h*.65,id:i,placed:false}));let drag=null;
  return{pointer(p,t){if(t==='pointerdown'){drag=[...pieces].reverse().find(q=>!q.placed&&buttonHit(p,q));if(drag){drag.dx=p.x-drag.x;drag.dy=p.y-drag.y}}else if(t==='pointermove'&&drag){drag.x=p.x-drag.dx;drag.y=p.y-drag.dy}else if(t==='pointerup'&&drag){const z=targets[drag.id];if(Math.hypot(drag.x-z.x,drag.y-z.y)<70){Object.assign(drag,{x:z.x,y:z.y,w:z.w,h:z.h,placed:true})}drag=null;if(pieces.every(q=>q.placed))completeLevel(2400)}},draw(c){bg(c,'#25203a');targets.forEach(t=>rect(c,t.x,t.y,t.w,t.h,'#ffffff12','#fff6'));pieces.forEach((q,i)=>rect(c,q.x,q.y,q.w,q.h,`hsl(${i*51} 75% 60%)`));txt(c,`Level ${s.level}: fit every shape into its matching outline`,450,45,20)}}
}

function nonogramGame(s){
  const patterns=[['01110','10101','11111','01110','00100'],['10001','01010','00100','01010','10001'],['00100','01110','11111','10101','00100'],['11011','11011','00000','10101','01110'],['11111','10001','10101','10001','11111'],['01010','11111','01110','11111','01010'],['10001','11011','11111','01110','00100'],['00100','10101','01110','10101','00100'],['11100','10100','11100','00101','00111'],['10010','01001','00100','10010','01001']],base=patterns[(s.level-1)%patterns.length].map(r=>[...r].map(Number)),variant=Math.floor((s.level-1)/patterns.length)%4,rot=a=>a[0].map((_,c)=>a.map(r=>r[c]).reverse()),sol=variant===0?base:variant===1?rot(base):variant===2?base.map(r=>[...r].reverse()):base.map(r=>r.map(v=>1-v)),g=Array.from({length:5},()=>Array(5).fill(0));let mode=1;const cell=70,ox=310,oy=120;const clue=a=>{let o=[],n=0;for(const v of a){if(v)n++;else if(n){o.push(n);n=0}}if(n)o.push(n);return o.join(' ')||'0'};
  function check(){if(g.every((r,i)=>r.every((v,j)=>(v===1)===(sol[i][j]===1))))completeLevel(2400)}
  return{keyDown(k){if(k==='Space'||k==='Enter')mode=mode===1?2:1},pointer(p,t){if(t!=='pointerdown')return;const r=Math.floor((p.y-oy)/cell),c=Math.floor((p.x-ox)/cell);if(g[r]?.[c]!==undefined){g[r][c]=g[r][c]===mode?0:mode;check()}},draw(c){bg(c,'#e8edf2');for(let r=0;r<5;r++){txt(c,clue(sol[r]),ox-18,oy+(r+.65)*cell,18,'#24364b','right');for(let col=0;col<5;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,g[r][col]===1?'#293c55':'#fff','#6b7a8c');if(g[r][col]===2)txt(c,'×',ox+(col+.5)*cell,oy+(r+.68)*cell,30,'#bd5969')}}for(let col=0;col<5;col++)txt(c,clue(sol.map(r=>r[col])),ox+(col+.5)*cell,oy-18,18,'#24364b');txt(c,mode===1?'FILL mode':'X mode',450,55,20,'#24364b')}}
}

function mastermindGame(s){
  const colors=['#f05267','#48c8ff','#ffe061','#5ce18b','#b578ff','#ff9d4c'],code=Array.from({length:4},()=>Math.floor(Math.random()*6));let current=[0,0,0,0],slot=0,rows=[];
  function submit(){let exact=0,partial=0,usedC=[],usedG=[];for(let i=0;i<4;i++)if(current[i]===code[i]){exact++;usedC.push(i);usedG.push(i)}for(let i=0;i<4;i++)if(!usedG.includes(i)){const j=code.findIndex((v,k)=>v===current[i]&&!usedC.includes(k));if(j>=0){partial++;usedC.push(j)}}rows.push({guess:current.slice(),exact,partial});if(exact===4)return completeLevel(2600-rows.length*100);if(rows.length>=8)return failLevel(0);current=[0,0,0,0];slot=0}
  return{keyDown(k){if(k==='ArrowLeft')slot=(slot+3)%4;if(k==='ArrowRight')slot=(slot+1)%4;if(k==='ArrowUp')current[slot]=(current[slot]+1)%6;if(k==='Enter'||k==='Space')submit()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>450){const i=Math.floor((p.x-225)/75);if(i>=0&&i<6){current[slot]=i;slot=(slot+1)%4}}else if(p.y>370)submit()},draw(c){bg(c,'#17273b');rows.slice(-5).forEach((r,ri)=>{r.guess.forEach((v,i)=>circle(c,300+i*70,90+ri*55,20,colors[v]));txt(c,`● ${r.exact}  ○ ${r.partial}`,650,98+ri*55,18)});current.forEach((v,i)=>circle(c,300+i*70,380,24,colors[v],i===slot?'#fff':''));rect(c,620,350,150,55,'#4d76a2');txt(c,'SUBMIT',695,386,18);colors.forEach((v,i)=>circle(c,250+i*75,485,24,v));txt(c,'Black = exact • White = wrong position',450,45,18)}}
}

function codeBreakerGame(s){
  const code=[1+Math.floor(Math.random()*8),1+Math.floor(Math.random()*8),1+Math.floor(Math.random()*8)],guess=[1,1,1];let selected=0,attempts=[];
  function submit(){const exact=guess.filter((v,i)=>v===code[i]).length,sum=guess.reduce((a,b)=>a+b,0),even=guess.filter(v=>v%2===0).length;attempts.push({g:guess.slice(),exact,sum,even});if(exact===3)return completeLevel(2500-attempts.length*120);if(attempts.length>=7)failLevel(0)}
  return{keyDown(k){if(k==='ArrowLeft')selected=(selected+2)%3;if(k==='ArrowRight')selected=(selected+1)%3;if(k==='ArrowUp')guess[selected]=guess[selected]%9+1;if(k==='ArrowDown')guess[selected]=(guess[selected]+7)%9+1;if(k==='Space'||k==='Enter')submit()},pointer(p,t){if(t!=='pointerdown')return;if(p.y<300){selected=clamp(Math.floor((p.x-300)/100),0,2);guess[selected]=guess[selected]%9+1}else submit()},draw(c){bg(c,'#281d34');guess.forEach((v,i)=>{rect(c,300+i*100,120,80,100,i===selected?'#8a5cb5':'#49375d');txt(c,v,340+i*100,185,48)});rect(c,330,260,240,55,'#b45a7c');txt(c,'TEST CODE',450,297,20);attempts.slice(-4).forEach((a,i)=>txt(c,`${a.g.join('')} • exact ${a.exact} • sum ${a.sum} • evens ${a.even}`,450,365+i*36,18));txt(c,'Use the clues to deduce all three digits',450,50,20)}}
}

function yahtzeeGame(s){
  let dice=[1,1,1,1,1],held=[false,false,false,false,false],rolls=0,round=1,total=0;const target=55+Math.floor(s.level*2);
  function roll(){if(rolls>=3)return;for(let i=0;i<5;i++)if(!held[i])dice[i]=1+Math.floor(Math.random()*6);rolls++}function score(){const counts=Array(7).fill(0);dice.forEach(v=>counts[v]++);const sum=dice.reduce((a,b)=>a+b,0),best=Math.max(sum,Math.max(...counts)*10,counts.some(x=>x>=4)?40:0,counts.some(x=>x===5)?50:0);total+=best;round++;rolls=0;held.fill(false);if(round>5)(total>=target?completeLevel:failLevel)(total*30);else roll()}roll();
  return{keyDown(k){if(k==='Space')roll();if(k==='Enter')score()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>160&&p.y<270){const i=Math.floor((p.x-230)/90);if(i>=0&&i<5)held[i]=!held[i]}else if(p.x<450)roll();else score()},draw(c){bg(c,'#0d543d');dice.forEach((v,i)=>{rect(c,230+i*90,170,70,70,held[i]?'#ffe06b':'#fff','#111');txt(c,v,265+i*90,220,32,'#111')});rect(c,210,330,210,60,'#2579b8');rect(c,480,330,210,60,'#a54875');txt(c,'ROLL',315,370,22);txt(c,'SCORE',585,370,22);txt(c,`Round ${round}/5 • Rolls ${rolls}/3 • Total ${total}/${target}`,450,55,22)}}
}

function solitaireGame(s){
  const suits=['♥','♠','♦','♣'],red=x=>x==='♥'||x==='♦';let deck=[];for(const suit of suits)for(let rank=1;rank<=4;rank++)deck.push({suit,rank});deck.sort(()=>Math.random()-.5);const piles=[[],[],[],[]];deck.forEach((c,i)=>piles[i%4].push(c));const foundations={'♥':0,'♠':0,'♦':0,'♣':0};let selected=null;
  function tapPile(i){const p=piles[i];if(!p.length)return;const card=p[p.length-1];if(foundations[card.suit]===card.rank-1){foundations[card.suit]++;p.pop()}else if(selected===null)selected=i;else{const from=piles[selected],m=from[from.length-1],dest=piles[i],top=dest[dest.length-1];if(selected!==i&&(!top||(top.rank===m.rank+1&&red(top.suit)!==red(m.suit))))dest.push(from.pop());selected=null}if(Object.values(foundations).every(v=>v===4))completeLevel(2600)}
  return{pointer(p,t){if(t==='pointerdown'){const i=Math.floor((p.x-170)/145);if(i>=0&&i<4)tapPile(i)}},draw(c){bg(c,'#07523b');suits.forEach((suit,i)=>{rect(c,160+i*145,70,90,110,'#ffffff18','#fff');txt(c,`${suit}${foundations[suit]||''}`,205+i*145,135,30,red(suit)?'#ff7082':'#fff')});piles.forEach((pile,i)=>pile.forEach((card,j)=>{rect(c,170+i*145,220+j*28,90,110,'#fff',selected===i&&j===pile.length-1?'#ffe06b':'#111');txt(c,`${card.suit}${card.rank}`,215+i*145,270+j*28,24,red(card.suit)?'#d33':'#111')}));txt(c,'Move A→4 of each suit to the foundations',450,45,19)}}
}

function warGame(s){
  let player=Array.from({length:12},()=>2+Math.floor(Math.random()*13)),cpu=Array.from({length:12},()=>2+Math.floor(Math.random()*13)),round=0,ps=0,cs=0,last=null;
  function reveal(){if(round>=12)return;const a=player[round],b=cpu[round];if(a>b)ps++;else if(b>a)cs++;else{ps+=.5;cs+=.5}last=[a,b];round++;if(round===12)setTimeout(()=>((ps>cs)?completeLevel:failLevel)(ps*200),300)}
  return{keyDown(k){if(k==='Space'||k==='Enter')reveal()},pointer(p,t){if(t==='pointerdown')reveal()},draw(c){bg(c,'#4b1730');txt(c,'YOU',280,100,24);txt(c,'CPU',620,100,24);if(last){drawCard(c,245,150,last[0],true);drawCard(c,585,150,last[1],true)}rect(c,330,390,240,65,'#8f3d69');txt(c,'REVEAL',450,433,22);txt(c,`Round ${round}/12 • ${ps}–${cs}`,450,55,22)}}
}

function goFishGame(s){
  const ranks=['A','2','3','4','5','6'],deck=[];for(let r=0;r<6;r++)for(let k=0;k<4;k++)deck.push(r);deck.sort(()=>Math.random()-.5);let hand=deck.splice(0,5),cpu=deck.splice(0,5),books=0,cpuBooks=0;
  function collect(h){for(let r=0;r<6;r++)if(h.filter(x=>x===r).length===4){for(let k=0;k<4;k++)h.splice(h.indexOf(r),1);return 1}return 0}function ask(r){if(!hand.includes(r))return;const got=cpu.filter(x=>x===r);if(got.length){cpu=cpu.filter(x=>x!==r);hand.push(...got)}else if(deck.length)hand.push(deck.pop());books+=collect(hand);setTimeout(ai,250);finish()}function ai(){if(!cpu.length&&deck.length)cpu.push(deck.pop());if(!cpu.length)return;const r=cpu[Math.floor(Math.random()*cpu.length)],got=hand.filter(x=>x===r);if(got.length){hand=hand.filter(x=>x!==r);cpu.push(...got)}else if(deck.length)cpu.push(deck.pop());cpuBooks+=collect(cpu);finish()}function finish(){if((!deck.length&&!hand.length)||books+cpuBooks===6)(books>cpuBooks?completeLevel:failLevel)(books*500)}
  return{pointer(p,t){if(t!=='pointerdown')return;const groups=[...new Set(hand)].sort();const i=Math.floor((p.x-170)/100);if(groups[i]!==undefined)ask(groups[i])},draw(c){bg(c,'#125b70');txt(c,`Your books ${books} • Computer books ${cpuBooks} • Pond ${deck.length}`,450,55,22);const groups=[...new Set(hand)].sort();groups.forEach((r,i)=>{rect(c,170+i*100,350,80,110,'#fff','#111');txt(c,ranks[r],210+i*100,410,32,'#153');txt(c,`×${hand.filter(x=>x===r).length}`,210+i*100,445,16,'#153')});txt(c,'Tap a rank to ask the computer',450,300,20)}}
}

function diceRaceGame(s){
  const pos=[0,0],cpu=[0],finish=30;let roll=0,choose=0,waiting=true;
  function rollDie(){if(!waiting)return;roll=1+Math.floor(Math.random()*6);waiting=false}function move(){if(waiting||!roll)return;pos[choose]=Math.min(finish,pos[choose]+roll+(pos[choose]===9||pos[choose]===19?3:0));cpu[0]=Math.min(finish,cpu[0]+1+Math.floor(Math.random()*6));roll=0;waiting=true;if(pos.every(x=>x>=finish))completeLevel(2500);else if(cpu[0]>=finish)failLevel(0)}
  return{keyDown(k){if(k==='Space')waiting?rollDie():move();if(k==='ArrowLeft'||k==='ArrowRight')choose=1-choose},pointer(p,t){if(t!=='pointerdown')return;if(p.y>420){if(waiting)rollDie();else move()}else choose=p.y<250?0:1},draw(c){bg(c,'#e8d8ae');for(let i=0;i<=finish;i++){const x=70+(i%10)*76,y=90+Math.floor(i/10)*95;rect(c,x,y,68,68,i===9||i===19?'#ffe06b':'#fff','#886');txt(c,i,x+34,y+43,16,'#443')}for(let i=0;i<2;i++)circle(c,104+(pos[i]%10)*76,110+Math.floor(pos[i]/10)*95+i*16,12,i===choose?'#31cfff':'#206da0');circle(c,104+(cpu[0]%10)*76,145+Math.floor(cpu[0]/10)*95,12,'#ff5c74');rect(c,330,445,240,55,'#7c5a31');txt(c,waiting?'ROLL DIE':`MOVE TOKEN ${choose+1} (${roll})`,450,482,20)}}
}

function dotsBoxesGame(s){
  const R=4,C=5,ox=250,oy=100,cell=90,h=new Set(),v=new Set(),boxes=Array.from({length:R-1},()=>Array(C-1).fill(0)),two=s.mode==='2P';let turn=1,selected=null,score=[0,0,0],busy=false;
  function edgeKey(a,b){return `${Math.min(a[0],b[0])},${Math.min(a[1],b[1])}-${Math.max(a[0],b[0])},${Math.max(a[1],b[1])}`}
  function boxDone(r,c){return h.has(edgeKey([r,c],[r,c+1]))&&h.has(edgeKey([r+1,c],[r+1,c+1]))&&v.has(edgeKey([r,c],[r+1,c]))&&v.has(edgeKey([r,c+1],[r+1,c+1]))}
  function allEdges(){const out=[];for(let r=0;r<R;r++)for(let c=0;c<C-1;c++)out.push([[r,c],[r,c+1]]);for(let r=0;r<R-1;r++)for(let c=0;c<C;c++)out.push([[r,c],[r+1,c]]);return out}
  function used(a,b){return (a[0]===b[0]?h:v).has(edgeKey(a,b))}
  function addEdge(a,b){const key=edgeKey(a,b),set=a[0]===b[0]?h:v;if(set.has(key))return false;set.add(key);let gained=false;for(let br=0;br<R-1;br++)for(let bc=0;bc<C-1;bc++)if(!boxes[br][bc]&&boxDone(br,bc)){boxes[br][bc]=turn;score[turn]++;gained=true}if(h.size+v.size===R*(C-1)+(R-1)*C){busy=true;(score[1]>=score[2]?completeLevel:failLevel)(score[1]*400);return true}if(!gained)turn=3-turn;if(!two&&turn===2&&!busy){busy=true;setTimeout(ai,220)}return true}
  function point(r,c){if(busy||(!two&&turn===2))return;if(selected===null){selected=[r,c];return}if(Math.abs(r-selected[0])+Math.abs(c-selected[1])!==1){selected=[r,c];return}const a=selected,b=[r,c];selected=null;addEdge(a,b)}
  function ai(){if(s.completed)return;const open=allEdges().filter(([a,b])=>!used(a,b));if(!open.length)return;let best=open[0],bestScore=-99;for(const edge of open){const[a,b]=edge,key=edgeKey(a,b),set=a[0]===b[0]?h:v;set.add(key);let made=0,risk=0;for(let r=0;r<R-1;r++)for(let c=0;c<C-1;c++){const n=[h.has(edgeKey([r,c],[r,c+1])),h.has(edgeKey([r+1,c],[r+1,c+1])),v.has(edgeKey([r,c],[r+1,c])),v.has(edgeKey([r,c+1],[r+1,c+1]))].filter(Boolean).length;if(!boxes[r][c]&&n===4)made++;else if(!boxes[r][c]&&n===3)risk++}set.delete(key);const value=made*20-risk+Math.random()*.1;if(value>bestScore){bestScore=value;best=edge}}busy=false;addEdge(best[0],best[1]);if(!s.completed&&turn===2){busy=true;setTimeout(ai,180)}}
  return{pointer(p,t){if(t!=='pointerdown')return;const c=Math.round((p.x-ox)/cell),r=Math.round((p.y-oy)/cell);if(r>=0&&r<R&&c>=0&&c<C)point(r,c)},draw(c){bg(c,'#f0e4ca');for(let r=0;r<R-1;r++)for(let col=0;col<C-1;col++)if(boxes[r][col])rect(c,ox+col*cell+8,oy+r*cell+8,cell-16,cell-16,boxes[r][col]===1?'#72d9ff':'#ff8ca2');c.strokeStyle='#533';c.lineWidth=6;for(const key of[...h,...v]){const[a,b]=key.split('-').map(x=>x.split(',').map(Number));c.beginPath();c.moveTo(ox+a[1]*cell,oy+a[0]*cell);c.lineTo(ox+b[1]*cell,oy+b[0]*cell);c.stroke()}for(let r=0;r<R;r++)for(let col=0;col<C;col++)circle(c,ox+col*cell,oy+r*cell,7,'#332');txt(c,two?`Player ${turn} • ${score[1]}–${score[2]}`:busy?'Computer thinking…':`You ${score[1]} • Computer ${score[2]}`,450,55,22,'#332')}}
}

function mancalaGame(s){
  let pits=[4,4,4,4,4,4,0,4,4,4,4,4,4,0],turn=0;const two=s.mode==='2P';
  function moveAllowed(i){return turn===0?i>=0&&i<=5:i>=7&&i<=12}
  function sow(i){if(!moveAllowed(i)||!pits[i])return;let stones=pits[i],who=turn;pits[i]=0;while(stones){i=(i+1)%14;if((who===0&&i===13)||(who===1&&i===6))continue;pits[i]++;stones--}const ownStore=who===0?6:13,ownPit=who===0?(i>=0&&i<6):(i>=7&&i<13),opposite=12-i;if(ownPit&&pits[i]===1&&pits[opposite]>0){pits[ownStore]+=pits[opposite]+1;pits[opposite]=pits[i]=0}if(i!==ownStore)turn=1-turn;if(end())return;if(!two&&turn===1)setTimeout(ai,250)}
  function ai(){const choices=[7,8,9,10,11,12].filter(i=>pits[i]);if(!choices.length)return end(true);const best=choices.sort((a,b)=>{const sa=(a+pits[a])%14===13?2:0,sb=(b+pits[b])%14===13?2:0;return sb-sa})[0];sow(best)}
  function end(force=false){if(force||pits.slice(0,6).every(x=>x===0)||pits.slice(7,13).every(x=>x===0)){pits[6]+=pits.slice(0,6).reduce((a,b)=>a+b,0);pits[13]+=pits.slice(7,13).reduce((a,b)=>a+b,0);pits.fill(0,0,6);pits.fill(0,7,13);(pits[6]>=pits[13]?completeLevel:failLevel)(pits[6]*100);return true}return false}
  return{pointer(p,t){if(t!=='pointerdown')return;const i=Math.floor((p.x-190)/85);if(p.y>320)sow(i);else if(two)sow(12-i)},draw(c){bg(c,'#9a653b');rect(c,120,120,660,300,'#c58b54','#6e4327');for(let i=0;i<6;i++){circle(c,215+i*85,350,32,'#7c4b2d');txt(c,pits[i],215+i*85,359,20);circle(c,215+(5-i)*85,190,32,'#7c4b2d');txt(c,pits[7+i],215+(5-i)*85,199,20)}rect(c,135,160,55,220,'#71432b');rect(c,710,160,55,220,'#71432b');txt(c,pits[13],162,280,24);txt(c,pits[6],737,280,24);txt(c,two?`Player ${turn+1} turn`:turn===0?'Your turn':'Computer turn',450,55,22)}}
}

function morrisGame(s){
  const pts=[[1,1],[4,1],[7,1],[2,2],[4,2],[6,2],[3,3],[4,3],[5,3],[1,4],[2,4],[3,4],[5,4],[6,4],[7,4],[3,5],[4,5],[5,5],[2,6],[4,6],[6,6],[1,7],[4,7],[7,7]],adj=[[1,9],[0,2,4],[1,14],[4,10],[1,3,5,7],[4,13],[7,11],[4,6,8],[7,12],[0,10,21],[3,9,11,18],[6,10,15],[8,13,17],[5,12,14,20],[2,13,23],[11,16],[15,17,19],[12,16],[10,19],[16,18,20,22],[13,19],[9,22],[19,21,23],[14,22]],mills=[[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14],[15,16,17],[18,19,20],[21,22,23],[0,9,21],[3,10,18],[6,11,15],[1,4,7],[16,19,22],[8,12,17],[5,13,20],[2,14,23]];let board=Array(24).fill(0),placed=[0,0,0],turn=1,sel=null,remove=false;
  const forms=(i,w)=>mills.some(m=>m.includes(i)&&m.every(x=>board[x]===w));function click(i){if(turn!==1)return;if(remove){if(board[i]===2){board[i]=0;remove=false;turn=2;setTimeout(ai,250)}return}if(placed[1]<9){if(board[i])return;board[i]=1;placed[1]++;if(forms(i,1))remove=true;else{turn=2;setTimeout(ai,250)}}else if(sel===null){if(board[i]===1)sel=i}else if(board[i]===0&&adj[sel].includes(i)){board[i]=1;board[sel]=0;sel=null;if(forms(i,1))remove=true;else{turn=2;setTimeout(ai,250)}}check()}function ai(){let empt=board.map((v,i)=>v?null:i).filter(i=>i!==null),i;if(placed[2]<9){i=empt[Math.floor(Math.random()*empt.length)];board[i]=2;placed[2]++}else{const moves=[];board.forEach((v,a)=>{if(v===2)adj[a].forEach(b=>{if(!board[b])moves.push([a,b])})});if(!moves.length)return completeLevel(2500);const m=moves[Math.floor(Math.random()*moves.length)];board[m[1]]=2;board[m[0]]=0;i=m[1]}if(forms(i,2)){const choices=board.map((v,j)=>v===1?j:null).filter(j=>j!==null);if(choices.length)board[choices[Math.floor(Math.random()*choices.length)]]=0}turn=1;check()}function check(){const a=board.filter(x=>x===1).length,b=board.filter(x=>x===2).length;if(placed[1]>=9&&a<3)failLevel(0);if(placed[2]>=9&&b<3)completeLevel(2500)}
  return{pointer(p,t){if(t!=='pointerdown')return;let best=-1,d=28;pts.forEach((q,i)=>{const dd=Math.hypot(p.x-(140+q[0]*75),p.y-(20+q[1]*62));if(dd<d){d=dd;best=i}});if(best>=0)click(best)},draw(c){bg(c,'#34251c');c.strokeStyle='#d9b98c';c.lineWidth=4;for(const m of mills){c.beginPath();m.forEach((i,k)=>{const q=pts[i],x=140+q[0]*75,y=20+q[1]*62;k?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}pts.forEach((q,i)=>circle(c,140+q[0]*75,20+q[1]*62,16,board[i]===1?'#eee':board[i]===2?'#222':'#9b7657',sel===i?'#5ee7ff':''));txt(c,remove?'Remove an enemy piece':placed[1]<9?'Place a piece':'Move along a line',450,38,20)}}
}

function gomokuGame(s){
  const N=15,g=Array.from({length:N},()=>Array(N).fill(0)),cell=29,ox=247,oy=70,two=s.mode==='2P';let turn=1,busy=false;
  function win(w){for(let r=0;r<N;r++)for(let c=0;c<N;c++)for(const[dR,dC]of[[1,0],[0,1],[1,1],[1,-1]])if([0,1,2,3,4].every(k=>g[r+dR*k]?.[c+dC*k]===w))return true;return false}
  function finish(w){if(!win(w))return false;(w===1||two?completeLevel:failLevel)(2500);return true}
  function ai(){const empty=[];for(let rr=0;rr<N;rr++)for(let cc=0;cc<N;cc++)if(!g[rr][cc])empty.push([rr,cc]);for(const who of[2,1])for(const q of empty){g[q[0]][q[1]]=who;const ok=win(who);g[q[0]][q[1]]=0;if(ok){g[q[0]][q[1]]=2;busy=false;finish(2);return}}const near=empty.filter(([rr,cc])=>g.slice(Math.max(0,rr-1),rr+2).some(row=>row.slice(Math.max(0,cc-1),cc+2).some(Boolean))),q=(near.length?near:empty)[Math.floor(Math.random()*(near.length||empty.length))];if(q)g[q[0]][q[1]]=2;busy=false;finish(2)}
  function play(r,c){if(busy||r<0||r>=N||c<0||c>=N||g[r][c])return;g[r][c]=turn;if(finish(turn))return;if(two)turn=3-turn;else{busy=true;setTimeout(ai,180)}}
  return{pointer(p,t){if(t==='pointerdown')play(Math.round((p.y-oy)/cell),Math.round((p.x-ox)/cell))},draw(c){bg(c,'#d8aa63');for(let i=0;i<N;i++){c.strokeStyle='#6c4b28';c.beginPath();c.moveTo(ox,oy+i*cell);c.lineTo(ox+(N-1)*cell,oy+i*cell);c.stroke();c.beginPath();c.moveTo(ox+i*cell,oy);c.lineTo(ox+i*cell,oy+(N-1)*cell);c.stroke()}for(let r=0;r<N;r++)for(let col=0;col<N;col++)if(g[r][col])circle(c,ox+col*cell,oy+r*cell,11,g[r][col]===1?'#fff':'#111');txt(c,two?`Player ${turn} turn`:busy?'Computer thinking…':'Your turn',450,38,20,'#4a321c')}}
}

function hexGame(s){
  const N=9,g=Array.from({length:N},()=>Array(N).fill(0)),rad=23,ox=270,oy=95,two=s.mode==='2P';let turn=1,busy=false;const neigh=[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,1]];
  function connected(w){const q=[],seen=new Set();if(w===1){for(let r=0;r<N;r++)if(g[r][0]===1){q.push([r,0]);seen.add(`${r},0`)}}else for(let c=0;c<N;c++)if(g[0][c]===2){q.push([0,c]);seen.add(`0,${c}`)}while(q.length){const[r,c]=q.shift();if((w===1&&c===N-1)||(w===2&&r===N-1))return true;for(const[dR,dC]of neigh){const rr=r+dR,cc=c+dC,k=`${rr},${cc}`;if(g[rr]?.[cc]===w&&!seen.has(k)){seen.add(k);q.push([rr,cc])}}}return false}
  function finish(w){if(!connected(w))return false;(w===1||two?completeLevel:failLevel)(2600);return true}
  function ai(){const empty=[];for(let rr=0;rr<N;rr++)for(let cc=0;cc<N;cc++)if(!g[rr][cc])empty.push([rr,cc]);const q=empty.sort((a,b)=>Math.abs(a[0]-4)-Math.abs(b[0]-4))[Math.floor(Math.random()*Math.min(8,empty.length))]||empty[0];if(q)g[q[0]][q[1]]=2;busy=false;finish(2)}
  function play(r,c){if(busy||r<0||r>=N||c<0||c>=N||g[r][c])return;g[r][c]=turn;if(finish(turn))return;if(two)turn=3-turn;else{busy=true;setTimeout(ai,180)}}function center(r,c){return[ox+c*rad*1.75+r*rad*.88,oy+r*rad*1.52]}
  return{pointer(p,t){if(t!=='pointerdown')return;let best=null,d=rad;for(let r=0;r<N;r++)for(let c=0;c<N;c++){const q=center(r,c),dd=Math.hypot(p.x-q[0],p.y-q[1]);if(dd<d){d=dd;best=[r,c]}}if(best)play(...best)},draw(c){bg(c,'#18314a');for(let r=0;r<N;r++)for(let col=0;col<N;col++){const[x,y]=center(r,col);circle(c,x,y,rad-3,g[r][col]===1?'#5bdcff':g[r][col]===2?'#ff627b':'#d7e1eb','#506981')}txt(c,two?`Player ${turn} • Blue left–right • Red top–bottom`:'Blue connects left–right • Computer red',450,45,19)}}
}

function dominoesGame(s){
  let tiles=[];for(let a=0;a<=6;a++)for(let b=a;b<=6;b++)tiles.push([a,b]);tiles.sort(()=>Math.random()-.5);let hand=tiles.splice(0,7),cpu=tiles.splice(0,7),chain=[tiles.pop()],selected=null,turnLocked=false,passes=0;const ends=()=>[chain[0][0],chain[chain.length-1][1]];
  function orient(tile,end,left){if(tile[1]===end)return left?tile:[tile[1],tile[0]];if(tile[0]===end)return left?[tile[1],tile[0]]:tile;return null}function playable(h){const e=ends();return h.some(t=>orient(t,e[0],true)||orient(t,e[1],false))}function finishBlocked(){if(passes<2)return false;const a=hand.flat().reduce((x,y)=>x+y,0),b=cpu.flat().reduce((x,y)=>x+y,0);(a<=b?completeLevel:failLevel)(Math.max(0,2500-a*50));return true}
  function play(i,left){if(turnLocked||!hand[i])return;const e=ends()[left?0:1],o=orient(hand[i],e,left);if(!o)return toast('That tile does not match this end');if(left)chain.unshift(o);else chain.push(o);hand.splice(i,1);passes=0;selected=null;if(!hand.length)return completeLevel(2500);turnLocked=true;setTimeout(ai,240)}
  function drawOrPass(){if(turnLocked)return;if(playable(hand))return toast('You already have a playable tile');if(tiles.length){hand.push(tiles.pop());toast('Drew one tile');if(!playable(hand))passes++;else passes=0}else{passes++;toast('Pass')}if(finishBlocked())return;turnLocked=true;setTimeout(ai,240)}
  function ai(){let safety=20;while(safety--){const e=ends();let move=null;for(let i=0;i<cpu.length&&!move;i++)for(const left of[true,false]){const o=orient(cpu[i],e[left?0:1],left);if(o){move=[i,left,o];break}}if(move){const[i,left,o]=move;if(left)chain.unshift(o);else chain.push(o);cpu.splice(i,1);passes=0;if(!cpu.length)return failLevel(0);break}if(tiles.length){cpu.push(tiles.pop());continue}passes++;break}turnLocked=false;finishBlocked()}
  function drawTile(c,t,x,y,sel){rect(c,x,y,70,40,'#f7f1df',sel?'#5ee7ff':'#332');c.strokeStyle='#332';c.beginPath();c.moveTo(x+35,y);c.lineTo(x+35,y+40);c.stroke();txt(c,t[0],x+17,y+28,18,'#222');txt(c,t[1],x+53,y+28,18,'#222')}
  return{keyDown(k){if(k==='Enter'||k==='Space')drawOrPass()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>420&&p.x<730){const i=Math.floor((p.x-85)/85);if(hand[i])selected=i}else if(p.y>430&&p.x>735)drawOrPass();else if(selected!==null)play(selected,p.x<450)},draw(c){bg(c,'#315b43');let x=100;chain.slice(-9).forEach(t=>{drawTile(c,t,x,220,false);x+=78});hand.forEach((t,i)=>drawTile(c,t,85+i*85,440,i===selected));rect(c,745,435,125,55,'#d4a64d');txt(c,tiles.length?'DRAW':'PASS',807,471,18,'#18291f');txt(c,`Open ends ${ends()[0]} and ${ends()[1]} • CPU ${cpu.length} • Boneyard ${tiles.length}`,450,55,20);txt(c,'Select a tile and tap a table side, or Draw/Pass when blocked',450,390,17)}}
}

function volleyballGame(s){
  const p1={x:180,y:430,vx:0,vy:0,score:0},p2={x:720,y:430,vx:0,vy:0,score:0},ball={x:450,y:145,vx:185,vy:0},two=s.mode==='2P';const ground=470;let rallyTime=0,stallTime=0,lastX=ball.x,lastY=ball.y,serveDelay=.8;
  function jump(p){if(p.y>=429)p.vy=-470}
  function reset(dir){Object.assign(ball,{x:dir>0?260:640,y:135,vx:175*dir,vy:-55});p1.y=p2.y=430;p1.vy=p2.vy=0;rallyTime=0;stallTime=0;serveDelay=.7}
  function hitBall(p,power=1){const dx=ball.x-p.x,dy=ball.y-(p.y-22),d=Math.hypot(dx,dy)||1;if(d<62){const attack=p===p1?1:-1;ball.vx=attack*(210+Math.min(180,Math.abs(dx)*3))*power;ball.vy=-Math.max(300,Math.abs(ball.vy)*.72+225)*power;ball.x=p.x+attack*32;ball.y=p.y-62;stallTime=0;return true}return false}
  return{pointer(q,t){if(t!=='pointerdown'&&t!=='pointermove')return;const player=(!two||q.x<W/2)?p1:p2;player.x=clamp(q.x,player===p1?35:485,player===p1?415:865);if(t==='pointerdown'||q.y<player.y-45)jump(player)},keyDown(k){if(k==='Space'||k==='ArrowUp')jump(p1);if(two&&(k==='KeyF'||k==='KeyW'))jump(p2)},update(dt){if(serveDelay>0){serveDelay-=dt;return}rallyTime+=dt;const v=285;if(s.pressed('ArrowLeft'))p1.x-=v*dt;if(s.pressed('ArrowRight'))p1.x+=v*dt;if(two){if(s.pressed('KeyA'))p2.x-=v*dt;if(s.pressed('KeyD'))p2.x+=v*dt}else{const timeToGround=Math.max(.15,(430-ball.y)/Math.max(120,ball.vy+330)),predicted=clamp(ball.x+ball.vx*timeToGround,500,850),attackTarget=ball.x>450?predicted:610;p2.x+=clamp(attackTarget-p2.x,-v*1.08*dt,v*1.08*dt);if(ball.x>455&&ball.y>210&&ball.y<410&&Math.abs(ball.x-p2.x)<105&&p2.y>=429)jump(p2);if(ball.x>455&&ball.y>285&&Math.abs(ball.x-p2.x)<85)hitBall(p2,1.12)}p1.x=clamp(p1.x,35,415);p2.x=clamp(p2.x,485,865);for(const p of[p1,p2]){p.vy+=900*dt;p.y+=p.vy*dt;if(p.y>430){p.y=430;p.vy=0}hitBall(p)}ball.vy+=650*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(!Number.isFinite(ball.x+ball.y)){reset(Math.random()<.5?-1:1);return}if(ball.x<15){ball.x=15;ball.vx=Math.abs(ball.vx)}if(ball.x>885){ball.x=885;ball.vx=-Math.abs(ball.vx)}if(ball.x>438&&ball.x<462&&ball.y>245){ball.x=ball.x<450?437:463;ball.vx=ball.x<450?-Math.max(120,Math.abs(ball.vx)*.9):Math.max(120,Math.abs(ball.vx)*.9)}const moved=Math.hypot(ball.x-lastX,ball.y-lastY);stallTime=moved<1.2?stallTime+dt:0;lastX=ball.x;lastY=ball.y;if(stallTime>.65||rallyTime>16){ball.x=ball.x<450?400:500;ball.vx=ball.x<450?230:-230;ball.vy=-320;ball.y=Math.min(ball.y,350);stallTime=0;rallyTime=0}if(ball.y>ground){if(ball.x<450)p2.score++;else p1.score++;reset(ball.x<450?-1:1)}if(p1.score>=7||p2.score>=7)(p1.score>p2.score?completeLevel:failLevel)(p1.score*400)},draw(c){bg(c,'#7bd1ff');rect(c,0,470,W,70,'#e9c47f');rect(c,443,250,14,220,'#fff');rect(c,p1.x-22,p1.y-45,44,45,'#4bdcff');rect(c,p2.x-22,p2.y-45,44,45,'#ff5f7d');circle(c,ball.x,ball.y,14,'#fff','#235');txt(c,`${p1.score} — ${p2.score}${two?'':' • attacking CPU'} • Rally ${Math.floor(rallyTime)}s`,450,45,24,'#16334e')}}
}

function airHockeyGame(s){
  const p1={x:200,y:270,r:28},p2={x:700,y:270,r:28},puck={x:450,y:270,r:16,vx:0,vy:0},score=[0,0,0],two=s.mode==='2P';let still=0;
  function reset(){Object.assign(puck,{x:450,y:270,vx:rand(-40,40),vy:rand(-30,30)});still=0}
  return{pointer(q,t){if(t!=='pointerdown'&&t!=='pointermove')return;const player=(!two||q.x<W/2)?p1:p2;player.x=clamp(q.x,player===p1?35:480,player===p1?420:865);player.y=clamp(q.y,85,H-35)},update(dt){const v=350;if(s.pressed('ArrowLeft'))p1.x-=v*dt;if(s.pressed('ArrowRight'))p1.x+=v*dt;if(s.pressed('ArrowUp'))p1.y-=v*dt;if(s.pressed('ArrowDown'))p1.y+=v*dt;if(two){if(s.pressed('KeyA'))p2.x-=v*dt;if(s.pressed('KeyD'))p2.x+=v*dt;if(s.pressed('KeyW'))p2.y-=v*dt;if(s.pressed('KeyS'))p2.y+=v*dt}else{const targetX=puck.x>430?clamp(puck.x+55,500,835):610,targetY=clamp(puck.y+puck.vy*.18,95,495),speed=puck.x>440?v*1.05:v*.85;p2.x+=clamp(targetX-p2.x,-speed*dt,speed*dt);p2.y+=clamp(targetY-p2.y,-speed*dt,speed*dt)}p1.x=clamp(p1.x,40,425);p2.x=clamp(p2.x,475,860);for(const player of[p1,p2]){player.y=clamp(player.y,85,500);const d=Math.hypot(puck.x-player.x,puck.y-player.y);if(d<player.r+puck.r){const nx=(puck.x-player.x)/(d||1),ny=(puck.y-player.y)/(d||1);puck.x=player.x+nx*(player.r+puck.r);puck.y=player.y+ny*(player.r+puck.r);puck.vx=nx*(player===p2?500:455);puck.vy=ny*(player===p2?500:455)}}puck.x+=puck.vx*dt;puck.y+=puck.vy*dt;puck.vx*=Math.pow(.4,dt);puck.vy*=Math.pow(.4,dt);if(!Number.isFinite(puck.x+puck.y)){reset();return}if(puck.y<75+puck.r){puck.y=75+puck.r;puck.vy=Math.abs(puck.vy)*.9}if(puck.y>H-puck.r){puck.y=H-puck.r;puck.vy=-Math.abs(puck.vy)*.9}if(puck.x<0&&puck.y>210&&puck.y<330){score[2]++;reset()}else if(puck.x>W&&puck.y>210&&puck.y<330){score[1]++;reset()}else{if(puck.x<puck.r){puck.x=puck.r;puck.vx=Math.abs(puck.vx)*.9}if(puck.x>W-puck.r){puck.x=W-puck.r;puck.vx=-Math.abs(puck.vx)*.9}}if(Math.hypot(puck.vx,puck.vy)<8)still+=dt;else still=0;if(still>1.6){puck.vx=puck.x<450?190:-190;puck.vy=rand(-90,90);still=0}if(score[1]>=5||score[2]>=5)(score[1]>score[2]?completeLevel:failLevel)(score[1]*500)},draw(c){bg(c,'#d9f5ff');c.strokeStyle='#2c7ba4';c.lineWidth=6;c.strokeRect(15,65,W-30,H-80);c.beginPath();c.arc(450,300,75,0,7);c.stroke();c.strokeRect(0,210,55,120);c.strokeRect(845,210,55,120);circle(c,p1.x,p1.y,p1.r,'#34bce8');circle(c,p2.x,p2.y,p2.r,'#ef5571');circle(c,puck.x,puck.y,puck.r,'#222');txt(c,`${score[1]} — ${score[2]}${two?'':' • attacking CPU'}`,450,42,26,'#17445d')}}
}

function bowlingGame(s){
  let aim=0,power=0,setting=false,balls=2,score=0,frame=1,pins=[];function resetPins(){pins=[];for(let r=0;r<4;r++)for(let i=0;i<=r;i++)pins.push({x:450+(i-r/2)*34,y:120+r*32,up:true})}resetPins();function action(){if(!setting){setting=true;power=0}else{const accuracy=Math.max(0,1-Math.abs(aim)/4),force=power;let knocked=0;for(const pin of pins)if(pin.up&&Math.random()<accuracy*force*.95){pin.up=false;knocked++}score+=knocked;balls--;setting=false;if(!pins.some(p=>p.up)||balls===0){frame++;if(frame>5)return(score>=25?completeLevel:failLevel)(score*100);balls=2;resetPins()}}}
  return{keyDown(k){if(k==='ArrowLeft')aim=Math.max(-3,aim-1);if(k==='ArrowRight')aim=Math.min(3,aim+1);if(k==='Space'||k==='Enter')action()},pointer(p,t){if(t==='pointerdown'){aim=clamp(Math.round((p.x-450)/80),-3,3);action()}},update(dt){if(setting)power=(Math.sin(performance.now()/230)+1)/2},draw(c){bg(c,'#2c5070');rect(c,260,60,380,480,'#d7aa65');for(const pin of pins)if(pin.up){circle(c,pin.x,pin.y,12,'#fff');rect(c,pin.x-7,pin.y,pin.x?14:14,25,'#fff')}c.strokeStyle='#ff5b6f';c.lineWidth=5;c.beginPath();c.moveTo(450,500);c.lineTo(450+aim*40,360);c.stroke();rect(c,300,465,300,20,'#233');rect(c,300,465,300*power,20,'#54de89');txt(c,`Frame ${frame}/5 • Balls ${balls} • Score ${score}`,450,40,21)}}
}

function fishingGame(s){
  let state='ready',wait=0,tension=50,fish=0,total=0,target=8+Math.floor(s.level/2),safe=50;
  function action(){if(state==='ready'){state='waiting';wait=1+Math.random()*2.5}else if(state==='bite'){state='hooked';fish=2+Math.random()*4}else if(state==='hooked')tension+=8}
  return{keyDown(k){if(k==='Space'||k==='Enter')action();if(k==='ArrowLeft')tension-=5;if(k==='ArrowRight')tension+=5},pointer(p,t){if(t==='pointerdown')action()},update(dt){if(state==='waiting'){wait-=dt;if(wait<=0){state='bite';wait=1}}else if(state==='bite'){wait-=dt;if(wait<=0)state='ready'}else if(state==='hooked'){safe=50+Math.sin(performance.now()/500)*22;tension+=(safe-tension)*dt*.7;tension-=dt*2;if(tension<10||tension>90){state='ready';tension=50}else{fish-=dt*(1-Math.abs(tension-safe)/60);if(fish<=0){const w=1+Math.floor(Math.random()*4);total+=w;state='ready';tension=50;if(total>=target)completeLevel(total*250)}}}},draw(c){bg(c,'#78c8e9');rect(c,0,360,W,180,'#1679a5');txt(c,state==='ready'?'CAST':state==='waiting'?'Waiting…':state==='bite'?'BITE! TAP NOW':'REEL! Keep tension in green',450,80,28,'#16324a');rect(c,200,430,500,30,'#26394d');rect(c,200+safe*5-60,430,120,30,'#51db83');rect(c,200+tension*5-5,420,10,50,'#ffe05c');txt(c,`Catch weight ${total}/${target}`,450,330,22,'#fff')}}
}

function cookingGame(s){
  const ingredients=['🍞','🥬','🍅','🧀','🥩','🍳'],orders=[[0,1,2],[0,4,3],[5,2,3],[0,1,4,2]],buttons=ingredients.map((v,i)=>({x:130+i*110,y:360,w:90,h:75,i}));let order=orders[(s.level-1)%orders.length],made=[],served=0,time=40,target=4+Math.floor(s.level/5);
  function tap(i){made.push(i);if(made.some((v,k)=>v!==order[k])){made=[];time-=3}}function serve(){if(made.length===order.length&&made.every((v,i)=>v===order[i])){served++;made=[];order=orders[Math.floor(Math.random()*orders.length)];if(served>=target)completeLevel(served*450)}else{made=[];time-=4}}
  return{keyDown(k){if(k==='Enter'||k==='Space')serve()},pointer(p,t){if(t!=='pointerdown')return;const b=buttons.find(x=>buttonHit(p,x));if(b)tap(b.i);else if(p.y>460)serve()},update(dt){time-=dt;if(time<=0)failLevel(served*200)},draw(c){bg(c,'#5a2f2a');txt(c,'ORDER',450,75,24);txt(c,order.map(i=>ingredients[i]).join('  '),450,145,44);txt(c,'PLATE',450,230,22);txt(c,made.map(i=>ingredients[i]).join('  ')||'—',450,290,42);buttons.forEach(b=>{rect(c,b.x,b.y,b.w,b.h,'#f0c685');txt(c,ingredients[b.i],b.x+b.w/2,b.y+52,32)});rect(c,340,465,220,50,'#4ca366');txt(c,'SERVE',450,498,20);txt(c,`${served}/${target} orders • ${Math.ceil(time)}s`,450,35,20)}}
}

function farmGame(s){
  const crops=[{name:'CARROT',icon:'🥕',seed:2,days:2,water:1,value:6},{name:'CORN',icon:'🌽',seed:4,days:3,water:2,value:11},{name:'BERRY',icon:'🍓',seed:6,days:4,water:2,value:17}],plots=Array.from({length:12},()=>({crop:-1,age:0,water:0,ready:false}));let crop=0,tool=0,coins=18,day=1,revenue=0,water=9,target=42+s.level*3,weather='SUN';const tools=['PLANT','WATER','HARVEST'];
  function act(i){const p=plots[i],spec=crops[crop];if(tool===0&&p.crop<0&&coins>=spec.seed){coins-=spec.seed;p.crop=crop;p.age=0;p.water=0;p.ready=false}else if(tool===1&&p.crop>=0&&!p.ready&&water>0){water--;p.water++}else if(tool===2&&p.ready){const q=crops[p.crop],price=Math.round(q.value*(weather==='MARKET BOOM'?1.4:1));coins+=price;revenue+=price;Object.assign(p,{crop:-1,age:0,water:0,ready:false});if(revenue>=target)completeLevel(revenue*90+coins)}}
  function nextDay(){day++;const rng=seedForLevel({level:s.level+day},236);weather=rng()<.18?'RAIN':rng()<.3?'DROUGHT':rng()<.42?'MARKET BOOM':'SUN';if(weather==='RAIN')water+=4;else water+=weather==='DROUGHT'?1:3;water=Math.min(14,water);for(const p of plots)if(p.crop>=0&&!p.ready){const q=crops[p.crop],need=Math.max(0,q.water-(weather==='RAIN'?1:0));if(p.water>=need){p.age++;p.water=0;if(p.age>=q.days)p.ready=true}else p.age=Math.max(0,p.age-1)}if(day>15&&revenue<target)failLevel(revenue*50)}
  return{keyDown(k){if(k==='Space')tool=(tool+1)%3;if(k==='Enter')nextDay();if(k==='ArrowLeft')crop=(crop+2)%3;if(k==='ArrowRight')crop=(crop+1)%3},pointer(p,t){if(t!=='pointerdown')return;if(p.y<410){const c=Math.floor((p.x-210)/120),r=Math.floor((p.y-95)/100),i=r*4+c;if(plots[i])act(i)}else if(p.x<300)crop=(crop+2)%3;else if(p.x<600)tool=(tool+1)%3;else nextDay()},draw(c){bg(c,'#76b95b');plots.forEach((p,i)=>{const x=210+(i%4)*120,y=95+Math.floor(i/4)*100;rect(c,x,y,100,80,'#6d4528','#d3b16e');if(p.crop>=0)txt(c,p.ready?crops[p.crop].icon:(p.water?'🌱💧':'🌱'),x+50,y+53,30)});rect(c,120,430,200,52,'#395f31');txt(c,`${crops[crop].icon} ${crops[crop].name}`,220,464,16);rect(c,340,430,220,52,'#395f31');txt(c,tools[tool],450,464,18);rect(c,580,430,200,52,'#395f31');txt(c,'NEXT DAY',680,464,18);txt(c,`Day ${day}/15 • ${weather} • Coins ${coins} • Water ${water} • Sales ${revenue}/${target}`,450,42,19)}}
}

function petCareGame(s){
  const needs={hunger:75,happy:75,clean:75,energy:75};let time=0;const actions=[['FEED','hunger'],['PLAY','happy'],['WASH','clean'],['SLEEP','energy']];function act(k){needs[k]=Math.min(100,needs[k]+30);for(const q of Object.keys(needs))if(q!==k)needs[q]-=4}
  return{pointer(p,t){if(t!=='pointerdown')return;const i=Math.floor((p.x-170)/145);if(actions[i])act(actions[i][1])},update(dt){time+=dt;for(const k of Object.keys(needs))needs[k]-=dt*(1.1+s.level*.03);if(Object.values(needs).some(v=>v<=0))failLevel(time*100);if(time>=35)completeLevel(Object.values(needs).reduce((a,b)=>a+b,0)*8)},draw(c){bg(c,'#f1d7e8');txt(c,'🐶',450,210,100);Object.entries(needs).forEach(([k,v],i)=>{txt(c,k.toUpperCase(),180,285+i*35,16,'#563b52','left');rect(c,300,268+i*35,400,22,'#c39ab8');rect(c,300,268+i*35,400*clamp(v,0,100)/100,22,['#ff8a72','#65d88d','#62bfff','#a58cff'][i])});actions.forEach((a,i)=>{rect(c,170+i*145,430,125,55,'#815a89');txt(c,a[0],232+i*145,466,17)});txt(c,`Care time ${Math.floor(time)}/35`,450,45,20,'#563b52')}}
}

function cityBuilderGame(s){
  const R=5,C=8,g=Array.from({length:R},()=>Array(C).fill(0)),types=['HOME','SHOP','FACTORY','PARK','POWER','BULLDOZE'],costs=[12,18,24,10,28,0],colors=['#7dc9ff','#ffe06a','#a88b7a','#65d77a','#bd7cff','#555'];let type=0,budget=150,month=1,pop=0,jobs=0,power=0,pollution=0,happy=50,target=55+s.level*3;
  function neighbors(r,c,want){let n=0;for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]])if(g[r+dr]?.[c+dc]===want)n++;return n}
  function recalc(){const counts=Array(7).fill(0);g.flat().forEach(v=>counts[v]++);power=counts[5]*12;const demand=counts[1]*2+counts[2]*2+counts[3]*3,jobs=counts[2]*5+counts[3]*8;pollution=counts[3]*6;let parkBonus=0,factoryPenalty=0;for(let r=0;r<R;r++)for(let c=0;c<C;c++)if(g[r][c]===1){parkBonus+=neighbors(r,c,4)*4;factoryPenalty+=neighbors(r,c,3)*6}happy=clamp(58+parkBonus-factoryPenalty-pollution*.35-Math.max(0,demand-power)*3,0,100);pop=Math.floor(counts[1]*8*Math.min(1,jobs/Math.max(1,counts[1]*5))*happy/70)}
  function place(r,c){if(g[r]?.[c]===undefined)return;if(type===5){if(g[r][c]){budget+=Math.floor(costs[g[r][c]-1]*.35);g[r][c]=0;recalc()}return}if(g[r][c]||budget<costs[type])return;g[r][c]=type+1;budget-=costs[type];recalc()}
  function nextMonth(){recalc();const homes=g.flat().filter(v=>v===1).length,shops=g.flat().filter(v=>v===2).length,factories=g.flat().filter(v=>v===3).length;budget+=shops*5+factories*8-homes*2-Math.max(0,power-(homes*2+shops*2+factories*3));month++;if(pop>=target&&happy>=55&&budget>=0)return completeLevel(pop*60+happy*20+budget);if(month>18||budget<-20)failLevel(Math.max(0,pop*30))}
  return{keyDown(k){if(k==='Space')type=(type+1)%types.length;if(k==='Enter')nextMonth();if(k==='Backspace')type=5},pointer(p,t){if(t!=='pointerdown')return;if(p.y<72){type=clamp(Math.floor(p.x/150),0,5);return}if(p.y>485){nextMonth();return}const r=Math.floor((p.y-90)/75),c=Math.floor((p.x-150)/75);place(r,c)},draw(c){bg(c,'#8fd0ef');types.forEach((q,i)=>{rect(c,i*150,8,148,48,type===i?'#28586f':'#497b8b');txt(c,`${q}${i<5?' $'+costs[i]:''}`,i*150+74,39,14)});for(let r=0;r<R;r++)for(let col=0;col<C;col++){const v=g[r][col];rect(c,150+col*75,90+r*75,68,68,v?colors[v-1]:'#d7e8dc','#496b61');if(v)txt(c,['🏠','🏪','🏭','🌳','⚡'][v-1],184+col*75,135+r*75,24)}rect(c,300,490,300,42,'#295b68');txt(c,'ADVANCE MONTH',450,518,17);txt(c,`Month ${month}/18 • $${budget} • Pop ${pop}/${target} • Jobs ${jobs} • Power ${power} • Happiness ${Math.round(happy)}%`,450,75,17)}}
}

function pinballGame(s){
  const ball={x:700,y:450,r:10,vx:0,vy:0},bumpers=[[330,180],[500,150],[610,260],[390,300]],targets=bumpers.map(()=>true);let balls=3,score=0,launched=false;
  function resetBall(){Object.assign(ball,{x:700,y:450,vx:0,vy:0});launched=false;targets.fill(true)}function launch(){if(!launched){ball.vx=-130;ball.vy=-520;launched=true}}
  return{keyDown(k){if(k==='Space')launch()},pointer(p,t){if(t==='pointerdown')launch()},update(dt){if(!launched)return;ball.vy+=520*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(!Number.isFinite(ball.x+ball.y)){resetBall();return}if(ball.x<130){ball.x=130;ball.vx=Math.abs(ball.vx)*.9}if(ball.x>770){ball.x=770;ball.vx=-Math.abs(ball.vx)*.9}if(ball.y<70){ball.y=70;ball.vy=Math.abs(ball.vy)}for(let i=0;i<bumpers.length;i++){const b=bumpers[i],d=Math.hypot(ball.x-b[0],ball.y-b[1]);if(d<38){const nx=(ball.x-b[0])/(d||1),ny=(ball.y-b[1])/(d||1);ball.x=b[0]+nx*38;ball.y=b[1]+ny*38;ball.vx=nx*330;ball.vy=ny*330-80;if(targets[i]){targets[i]=false;score+=500}}}const left=s.pressed('ArrowLeft','KeyA'),right=s.pressed('ArrowRight','KeyD');if(ball.y>410&&ball.y<500&&((left&&ball.x<450)||(right&&ball.x>450))){ball.y=Math.min(ball.y,468);ball.vy=-460;ball.vx+=(ball.x<450?120:-120)}if(ball.y>H+20){balls--;if(!balls)return(score>=1500?completeLevel:failLevel)(score);resetBall()}if(score>=2500+s.level*100)completeLevel(score)},draw(c){bg(c,'#21113e');c.strokeStyle='#7be8ff';c.lineWidth=8;c.strokeRect(120,60,660,470);bumpers.forEach((b,i)=>circle(c,b[0],b[1],30,targets[i]?'#ff5f8a':'#555','#fff'));circle(c,ball.x,ball.y,ball.r,'#fff');c.strokeStyle='#ffe06a';c.lineWidth=10;c.beginPath();c.moveTo(250,470);c.lineTo(420,500);c.moveTo(650,470);c.lineTo(480,500);c.stroke();txt(c,`Score ${score} • Balls ${balls} • tap to launch`,450,38,21)}}
}

function match3Game(s){
  const R=8,C=8,K=6,colors=['#ff5f7b','#53cfff','#ffe05e','#64db86','#a877ff','#ff9e4c'];let selected=null,moves=20,score=0,target=800+s.level*40,cell=52,ox=242,oy=70,g;
  function matches(board=g){const set=new Set();for(let r=0;r<R;r++)for(let c=0;c<C;c++){if(c<C-2&&board[r][c]===board[r][c+1]&&board[r][c]===board[r][c+2])for(let k=c;k<C&&board[r][k]===board[r][c];k++)set.add(`${r},${k}`);if(r<R-2&&board[r][c]===board[r+1][c]&&board[r][c]===board[r+2][c])for(let k=r;k<R&&board[k][c]===board[r][c];k++)set.add(`${k},${c}`)}return set}
  function hasMove(){for(let r=0;r<R;r++)for(let c=0;c<C;c++)for(const[dr,dc]of[[1,0],[0,1]]){const nr=r+dr,nc=c+dc;if(nr>=R||nc>=C)continue;[g[r][c],g[nr][nc]]=[g[nr][nc],g[r][c]];const ok=matches().size>0;[g[r][c],g[nr][nc]]=[g[nr][nc],g[r][c]];if(ok)return true}return false}
  function makeBoard(){const rng=seedForLevel(s,258);do{g=Array.from({length:R},(_,r)=>Array.from({length:C},(_,c)=>{let v;do v=Math.floor(rng()*K);while((c>1&&g?.[r]?.[c-1]===v&&g[r][c-2]===v)||(r>1&&g?.[r-1]?.[c]===v&&g[r-2][c]===v));return v}))}while(!hasMove())}makeBoard();
  function resolve(){let cascades=0;while(cascades++<12){const m=matches();if(!m.size)break;score+=m.size*50*cascades;for(const q of m){const[r,c]=q.split(',').map(Number);g[r][c]=-1}for(let c=0;c<C;c++){const vals=[];for(let r=R-1;r>=0;r--)if(g[r][c]>=0)vals.push(g[r][c]);for(let r=R-1,i=0;r>=0;r--,i++)g[r][c]=i<vals.length?vals[i]:Math.floor(Math.random()*K)}}if(!hasMove())makeBoard();return cascades>1}
  function choose(r,c){if(r<0||r>=R||c<0||c>=C)return;if(selected===null){selected=[r,c];return}if(Math.abs(r-selected[0])+Math.abs(c-selected[1])!==1){selected=[r,c];return}const[a,b]=selected;[g[a][b],g[r][c]]=[g[r][c],g[a][b]];if(!matches().size)[g[a][b],g[r][c]]=[g[r][c],g[a][b]];else{moves--;resolve()}selected=null;if(score>=target)completeLevel(score);else if(moves<=0)failLevel(score)}
  return{pointer(p,t){if(t==='pointerdown')choose(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell))},draw(c){bg(c,'#402052');for(let r=0;r<R;r++)for(let col=0;col<C;col++)circle(c,ox+(col+.5)*cell,oy+(r+.5)*cell,21,colors[g[r][col]],selected&&selected[0]===r&&selected[1]===col?'#fff':'');txt(c,`Score ${score}/${target} • Moves ${moves} • No free starting matches`,450,38,20)}}
}

function robotCodeGame(s){
  const R=6,C=8,rng=seedForLevel(s,1021),map=Array.from({length:R},(_,r)=>Array.from({length:C},(_,c)=>(r===0||c===0||r===R-1||c===C-1)?'#':' '));for(let r=1;r<R-1;r++)for(let c=1;c<C-1;c++)if(rng()<.34)map[r][c]='#';const start={r:1,c:1,d:1},battery={r:1+seededInt(rng,0,R-3),c:1+seededInt(rng,1,C-3)},goal={r:R-2,c:C-2};if(battery.r===start.r&&battery.c===start.c)battery.c=3;
  function carve(a,b,hFirst){let r=a.r,c=a.c;map[r][c]=' ';const horizontal=()=>{while(c!==b.c){c+=Math.sign(b.c-c);map[r][c]=' '}};const vertical=()=>{while(r!==b.r){r+=Math.sign(b.r-r);map[r][c]=' '}};hFirst?(horizontal(),vertical()):(vertical(),horizontal())}
  carve(start,battery,s.level%2===0);carve(battery,goal,s.level%3===0);map[battery.r][battery.c]='B';map[goal.r][goal.c]='G';const program=[];let robot={...start},running=false,pc=0,timer=0,collected=false;const cmds=['MOVE','LEFT','RIGHT'],limit=20+Math.floor(s.level/8);
  function add(i){if(program.length<limit)program.push(i)}function run(){robot={...start};pc=0;collected=false;running=true}function step(){if(pc>=program.length){running=false;return}const cmd=program[pc++];if(cmd===1)robot.d=(robot.d+3)%4;else if(cmd===2)robot.d=(robot.d+1)%4;else{const dirs=[[-1,0],[0,1],[1,0],[0,-1]],d=dirs[robot.d],nr=robot.r+d[0],nc=robot.c+d[1];if(map[nr]?.[nc]!=='#'){robot.r=nr;robot.c=nc;if(map[nr][nc]==='B')collected=true;if(map[nr][nc]==='G'&&collected){running=false;completeLevel(2800-program.length*40)}}}}
  return{keyDown(k){if(k==='Space')run();if(k==='Enter'||k==='Backspace')program.pop()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>430){const i=Math.floor((p.x-170)/150);if(i<3)add(i);else if(i===3)run();else program.pop()}},update(dt){if(running){timer+=dt;if(timer>.35){timer=0;step()}}},draw(c){bg(c,'#18283b');const cell=65,ox=190,oy=65;for(let r=0;r<map.length;r++)for(let col=0;col<map[r].length;col++){rect(c,ox+col*cell,oy+r*cell,cell,cell,map[r][col]==='#'?'#34475a':'#d7e4ea','#758695');if(map[r][col]==='B'&&!collected)txt(c,'⚡',ox+(col+.5)*cell,oy+(r+.68)*cell,28);if(map[r][col]==='G')txt(c,'★',ox+(col+.5)*cell,oy+(r+.68)*cell,28,'#5bdc82')}txt(c,['▲','▶','▼','◀'][robot.d],ox+(robot.c+.5)*cell,oy+(robot.r+.68)*cell,30,'#ff5e7b');['MOVE','LEFT','RIGHT','RUN','UNDO'].forEach((v,i)=>{rect(c,170+i*150,440,130,50,'#3b5d7a');txt(c,v,235+i*150,473,16)});txt(c,`${program.map(i=>cmds[i]).join(' → ')||'Program is empty'}  (${program.length}/${limit})`,450,415,18)}}
}
