'use strict';

/* Version 11 adds 25 distinct games, bringing the catalog to 100. */
Object.assign(window.EXTRA_GAME_FACTORIES||={}, {
  trafficcontrol:trafficControlGame,powergrid:powerGridGame,factoryflow:factoryFlowGame,rescuedispatch:rescueDispatchGame,
  spacecolony:spaceColonyGame,ecobalance:ecoBalanceGame,harborlogistics:harborLogisticsGame,castlecommand:castleCommandGame,
  gravityflip:gravityFlipGame,colordash:colorDashGame,orbitdefender:orbitDefenderGame,caveexplorer:caveExplorerGame,
  treasuremap:treasureMapGame,signalswitch:signalSwitchGame,conveyorsort:conveyorSortGame,dronedelivery:droneDeliveryGame,
  submarinesonar:submarineSonarGame,snowboardslalom:snowboardSlalomGame,tabletennis:tableTennisGame,wordladder:wordLadderGame,
  cipherlab:cipherLabGame,fractionforge:fractionForgeGame,melodymemory:melodyMemoryGame,beatbuilder:beatBuilderGame,meteorminer:meteorMinerGame
});

function trafficControlGame(s){
  const cars=[],lanes=[{x:450,y:-35,dx:0,dy:1},{x:935,y:270,dx:-1,dy:0},{x:450,y:575,dx:0,dy:-1},{x:-35,y:270,dx:1,dy:0}];let ns=true,spawn=.5,passed=0,crashes=0,time=45,target=18+Math.floor(s.level/2);
  function toggle(){ns=!ns}function green(i){return i%2===0?ns:!ns}
  return{keyDown(k){if(k==='Space'||k==='Enter')toggle()},pointer(p,t){if(t==='pointerdown')toggle()},update(dt){time-=dt;spawn-=dt;if(spawn<=0){const lane=(passed+cars.length+s.level)%4,q=lanes[lane];cars.push({lane,x:q.x,y:q.y,dx:q.dx,dy:q.dy,wait:0});spawn=Math.max(.45,1.15-s.level*.012)}for(const car of cars){const near=Math.abs(car.x-450)<105&&Math.abs(car.y-270)<105;if(near&&!green(car.lane)){car.wait+=dt;if(car.wait>5)return failLevel(passed*80);continue}const v=105+Math.min(75,s.level*2);car.x+=car.dx*v*dt;car.y+=car.dy*v*dt}for(let i=0;i<cars.length;i++)for(let j=i+1;j<cars.length;j++)if(Math.hypot(cars[i].x-cars[j].x,cars[i].y-cars[j].y)<28&&cars[i].lane%2!==cars[j].lane%2){crashes++;return failLevel(passed*80)}for(const car of [...cars])if(car.x<-60||car.x>960||car.y<-60||car.y>600){cars.splice(cars.indexOf(car),1);passed++;if(passed>=target)completeLevel(2500+Math.ceil(time)*20)}if(time<=0)failLevel(passed*80)},draw(c){bg(c,'#2c6a45');rect(c,360,0,180,H,'#454b55');rect(c,0,180,W,180,'#454b55');c.strokeStyle='#f7e16b';c.setLineDash([20,18]);c.beginPath();c.moveTo(450,0);c.lineTo(450,H);c.moveTo(0,270);c.lineTo(W,270);c.stroke();c.setLineDash([]);for(const car of cars)rect(c,car.x-16,car.y-10,32,20,car.lane%2?'#ff667e':'#58ddff');circle(c,335,155,12,ns?'#62e78a':'#ff5e67');circle(c,565,385,12,ns?'#62e78a':'#ff5e67');circle(c,565,155,12,!ns?'#62e78a':'#ff5e67');circle(c,335,385,12,!ns?'#62e78a':'#ff5e67');txt(c,`Traffic ${passed}/${target} • ${Math.ceil(time)}s • Tap/Space switches lights`,450,38,20)}}
}

function powerGridGame(s){
  const N=6,cell=66,ox=252,oy=75,rng=seedForLevel(s,760),g=Array.from({length:N},()=>Array(N).fill(0)),cities=[],plants=[];let budget=75,wire=0;for(let i=0;i<3+Math.floor(s.level/12);i++){let r,c;do{r=seededInt(rng,0,N-1);c=seededInt(rng,0,N-1)}while(g[r][c]);g[r][c]=2;cities.push([r,c])}for(let i=0;i<2;i++){let r,c;do{r=seededInt(rng,0,N-1);c=seededInt(rng,0,N-1)}while(g[r][c]);g[r][c]=3;plants.push([r,c])}
  function connectedCity(r,c){const q=[[r,c]],seen=new Set([`${r},${c}`]);while(q.length){const[a,b]=q.shift();if(g[a][b]===3)return true;for(const[dr,dc]of[[1,0],[-1,0],[0,1],[0,-1]]){const nr=a+dr,nc=b+dc,key=`${nr},${nc}`;if(nr>=0&&nr<N&&nc>=0&&nc<N&&!seen.has(key)&&(g[nr][nc]===1||g[nr][nc]===2||g[nr][nc]===3)){seen.add(key);q.push([nr,nc])}}}return false}
  function place(r,c){if(g[r]?.[c]!==0||budget<3)return;g[r][c]=1;budget-=3;wire++;const powered=cities.filter(q=>connectedCity(q[0],q[1])).length;if(powered===cities.length&&wire>=cities.length)completeLevel(2600+budget*10)}
  return{pointer(p,t){if(t==='pointerdown')place(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell))},keyDown(k){if(k==='Backspace'){for(let r=N-1;r>=0;r--)for(let c=N-1;c>=0;c--)if(g[r][c]===1){g[r][c]=0;budget+=2;wire--;return}}},draw(c){bg(c,'#172841');for(let r=0;r<N;r++)for(let col=0;col<N;col++){const v=g[r][col];rect(c,ox+col*cell,oy+r*cell,cell-4,cell-4,v===1?'#f0cf54':v===2?(connectedCity(r,col)?'#55dc87':'#e45b67'):v===3?'#a477ff':'#2c4564','#7890aa');if(v===2)txt(c,'🏙️',ox+(col+.5)*cell,oy+(r+.68)*cell,26);if(v===3)txt(c,'⚡',ox+(col+.5)*cell,oy+(r+.68)*cell,26)}txt(c,`Budget ${budget} • Connect every city to a plant • Backspace removes last wire`,450,40,19)}}
}

function factoryFlowGame(s){
  const R=6,C=9,cell=55,ox=202,oy=82,rng=seedForLevel(s,790),g=Array.from({length:R},()=>Array.from({length:C},()=>seededInt(rng,0,3))),parts=[];let spawn=.3,delivered=0,lost=0,target=12+Math.floor(s.level/3);g[2][0]=1;g[3][C-1]=3;
  const dirs=[[1,0],[0,1],[-1,0],[0,-1]];function rotate(r,c){if(g[r]?.[c]!==undefined)g[r][c]=(g[r][c]+1)%4}
  return{pointer(p,t){if(t==='pointerdown')rotate(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell))},update(dt){spawn-=dt;if(spawn<=0){parts.push({r:2,c:0,progress:0});spawn=.8}for(const q of parts){q.progress+=dt*(2.2+s.level*.02);if(q.progress<1)continue;q.progress=0;const[dC,dR]=dirs[g[q.r][q.c]],nr=q.r+dR,nc=q.c+dC;if(nr===3&&nc===C){delivered++;parts.splice(parts.indexOf(q),1);if(delivered>=target)completeLevel(2500-lost*100);continue}if(nr<0||nr>=R||nc<0||nc>=C){lost++;parts.splice(parts.indexOf(q),1);if(lost>=5)failLevel(delivered*100)}else{q.r=nr;q.c=nc}}},draw(c){bg(c,'#33313f');for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,ox+col*cell,oy+r*cell,cell-3,cell-3,'#4d5363','#8f98aa');txt(c,['→','↓','←','↑'][g[r][col]],ox+(col+.5)*cell,oy+(r+.68)*cell,26,'#e7efff')}for(const q of parts)circle(c,ox+(q.c+.5)*cell,oy+(q.r+.5)*cell,11,'#ffda57');txt(c,`Delivered ${delivered}/${target} • Lost ${lost}/5 • Rotate conveyor tiles`,450,40,20)}}
}

function rescueDispatchGame(s){
  const stations=[{x:100,y:110,busy:0},{x:100,y:270,busy:0},{x:100,y:430,busy:0}],incidents=[];let spawn=.5,saved=0,missed=0,time=48,target=10+Math.floor(s.level/4),selected=0,rng=seedForLevel(s,800);
  function dispatch(i){const st=stations[selected],q=incidents[i];if(!q||st.busy>0)return;const travel=Math.hypot(st.x-q.x,st.y-q.y)/170;st.busy=travel*2+q.severity*.7;q.assigned=true;q.timer+=travel*-1.2;setTimeout(()=>{if(!incidents.includes(q))return;incidents.splice(incidents.indexOf(q),1);saved++;if(saved>=target)completeLevel(saved*250-missed*100)},travel*1000)}
  return{keyDown(k){if(k==='ArrowUp')selected=(selected+2)%3;if(k==='ArrowDown')selected=(selected+1)%3},pointer(p,t){if(t!=='pointerdown')return;if(p.x<190){selected=clamp(Math.floor((p.y-70)/160),0,2);return}const i=incidents.findIndex(q=>Math.hypot(p.x-q.x,p.y-q.y)<35);if(i>=0)dispatch(i)},update(dt){time-=dt;spawn-=dt;for(const st of stations)st.busy=Math.max(0,st.busy-dt);if(spawn<=0){incidents.push({x:seededInt(rng,270,830),y:seededInt(rng,80,470),severity:seededInt(rng,1,3),timer:9-seededInt(rng,0,2),assigned:false});spawn=Math.max(1.8,3.7-s.level*.035)}for(const q of [...incidents])if(!q.assigned&&(q.timer-=dt)<=0){incidents.splice(incidents.indexOf(q),1);missed++;if(missed>=4)failLevel(saved*120)}if(time<=0)(saved>=target?completeLevel:failLevel)(saved*180)},draw(c){bg(c,'#26374a');stations.forEach((q,i)=>{rect(c,45,q.y-45,110,90,i===selected?'#5bdcff':'#607790');txt(c,`🚑 ${q.busy>0?Math.ceil(q.busy):'READY'}`,100,q.y+8,16)});for(const q of incidents){circle(c,q.x,q.y,20,['','#65dd8b','#ffcf5b','#ff6479'][q.severity]);txt(c,q.severity,q.x,q.y+7,16,'#162434')}txt(c,`Saved ${saved}/${target} • Missed ${missed}/4 • Choose ambulance, then incident`,500,42,19)}}
}

function spaceColonyGame(s){
  const jobs=['OXYGEN','FOOD','POWER','RESEARCH'],workers=[2,2,2,1];let colonists=7,oxygen=18,food=18,power=16,research=0,day=1,target=18+s.level;
  function adjust(i,d){if(workers[i]+d<0)return;const total=workers.reduce((a,b)=>a+b,0);if(d>0&&total>=colonists)return;workers[i]+=d}function next(){oxygen+=workers[0]*4-colonists*2;food+=workers[1]*3-colonists*1.5;power+=workers[2]*4-(workers[0]+workers[1]+workers[3])*1.2;research+=workers[3]*2;if(oxygen<=0||food<=0||power<=0)return failLevel(research*100);if(research>=target)return completeLevel(3000+Math.floor(oxygen+food+power)*10);day++;if(day%4===0){colonists++;while(workers.reduce((a,b)=>a+b,0)<colonists)workers[1]++}if(day>18)failLevel(research*100)}
  return{keyDown(k){const i={ArrowUp:0,ArrowRight:1,ArrowDown:2,ArrowLeft:3}[k];if(i!==undefined)adjust(i,1);if(k==='Enter'||k==='Space')next()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>420)return next();const i=clamp(Math.floor((p.x-130)/165),0,3);adjust(i,p.y<250?1:-1)},draw(c){bg(c,'#111a36');jobs.forEach((q,i)=>{rect(c,130+i*165,120,145,230,'#27385c','#728bb6');txt(c,q,202+i*165,155,15);txt(c,workers[i],202+i*165,245,52,'#69e0ff');txt(c,'tap top + / bottom −',202+i*165,325,12,'#b9c8e3')});rect(c,330,430,240,55,'#674eaa');txt(c,'ADVANCE DAY',450,466,19);txt(c,`Day ${day}/18 • Colonists ${colonists} • O₂ ${Math.floor(oxygen)} • Food ${Math.floor(food)} • Power ${Math.floor(power)} • Research ${research}/${target}`,450,45,17)}}
}

function ecoBalanceGame(s){
  const R=5,C=8,g=Array.from({length:R},()=>Array(C).fill(0)),types=['FOREST','WETLAND','FARM','TOWN'],cost=[8,10,7,12];let type=0,budget=95,food=0,water=0,bio=0,pop=0,target=35+s.level*2;
  function recalc(){const n=Array(5).fill(0);g.flat().forEach(v=>n[v]++);food=n[3]*7-n[4]*2;water=n[2]*8-n[3]-n[4]*3;bio=n[1]*6+n[2]*5-n[3]*2-n[4]*4;pop=n[4]*8}function place(r,c){if(r<0||r>=R||c<0||c>=C||g[r][c]||budget<cost[type])return;g[r][c]=type+1;budget-=cost[type];recalc();if(pop>=target&&food>=0&&water>=0&&bio>=20)completeLevel(pop*50+bio*30+budget)}
  return{keyDown(k){if(k==='Space'||k==='Enter')type=(type+1)%4},pointer(p,t){if(t!=='pointerdown')return;if(p.y<70){type=clamp(Math.floor(p.x/225),0,3);return}place(Math.floor((p.y-105)/75),Math.floor((p.x-150)/75))},draw(c){bg(c,'#6aa46e');types.forEach((q,i)=>{rect(c,i*225,8,223,48,type===i?'#244d3b':'#3d7052');txt(c,`${q} $${cost[i]}`,i*225+111,39,15)});for(let r=0;r<R;r++)for(let col=0;col<C;col++){const v=g[r][col];rect(c,150+col*75,105+r*75,68,68,v?['','#3f8b4c','#4ca7b7','#d7b75e','#8c7a8e'][v]:'#c8dcb7','#496b61');if(v)txt(c,['','🌲','💧','🌾','🏘️'][v],184+col*75,150+r*75,24)}txt(c,`Budget ${budget} • Population ${pop}/${target} • Food ${food} • Water ${water} • Biodiversity ${bio}`,450,505,18)}}
}

function harborLogisticsGame(s){
  const docks=[{x:210,busy:0,type:0},{x:450,busy:0,type:1},{x:690,busy:0,type:2}],ships=[];let spawn=.5,served=0,late=0,time=50,target=12+Math.floor(s.level/4),rng=seedForLevel(s,830),selected=0;
  function assign(i){const ship=ships[i],dock=docks[selected];if(!ship||dock.busy>0||ship.type!==dock.type)return;dock.busy=3+ship.size;ship.assigned=true;setTimeout(()=>{if(ships.includes(ship)){ships.splice(ships.indexOf(ship),1);served++;if(served>=target)completeLevel(2700-late*120)}},dock.busy*700)}
  return{keyDown(k){if(k==='ArrowLeft')selected=(selected+2)%3;if(k==='ArrowRight')selected=(selected+1)%3},pointer(p,t){if(t!=='pointerdown')return;if(p.y>370){selected=clamp(Math.floor((p.x-100)/240),0,2);return}const i=ships.findIndex(q=>Math.hypot(p.x-q.x,p.y-q.y)<32);if(i>=0)assign(i)},update(dt){time-=dt;spawn-=dt;for(const d of docks)d.busy=Math.max(0,d.busy-dt);if(spawn<=0){ships.push({x:seededInt(rng,120,780),y:90+ships.length*42,type:seededInt(rng,0,2),size:seededInt(rng,1,3),wait:9,assigned:false});spawn=2.2}for(const q of [...ships])if(!q.assigned&&(q.wait-=dt)<=0){ships.splice(ships.indexOf(q),1);late++;if(late>=4)failLevel(served*120)}if(time<=0)failLevel(served*120)},draw(c){bg(c,'#176b91');for(const q of ships){rect(c,q.x-28,q.y-14,56,28,['#55d9ff','#ffd35e','#ff778c'][q.type]);txt(c,q.size,q.x,q.y+6,14,'#173048')}docks.forEach((d,i)=>{rect(c,d.x-90,385,180,105,i===selected?'#edf3ff':'#8d755e','#fff');txt(c,['BLUE','GOLD','RED'][d.type],d.x,420,17,['#34bfea','#d2a600','#e5526b'][d.type]);txt(c,d.busy?`BUSY ${Math.ceil(d.busy)}`:'READY',d.x,466,16,'#28384a')});txt(c,`Served ${served}/${target} • Late ${late}/4 • Match ship color to dock`,450,40,19)}}
}

function castleCommandGame(s){
  const lanes=[145,270,395],units=[0,0,0],enemies=[];let gold=80,spawn=.4,wave=1,kills=0,target=18+s.level,castle=15,type=0;const specs=[{name:'ARCHER',cost:18,dmg:7,rate:.45},{name:'KNIGHT',cost:30,dmg:16,rate:.9},{name:'MAGE',cost:42,dmg:24,rate:1.3}];
  function place(lane){if(gold<specs[type].cost)return;gold-=specs[type].cost;units[lane]=Math.min(3,units[lane]+1)}
  return{keyDown(k){if(k==='Space')type=(type+1)%3},pointer(p,t){if(t!=='pointerdown')return;if(p.y<60){type=clamp(Math.floor(p.x/300),0,2);return}place(clamp(Math.floor((p.y-90)/125),0,2))},update(dt){spawn-=dt;if(spawn<=0){enemies.push({lane:(kills+enemies.length+s.level)%3,x:900,hp:26+s.level*2,speed:35+s.level*.5});spawn=.75}for(const e of enemies){const u=units[e.lane];if(u){const spec=specs[Math.min(2,u-1)];e.hp-=spec.dmg*u*dt/spec.rate}else e.x-=e.speed*dt;if(e.hp<=0){enemies.splice(enemies.indexOf(e),1);gold+=10;kills++;if(kills>=target)completeLevel(castle*180+gold)}else if(e.x<90){enemies.splice(enemies.indexOf(e),1);castle--;if(castle<=0)failLevel(kills*100)}}},draw(c){bg(c,'#4e6c48');specs.forEach((q,i)=>{rect(c,i*300,8,298,44,type===i?'#a87a43':'#6f5538');txt(c,`${q.name} $${q.cost}`,i*300+149,37,16)});rect(c,30,80,80,390,'#8e8b91');lanes.forEach((y,i)=>{rect(c,110,y-42,790,84,'#8e734f');for(let k=0;k<units[i];k++)txt(c,['🏹','⚔️','✨'][Math.min(2,units[i]-1)],145+k*45,y+10,24)});for(const e of enemies){circle(c,e.x,lanes[e.lane],18,'#d74f67');rect(c,e.x-20,lanes[e.lane]-30,40,5,'#26252b');rect(c,e.x-20,lanes[e.lane]-30,40*clamp(e.hp/(26+s.level*2),0,1),5,'#67e78c')}txt(c,`Castle ${castle} • Gold ${gold} • Defeated ${kills}/${target}`,450,525,18)}}
}

function gravityFlipGame(s){
  const p={x:130,y:420,w:28,h:28,vy:0},obstacles=[];let gravity=1,spawn=.5,score=0,target=12+Math.floor(s.level/3);function flip(){gravity*=-1;p.vy=-gravity*220}
  return{keyDown(k){if(k==='Space'||k==='ArrowUp'||k==='ArrowDown')flip()},pointer(p,t){if(t==='pointerdown')flip()},update(dt){spawn-=dt;if(spawn<=0){const top=Math.random()<.5;obstacles.push({x:930,y:top?55:340,w:48,h:145});spawn=1.15}p.vy+=gravity*900*dt;p.y+=p.vy*dt;if(p.y<55){p.y=55;p.vy=0}if(p.y>457){p.y=457;p.vy=0}for(const q of obstacles){q.x-=(220+s.level*2)*dt;if(hit(p,q))return failLevel(score*150)}for(const q of [...obstacles])if(q.x<-60){obstacles.splice(obstacles.indexOf(q),1);score++;if(score>=target)completeLevel(2500)}},draw(c){bg(c,'#151735');rect(c,0,50,W,8,'#71dfff');rect(c,0,490,W,8,'#71dfff');for(const q of obstacles)rect(c,q.x,q.y,q.w,q.h,'#ff5e82');rect(c,p.x,p.y,p.w,p.h,'#ffe15d');txt(c,`Gravity ${gravity>0?'DOWN':'UP'} • Gates ${score}/${target}`,450,35,20)}}
}

function colorDashGame(s){
  const colors=['#ff5f78','#55dfff','#ffe05b','#6de08b'],p={x:100,y:270,color:0},gates=[];let spawn=.4,score=0,target=15+s.level;function change(d){p.color=(p.color+d+4)%4}
  return{keyDown(k){if(k==='ArrowUp'||k==='ArrowRight')change(1);if(k==='ArrowDown'||k==='ArrowLeft')change(-1)},pointer(q,t){if(t==='pointerdown')change(q.x>450?1:-1)},update(dt){spawn-=dt;if(spawn<=0){gates.push({x:930,color:(score+gates.length+s.level)%4});spawn=.85}for(const q of gates)q.x-=(250+s.level*2)*dt;for(const q of [...gates])if(q.x<120){if(q.color!==p.color)return failLevel(score*120);gates.splice(gates.indexOf(q),1);score++;if(score>=target)completeLevel(2500)}},draw(c){bg(c,'#27213b');circle(c,p.x,p.y,28,colors[p.color]);for(const q of gates){rect(c,q.x,60,28,420,colors[q.color]);rect(c,q.x-4,230,36,80,'#27213b')}txt(c,`Match color at each gate • ${score}/${target}`,450,38,20)}}
}

function orbitDefenderGame(s){
  const planet={x:450,y:280,r:75},meteors=[],shots=[];let angle=0,spawn=.3,kills=0,target=12+s.level,cd=0;function fire(){if(cd>0)return;const x=planet.x+Math.cos(angle)*115,y=planet.y+Math.sin(angle)*115;shots.push({x,y,vx:Math.cos(angle)*420,vy:Math.sin(angle)*420});cd=.22}
  return{keyDown(k){if(k==='Space')fire()},update(dt){cd-=dt;if(s.pressed('ArrowLeft','KeyA'))angle-=2.8*dt;if(s.pressed('ArrowRight','KeyD'))angle+=2.8*dt;spawn-=dt;if(spawn<=0){const a=Math.random()*Math.PI*2;meteors.push({x:450+Math.cos(a)*500,y:280+Math.sin(a)*500,vx:-Math.cos(a)*(65+s.level),vy:-Math.sin(a)*(65+s.level),r:14});spawn=.7}for(const q of shots){q.x+=q.vx*dt;q.y+=q.vy*dt}for(const m of meteors){m.x+=m.vx*dt;m.y+=m.vy*dt;if(Math.hypot(m.x-450,m.y-280)<planet.r+m.r)return failLevel(kills*120);for(const q of shots)if(Math.hypot(m.x-q.x,m.y-q.y)<m.r+5){meteors.splice(meteors.indexOf(m),1);shots.splice(shots.indexOf(q),1);kills++;if(kills>=target)completeLevel(2800);break}}},draw(c){bg(c,'#05091b');circle(c,planet.x,planet.y,planet.r,'#3e82c5');const sx=planet.x+Math.cos(angle)*115,sy=planet.y+Math.sin(angle)*115;circle(c,sx,sy,15,'#5ee4ff');for(const m of meteors)circle(c,m.x,m.y,m.r,'#a86e55');for(const q of shots)circle(c,q.x,q.y,4,'#ffe05d');txt(c,`Meteors ${kills}/${target}`,450,35,20)}}
}

function caveExplorerGame(s){
  const R=11,C=17,rng=seedForLevel(s,870),g=Array.from({length:R},()=>Array(C).fill(0));for(let i=0;i<42+s.level;i++)g[seededInt(rng,0,R-1)][seededInt(rng,0,C-1)]=1;g[1][1]=0;g[R-2][C-2]=3;let gems=0;const gemCells=[];for(let i=0;i<5;i++){let r,c;do{r=seededInt(rng,1,R-2);c=seededInt(rng,1,C-2)}while(g[r][c]===2||(r===1&&c===1));g[r][c]=2;gemCells.push([r,c])}
  let cr=1,cc=1;for(const [tr,tc] of [...gemCells,[R-2,C-2]]){while(cr!==tr){g[cr][cc]=g[cr][cc]===2?2:0;cr+=Math.sign(tr-cr)}while(cc!==tc){g[cr][cc]=g[cr][cc]===2?2:0;cc+=Math.sign(tc-cc)}g[cr][cc]=tr===R-2&&tc===C-2?3:2}const p={r:1,c:1};let oxygen=110;
  function move(k){const d=keyDirection(k);if(!d)return;const nr=p.r+d[1],nc=p.c+d[0];if(nr<0||nr>=R||nc<0||nc>=C||g[nr][nc]===1)return;p.r=nr;p.c=nc;oxygen--;if(g[nr][nc]===2){g[nr][nc]=0;gems++}if(g[nr][nc]===3&&gems===5)completeLevel(2600+oxygen*10);if(oxygen<=0)failLevel(gems*200)}
  return{keyDown:move,draw(c){bg(c,'#15171d');const cell=42,ox=93,oy=58;for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,ox+col*cell,oy+r*cell,cell-2,cell-2,g[r][col]===1?'#4b443d':'#2a3033');if(g[r][col]===2)txt(c,'◆',ox+(col+.5)*cell,oy+(r+.68)*cell,22,'#55e6ff');if(g[r][col]===3)txt(c,'🚪',ox+(col+.5)*cell,oy+(r+.68)*cell,22)}circle(c,ox+(p.c+.5)*cell,oy+(p.r+.5)*cell,14,'#ffe05d');txt(c,`Gems ${gems}/5 • Oxygen ${oxygen}`,450,36,20)}}
}

function treasureMapGame(s){
  const N=9,rng=seedForLevel(s,890),treasure=[seededInt(rng,0,N-1),seededInt(rng,0,N-1)],cell=48,ox=234,oy=70;let digs=8,found=false,marks=[];
  function dig(r,c){if(found||digs<=0||r<0||r>=N||c<0||c>=N)return;digs--;const dist=Math.abs(r-treasure[0])+Math.abs(c-treasure[1]);marks.push({r,c,dist});if(!dist){found=true;completeLevel(2400+digs*150)}else if(!digs)failLevel(0)}
  return{pointer(p,t){if(t==='pointerdown')dig(Math.floor((p.y-oy)/cell),Math.floor((p.x-ox)/cell))},draw(c){bg(c,'#d9c486');for(let r=0;r<N;r++)for(let col=0;col<N;col++){rect(c,ox+col*cell,oy+r*cell,cell-2,cell-2,'#eadba8','#806d45');const m=marks.find(q=>q.r===r&&q.c===col);if(m)txt(c,m.dist||'★',ox+(col+.5)*cell,oy+(r+.68)*cell,20,m.dist?'#6c4b29':'#e04455')}txt(c,`Digs ${digs} • Numbers show Manhattan distance to treasure`,450,38,19)}}
}

function signalSwitchGame(s){
  const switches=[false,false,false,false],trains=[];let spawn=.2,delivered=0,crashed=0,target=10+s.level;function toggle(i){switches[i]=!switches[i]}
  return{keyDown(k){const i={Digit1:0,Digit2:1,Digit3:2,Digit4:3}[k];if(i!==undefined)toggle(i)},pointer(p,t){if(t==='pointerdown')toggle(clamp(Math.floor((p.x-170)/150),0,3))},update(dt){spawn-=dt;if(spawn<=0){trains.push({x:0,lane:(delivered+trains.length)%2,color:(delivered+trains.length+s.level)%2,passed:new Set()});spawn=1.15}for(const q of [...trains]){q.x+=150*dt;[220,390,560,730].forEach((x,i)=>{if(q.x>=x&&!q.passed.has(i)){q.passed.add(i);if(switches[i])q.lane=1-q.lane}});if(q.x>900){if(q.lane===q.color){delivered++;if(delivered>=target)completeLevel(2500-crashed*100)}else{crashed++;if(crashed>=4)failLevel(delivered*100)}trains.splice(trains.indexOf(q),1)}}},draw(c){bg(c,'#436046');for(let lane=0;lane<2;lane++){c.strokeStyle='#d2c39d';c.lineWidth=8;c.beginPath();c.moveTo(0,180+lane*180);c.lineTo(W,180+lane*180);c.stroke()}switches.forEach((v,i)=>{circle(c,220+i*170,270,18,v?'#ffe05d':'#87958b');txt(c,i+1,220+i*170,277,14,'#24352b')});for(const q of trains)rect(c,q.x-28,160+q.lane*180,56,40,q.color?'#ff647d':'#55dfff');txt(c,`Correct routes ${delivered}/${target} • Mistakes ${crashed}/4`,450,38,20)}}
}

function conveyorSortGame(s){
  const items=[];let gate=1,spawn=.2,sorted=0,wrong=0,target=14+s.level;function flip(){gate=1-gate}
  return{keyDown(k){if(k==='Space'||k==='ArrowUp'||k==='ArrowDown')flip()},pointer(p,t){if(t==='pointerdown')flip()},update(dt){spawn-=dt;if(spawn<=0){items.push({x:0,color:(sorted+items.length+s.level)%2,lane:1});spawn=.8}for(const q of items){q.x+=190*dt;if(q.x>430&&q.x<450)q.lane=gate;if(q.x>900){if(q.lane===q.color){sorted++;if(sorted>=target)completeLevel(2500)}else{wrong++;if(wrong>=5)failLevel(sorted*100)}items.splice(items.indexOf(q),1)}}},draw(c){bg(c,'#383c48');rect(c,0,245,440,50,'#68707f');rect(c,440,125,460,50,'#68707f');rect(c,440,365,460,50,'#68707f');for(const q of items)rect(c,q.x-18,(q.x<440?250:q.lane?370:130),36,36,q.color?'#ff657d':'#55dfff');txt(c,gate?'↓':'↑',440,300,48,'#ffe05d');txt(c,`Sorted ${sorted}/${target} • Wrong ${wrong}/5 • Switch gate`,450,38,20)}}
}

function droneDeliveryGame(s){
  const p={x:100,y:270,vx:0,vy:0},pads=[{x:760,y:100,done:false},{x:780,y:420,done:false},{x:500,y:260,done:false}],wind=Math.sin(s.level)*35;let battery=100,packages=3;
  return{keyDown(k){if(k==='Space'&&packages>0){const q=pads.find(q=>!q.done&&Math.hypot(p.x-q.x,p.y-q.y)<45);if(q){q.done=true;packages--;if(!packages)completeLevel(Math.floor(battery)*25)}}},update(dt){const a=190;if(s.pressed('ArrowLeft','KeyA'))p.vx-=a*dt;if(s.pressed('ArrowRight','KeyD'))p.vx+=a*dt;if(s.pressed('ArrowUp','KeyW'))p.vy-=a*dt;if(s.pressed('ArrowDown','KeyS'))p.vy+=a*dt;p.vx+=wind*dt;p.vx*=.985;p.vy*=.985;p.x=clamp(p.x+p.vx*dt,20,880);p.y=clamp(p.y+p.vy*dt,65,510);battery-=dt*(1.2+Math.hypot(p.vx,p.vy)/250);if(battery<=0)failLevel((3-packages)*600)},draw(c){bg(c,'#8ed6f0');for(const q of pads){circle(c,q.x,q.y,30,q.done?'#66d98d':'#f0c85c');txt(c,q.done?'✓':'P',q.x,q.y+7,18,'#24404b')}txt(c,'🚁',p.x,p.y+12,34);txt(c,`Packages ${packages} • Battery ${Math.ceil(battery)}% • Wind ${wind>0?'→':'←'} • Space delivers`,450,38,19)}}
}

function submarineSonarGame(s){
  const N=12,rng=seedForLevel(s,920),mines=new Set(),treasures=new Set();while(mines.size<16)mines.add(`${seededInt(rng,0,N-1)},${seededInt(rng,0,N-1)}`);while(treasures.size<4){const k=`${seededInt(rng,0,N-1)},${seededInt(rng,0,N-1)}`;if(!mines.has(k))treasures.add(k)}const p={r:0,c:0};mines.delete('0,0');let found=0,oxygen=60,ping=0;
  function nearest(){let d=99;for(const k of mines){const[r,c]=k.split(',').map(Number);d=Math.min(d,Math.abs(r-p.r)+Math.abs(c-p.c))}return d}function move(k){const d=keyDirection(k);if(!d)return;const nr=clamp(p.r+d[1],0,N-1),nc=clamp(p.c+d[0],0,N-1);p.r=nr;p.c=nc;oxygen--;const key=`${nr},${nc}`;if(mines.has(key))return failLevel(found*500);if(treasures.delete(key)){found++;if(found===4)completeLevel(2600+oxygen*10)}if(oxygen<=0)failLevel(found*400)}
  return{keyDown(k){if(k==='Space')ping=nearest();else move(k)},draw(c){bg(c,'#062840');const cell=36,ox=234,oy=70;for(let r=0;r<N;r++)for(let col=0;col<N;col++)rect(c,ox+col*cell,oy+r*cell,cell-2,cell-2,'#0d4968','#206889');txt(c,'⚓',ox+(p.c+.5)*cell,oy+(p.r+.7)*cell,23);txt(c,`Treasure ${found}/4 • Oxygen ${oxygen} • Sonar ${ping?`${ping} squares to nearest mine`:'press Space to ping'}`,450,38,18)}}
}

function snowboardSlalomGame(s){
  const p={x:450,y:430},gates=[];let spawn=.2,passed=0,missed=0,target=16+s.level;
  return{update(dt){const v=330;if(s.pressed('ArrowLeft','KeyA'))p.x-=v*dt;if(s.pressed('ArrowRight','KeyD'))p.x+=v*dt;p.x=clamp(p.x,70,830);spawn-=dt;if(spawn<=0){gates.push({x:120+Math.random()*660,y:60,w:110});spawn=.75}for(const q of gates)q.y+=(200+s.level*2)*dt;for(const q of [...gates])if(q.y>430){if(Math.abs(p.x-q.x)<q.w/2)passed++;else missed++;gates.splice(gates.indexOf(q),1);if(passed>=target)completeLevel(2600-missed*100);if(missed>=5)failLevel(passed*100)}},draw(c){bg(c,'#dceeff');for(const q of gates){rect(c,q.x-q.w/2,q.y,8,55,'#e64f68');rect(c,q.x+q.w/2,q.y,8,55,'#468ad2')}txt(c,'🏂',p.x,p.y+18,38);txt(c,`Gates ${passed}/${target} • Missed ${missed}/5`,450,38,20,'#27425d')}}
}

function tableTennisGame(s){
  const p={x:350,y:455,w:200},cpu={x:350,y:70,w:200},ball={x:450,y:270,vx:150,vy:220},two=s.mode==='2P';let a=0,b=0;function reset(dir){Object.assign(ball,{x:450,y:270,vx:(Math.random()-.5)*220,vy:240*dir})}
  return{update(dt){const v=420;if(s.pressed('ArrowLeft'))p.x-=v*dt;if(s.pressed('ArrowRight'))p.x+=v*dt;if(two){if(s.pressed('KeyA'))cpu.x-=v*dt;if(s.pressed('KeyD'))cpu.x+=v*dt}else cpu.x+=clamp(ball.x-(cpu.x+cpu.w/2),-v*dt*.72,v*dt*.72);p.x=clamp(p.x,30,870-p.w);cpu.x=clamp(cpu.x,30,870-cpu.w);ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<15||ball.x>885)ball.vx*=-1;if(ball.vy>0&&ball.y>445&&ball.x>p.x&&ball.x<p.x+p.w){ball.vy=-Math.abs(ball.vy)-8;ball.vx+=(ball.x-(p.x+p.w/2))*2.8}if(ball.vy<0&&ball.y<95&&ball.x>cpu.x&&ball.x<cpu.x+cpu.w){ball.vy=Math.abs(ball.vy)+8;ball.vx+=(ball.x-(cpu.x+cpu.w/2))*2.8}if(ball.y>540){b++;reset(-1)}if(ball.y<0){a++;reset(1)}if(a>=7||b>=7)(a>b?completeLevel:failLevel)(a*350)},draw(c){bg(c,'#174e77');rect(c,0,267,W,6,'#fff');rect(c,p.x,470,p.w,14,'#55ddff');rect(c,cpu.x,56,cpu.w,14,'#ff657c');circle(c,ball.x,ball.y,10,'#fff');txt(c,`${a} — ${b}${two?'':' • CPU'}`,450,38,24)}}
}

function wordLadderGame(s){
  const ladders=[['COLD','CORD','CARD','WARD','WARM'],['HIT','HOT','DOT','DOG','COG'],['HEAD','HEAL','TEAL','TELL','TALL'],['SAND','SEND','SEED','NEED'],['FIRE','FIVE','DIVE','DOVE','LOVE']],ladder=ladders[(s.level-1)%ladders.length];let step=0,typed='';const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';function submit(){if(typed===ladder[step+1]){step++;typed='';if(step===ladder.length-1)completeLevel(2500)}else{typed='';toast('That is not the next one-letter change')}}
  return{keyDown(k){if(/^Key[A-Z]$/.test(k)&&typed.length<ladder[0].length)typed+=k.slice(3);if(k==='Backspace')typed=typed.slice(0,-1);if(k==='Enter')submit()},pointer(p,t){if(t!=='pointerdown')return;if(p.y>430){const i=Math.floor((p.x-85)/28);if(i>=0&&i<26&&typed.length<ladder[0].length)typed+=letters[i]}else if(p.y>350)submit()},draw(c){bg(c,'#26304e');txt(c,`${ladder[0]}  →  ${ladder.at(-1)}`,450,90,38);txt(c,ladder.slice(0,step+1).join(' → '),450,180,25,'#66e1a1');txt(c,(typed||'_'.repeat(ladder[0].length)).split('').join(' '),450,285,40,'#ffe05d');rect(c,340,345,220,55,'#6c55a5');txt(c,'SUBMIT',450,381,18);for(let i=0;i<26;i++){rect(c,85+i*28,445,25,34,'#3d557e');txt(c,letters[i],97+i*28,468,14)}}
}
}

function cipherLabGame(s){
  const phrases=['ARCADE HERO','SECRET CODE','NINTENDO GAME','PUZZLE MASTER','LEVEL COMPLETE'],plain=phrases[(s.level-1)%phrases.length],shift=1+(s.level*3)%25,cipher=[...plain].map(ch=>/[A-Z]/.test(ch)?String.fromCharCode(65+(ch.charCodeAt(0)-65+shift)%26):ch).join('');let guess=0;
  function check(){if(guess===shift)completeLevel(2500);else toast('Not that shift—compare repeated letters')}
  return{keyDown(k){if(k==='ArrowLeft')guess=(guess+25)%26;if(k==='ArrowRight')guess=(guess+1)%26;if(k==='Enter'||k==='Space')check()},pointer(p,t){if(t!=='pointerdown')return;if(p.x<350)guess=(guess+25)%26;else if(p.x>550)guess=(guess+1)%26;else check()},draw(c){bg(c,'#201c3d');txt(c,'DECODE THIS CAESAR CIPHER',450,85,22);txt(c,cipher,450,165,35,'#ffdf62');const decoded=[...cipher].map(ch=>/[A-Z]/.test(ch)?String.fromCharCode(65+(ch.charCodeAt(0)-65-guess+26)%26):ch).join('');txt(c,decoded,450,275,32,'#5ee4ff');rect(c,180,360,180,65,'#435777');txt(c,'◀ SHIFT',270,402,18);rect(c,360,360,180,65,'#694f9a');txt(c,guess,450,405,30);rect(c,540,360,180,65,'#435777');txt(c,'SHIFT ▶',630,402,18);txt(c,'Tap center to submit',450,480,17)}}
}

function fractionForgeGame(s){
  let score=0,round=0,target=8+Math.floor(s.level/5),q,buttons=[];function next(){const den=[4,6,8,10,12][round%5],num=1+((round+s.level)%(den-1)),factor=2+round%3,ans=`${num*factor}/${den*factor}`;q={text:`${num}/${den}`,ans};buttons=[ans,`${num+1}/${den}`,`${num}/${den+1}`,`${num*2+1}/${den*2}`].sort(()=>Math.random()-.5).map((v,i)=>({x:150+(i%2)*310,y:260+Math.floor(i/2)*95,w:280,h:70,v}))}next();function pick(v){if(v===q.ans){score++;round++;if(score>=target)return completeLevel(score*300);next()}else failLevel(score*150)}
  return{pointer(p,t){if(t==='pointerdown'){const b=buttons.find(q=>buttonHit(p,q));if(b)pick(b.v)}},keyDown(k){const i={Digit1:0,Digit2:1,Digit3:2,Digit4:3}[k];if(i!==undefined)pick(buttons[i].v)},draw(c){bg(c,'#17354b');txt(c,`Choose a fraction equivalent to ${q.text}`,450,150,34);buttons.forEach((b,i)=>{rect(c,b.x,b.y,b.w,b.h,'#315f7c');txt(c,`${i+1}. ${b.v}`,b.x+b.w/2,b.y+46,24)});txt(c,`Correct ${score}/${target}`,450,40,20)}}
}

function melodyMemoryGame(s){
  const notes=['C','D','E','G'],seq=[];let round=0,target=5+Math.floor(s.level/6),showing=false,input=0,lit=-1;function playRound(){seq.push((round*3+s.level)%4);showing=true;input=0;let i=0;const tick=()=>{if(i>=seq.length){lit=-1;showing=false;return}lit=seq[i++];setTimeout(()=>{lit=-1;setTimeout(tick,140)},320)};tick()}setTimeout(playRound,400);function tap(i){if(showing)return;if(i!==seq[input])return failLevel(round*300);input++;if(input===seq.length){round++;if(round>=target)return completeLevel(2800);setTimeout(playRound,350)}}
  return{keyDown(k){const i={ArrowLeft:0,ArrowDown:1,ArrowUp:2,ArrowRight:3,KeyA:0,KeyS:1,KeyW:2,KeyD:3}[k];if(i!==undefined)tap(i)},pointer(p,t){if(t==='pointerdown')tap(clamp(Math.floor((p.x-170)/140),0,3))},draw(c){bg(c,'#271846');notes.forEach((n,i)=>{rect(c,170+i*140,200,120,160,lit===i?'#ffe05d':'#6a52a0');txt(c,n,230+i*140,300,42,lit===i?'#2a2042':'#fff')});txt(c,`Melody ${round}/${target} • ${showing?'Listen':'Repeat'}`,450,70,24)}}
}

function beatBuilderGame(s){
  const R=4,C=8,target=Array.from({length:R},(_,r)=>Array.from({length:C},(_,c)=>((c*3+r+s.level)%7===0))),g=Array.from({length:R},()=>Array(C).fill(false));let plays=0;function check(){let errors=0;for(let r=0;r<R;r++)for(let c=0;c<C;c++)if(g[r][c]!==target[r][c])errors++;if(!errors)completeLevel(2600);else{plays++;toast(`${errors} beat${errors===1?'':'s'} differ`)}}
  return{keyDown(k){if(k==='Space'||k==='Enter')check()},pointer(p,t){if(t!=='pointerdown')return;if(p.y<400){const c=Math.floor((p.x-210)/60),r=Math.floor((p.y-110)/65);if(g[r]?.[c]!==undefined)g[r][c]=!g[r][c]}else check()},draw(c){bg(c,'#151d38');for(let r=0;r<R;r++)for(let col=0;col<C;col++){rect(c,210+col*60,110+r*65,52,52,g[r][col]?'#58ddff':'#304260','#8092b2');if(s.level<4&&target[r][col])circle(c,236+col*60,136+r*65,5,'#ffe05d')}rect(c,340,430,220,55,'#684fa0');txt(c,'CHECK BEAT',450,466,18);txt(c,`Build the rhythm pattern • Attempts ${plays}`,450,55,20)}}
}

function meteorMinerGame(s){
  const rocks=[];let energy=100,shield=60,ore=0,target=28+s.level,spawn=.2,mode=0;function switchMode(){mode=1-mode}
  return{keyDown(k){if(k==='Space'||k==='Enter')switchMode()},pointer(p,t){if(t==='pointerdown')switchMode()},update(dt){spawn-=dt;if(spawn<=0){rocks.push({x:930,y:80+Math.random()*380,hp:12+Math.random()*18,ore:3+Math.floor(Math.random()*5),danger:Math.random()<.35});spawn=.65}energy=Math.min(100,energy+dt*8);for(const q of rocks){q.x-=85*dt;if(mode===0&&energy>0&&q.x<700){q.hp-=22*dt;energy-=12*dt;if(q.hp<=0){ore+=q.ore;rocks.splice(rocks.indexOf(q),1);if(ore>=target)completeLevel(2800+Math.floor(shield)*10)}}if(q.x<120){if(q.danger){shield-=14;if(shield<=0)return failLevel(ore*80)}rocks.splice(rocks.indexOf(q),1)}}},draw(c){bg(c,'#080d20');rect(c,60,200,90,140,'#4d6f91');for(const q of rocks)circle(c,q.x,q.y,18,q.danger?'#d85868':'#8d705f');if(mode===0){c.strokeStyle='#5ee5ff';c.lineWidth=4;c.beginPath();c.moveTo(150,270);c.lineTo(700,270);c.stroke()}txt(c,mode===0?'MINING LASER':'SHIELD RECHARGE',450,55,22);txt(c,`Ore ${ore}/${target} • Energy ${Math.ceil(energy)} • Shield ${Math.ceil(shield)} • Space changes mode`,450,510,18)}}
}
